// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.Azure.Search.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Microsoft.Rest.Azure;

    /// <summary>
    /// Divides text at non-letters.
    /// </summary>
    [JsonObject("#Microsoft.Azure.Search.LowercaseTokenizer")]
    public partial class LowercaseTokenizer : Tokenizer
    {
        /// <summary>
        /// Initializes a new instance of the LowercaseTokenizer class.
        /// </summary>
        public LowercaseTokenizer() { }

        /// <summary>
        /// Initializes a new instance of the LowercaseTokenizer class.
        /// </summary>
        public LowercaseTokenizer(string name)
            : base(name)
        {
        }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public override void Validate()
        {
            base.Validate();
        }
    }
}
