// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// </auto-generated>

namespace Microsoft.Azure.Management.DevTestLab.Fluent.Models
{
    using Microsoft.Azure;
    using Microsoft.Azure.Management;
    using Microsoft.Azure.Management.DevTestLab;
    using Microsoft.Azure.Management.DevTestLab.Fluent;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Request body for evaluating a policy set.
    /// </summary>
    public partial class EvaluatePoliciesRequest
    {
        /// <summary>
        /// Initializes a new instance of the EvaluatePoliciesRequest class.
        /// </summary>
        public EvaluatePoliciesRequest()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EvaluatePoliciesRequest class.
        /// </summary>
        /// <param name="policies">Policies to evaluate.</param>
        public EvaluatePoliciesRequest(IList<EvaluatePoliciesPropertiesInner> policies = default(IList<EvaluatePoliciesPropertiesInner>))
        {
            Policies = policies;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets policies to evaluate.
        /// </summary>
        [JsonProperty(PropertyName = "policies")]
        public IList<EvaluatePoliciesPropertiesInner> Policies { get; set; }

    }
}
