// <auto-generated/>

#nullable disable

using System.IO;
using System;
using System.ClientModel;

using Payload.MultiPart;

namespace Payload.MultiPart.Models
{
    public partial class FileWithHttpPartOptionalContentTypeRequest
    {
        public FileWithHttpPartOptionalContentTypeRequest(string filename, string profileImagePath)
        {
            Argument.AssertNotNullOrEmpty(filename, nameof(filename));
            Argument.AssertNotNullOrEmpty(profileImagePath, nameof(profileImagePath));

            ProfileImage = new(profileImagePath)
            {
                Filename = filename,
            };
        }

        public FileWithHttpPartOptionalContentTypeRequest(string filename, Stream profileImage)
        {
            Argument.AssertNotNullOrEmpty(filename, nameof(filename));
            Argument.AssertNotNull(profileImage, nameof(profileImage));

            ProfileImage = new(profileImage)
            {
                Filename = filename,
            };
        }

        public FileWithHttpPartOptionalContentTypeRequest(string filename, BinaryData profileImage)
        {
            Argument.AssertNotNullOrEmpty(filename, nameof(filename));
            Argument.AssertNotNull(profileImage, nameof(profileImage));

            ProfileImage = new(profileImage)
            {
                Filename = filename,
            };
        }

        /// <summary> Gets the profile image. </summary>
        public FileBinaryContent ProfileImage { get; }
    }
}
