// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Linq;
using Azure.Core;

namespace Samples
{
    internal static partial class RawRequestUriBuilderExtensions
    {
        public static void AppendQueryDelimited<T>(this global::Azure.Core.RawRequestUriBuilder builder, string name, global::System.Collections.Generic.IEnumerable<T> value, string delimiter, global::Samples.SerializationFormat format = global::Samples.SerializationFormat.Default, bool escape = true)
        {
            delimiter ??= ",";
            global::System.Collections.Generic.IEnumerable<string> stringValues = value.Select(v => global::Samples.TypeFormatters.ConvertToString(v, format));
            builder.AppendQuery(name, string.Join(delimiter, stringValues), escape);
        }
    }
}
