#!/bin/bash

AZURE_TEST_MODE=record \
SUBSCRIPTION_ID="$SUBSCRIPTION_ID" \
RESOURCE_GROUP="$RESOURCE_GROUP" \
CNI_NETWORK_ID="$CNI_NETWORK_ID" \
L2_ISOLATION_DOMAIN_ID="$L2_ISOLATION_DOMAIN_ID" \
L3_ISOLATION_DOMAIN_ID="$L3_ISOLATION_DOMAIN_ID" \
TRUNKED_NETWORK_ID="$TRUNKED_NETWORK_ID" \
CLUSTER_EXTENDED_LOCATION="$CLUSTER_EXTENDED_LOCATION" \
CLOUD_SERVICES_NETWORK_ID="$CLOUD_SERVICES_NETWORK_ID" \
SSH_PUBLIC_KEY="$SSH_PUBLIC_KEY" \
LOCATION="$LOCATION" \
USE_DEFAULT_CRED=true \
dotnet test --framework net7.0 --filter "KubernetesClusters"
