// Copyright (c) Microsoft and contributors.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.Azure.Batch.Protocol.Models
{

    /// <summary>
    /// Defines values for JobState.
    /// </summary>
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum JobState
    {
        [System.Runtime.Serialization.EnumMember(Value = "active")]
        Active,
        [System.Runtime.Serialization.EnumMember(Value = "disabling")]
        Disabling,
        [System.Runtime.Serialization.EnumMember(Value = "disabled")]
        Disabled,
        [System.Runtime.Serialization.EnumMember(Value = "enabling")]
        Enabling,
        [System.Runtime.Serialization.EnumMember(Value = "terminating")]
        Terminating,
        [System.Runtime.Serialization.EnumMember(Value = "completed")]
        Completed,
        [System.Runtime.Serialization.EnumMember(Value = "deleting")]
        Deleting
    }
    internal static class JobStateEnumExtension
    {
        internal static string ToSerializedValue(this JobState? value )  =>
            value == null ? null : (( JobState )value).ToSerializedValue();

        internal static string ToSerializedValue(this JobState value )
        {
            switch( value )
            {
                case JobState.Active:
                    return "active";
                case JobState.Disabling:
                    return "disabling";
                case JobState.Disabled:
                    return "disabled";
                case JobState.Enabling:
                    return "enabling";
                case JobState.Terminating:
                    return "terminating";
                case JobState.Completed:
                    return "completed";
                case JobState.Deleting:
                    return "deleting";
            }
            return null;
        }

        internal static JobState? ParseJobState( this string value )
        {
            switch( value )
            {
                case "active":
                    return JobState.Active;
                case "disabling":
                    return JobState.Disabling;
                case "disabled":
                    return JobState.Disabled;
                case "enabling":
                    return JobState.Enabling;
                case "terminating":
                    return JobState.Terminating;
                case "completed":
                    return JobState.Completed;
                case "deleting":
                    return JobState.Deleting;
            }
            return null;
        }
    }
}
