// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.ComponentModel;
using System.Threading;
using Azure;
using Azure.Core;

namespace Samples
{
    public partial class TestClient
    {
        public virtual string Get(global::Azure.MatchConditions matchConditions = default, global::System.Threading.CancellationToken cancellationToken = default)
        {
            return "value";
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::Azure.Core.ForwardsClientCallsAttribute]
        public virtual string Get(string ifMatch, string ifNoneMatch = default, global::System.Threading.CancellationToken cancellationToken = default)
        {
            return this.Get(((ifMatch == null) && (ifNoneMatch == null)) ? ((global::Azure.MatchConditions)null) : new global::Azure.MatchConditions
            {
                IfMatch = (ifMatch != null) ? new global::Azure.ETag(ifMatch) : ((global::Azure.ETag?)null),
                IfNoneMatch = (ifNoneMatch != null) ? new global::Azure.ETag(ifNoneMatch) : ((global::Azure.ETag?)null)
            }, cancellationToken);
        }
    }
}
