namespace Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes
{
    public partial class AzureResourceManagerKubernetesConfigurationExtensionTypesContext : System.ClientModel.Primitives.ModelReaderWriterContext
    {
        internal AzureResourceManagerKubernetesConfigurationExtensionTypesContext() { }
        public static Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.AzureResourceManagerKubernetesConfigurationExtensionTypesContext Default { get { throw null; } }
        protected override bool TryGetTypeBuilderCore(System.Type type, out System.ClientModel.Primitives.ModelReaderWriterTypeBuilder builder) { throw null; }
    }
    public partial class ClusterExtensionTypeCollection : Azure.ResourceManager.ArmCollection, System.Collections.Generic.IAsyncEnumerable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeResource>, System.Collections.Generic.IEnumerable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeResource>, System.Collections.IEnumerable
    {
        protected ClusterExtensionTypeCollection() { }
        public virtual Azure.Response<bool> Exists(string extensionTypeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<bool>> ExistsAsync(string extensionTypeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeResource> Get(string extensionTypeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Pageable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeResource> GetAll(string publisherId = null, string offerId = null, string planId = null, string releaseTrain = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.AsyncPageable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeResource> GetAllAsync(string publisherId = null, string offerId = null, string planId = null, string releaseTrain = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeResource>> GetAsync(string extensionTypeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.NullableResponse<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeResource> GetIfExists(string extensionTypeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.NullableResponse<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeResource>> GetIfExistsAsync(string extensionTypeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        System.Collections.Generic.IAsyncEnumerator<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeResource> System.Collections.Generic.IAsyncEnumerable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeResource>.GetAsyncEnumerator(System.Threading.CancellationToken cancellationToken) { throw null; }
        System.Collections.Generic.IEnumerator<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeResource> System.Collections.Generic.IEnumerable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeResource>.GetEnumerator() { throw null; }
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() { throw null; }
    }
    public partial class ClusterExtensionTypeResource : Azure.ResourceManager.ArmResource, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData>
    {
        public static readonly Azure.Core.ResourceType ResourceType;
        protected ClusterExtensionTypeResource() { }
        public virtual Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData Data { get { throw null; } }
        public virtual bool HasData { get { throw null; } }
        public static Azure.Core.ResourceIdentifier CreateResourceIdentifier(string subscriptionId, string resourceGroupName, string clusterRp, string clusterResourceName, string clusterName, string extensionTypeName) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeResource> Get(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeResource>> GetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeVersionResource> GetClusterExtensionTypeVersion(string versionNumber, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeVersionResource>> GetClusterExtensionTypeVersionAsync(string versionNumber, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeVersionCollection GetClusterExtensionTypeVersions() { throw null; }
        Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class ClusterExtensionTypeVersionCollection : Azure.ResourceManager.ArmCollection, System.Collections.Generic.IAsyncEnumerable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeVersionResource>, System.Collections.Generic.IEnumerable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeVersionResource>, System.Collections.IEnumerable
    {
        protected ClusterExtensionTypeVersionCollection() { }
        public virtual Azure.Response<bool> Exists(string versionNumber, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<bool>> ExistsAsync(string versionNumber, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeVersionResource> Get(string versionNumber, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Pageable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeVersionResource> GetAll(string releaseTrain = null, string majorVersion = null, bool? showLatest = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.AsyncPageable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeVersionResource> GetAllAsync(string releaseTrain = null, string majorVersion = null, bool? showLatest = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeVersionResource>> GetAsync(string versionNumber, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.NullableResponse<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeVersionResource> GetIfExists(string versionNumber, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.NullableResponse<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeVersionResource>> GetIfExistsAsync(string versionNumber, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        System.Collections.Generic.IAsyncEnumerator<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeVersionResource> System.Collections.Generic.IAsyncEnumerable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeVersionResource>.GetAsyncEnumerator(System.Threading.CancellationToken cancellationToken) { throw null; }
        System.Collections.Generic.IEnumerator<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeVersionResource> System.Collections.Generic.IEnumerable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeVersionResource>.GetEnumerator() { throw null; }
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() { throw null; }
    }
    public partial class ClusterExtensionTypeVersionResource : Azure.ResourceManager.ArmResource, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData>
    {
        public static readonly Azure.Core.ResourceType ResourceType;
        protected ClusterExtensionTypeVersionResource() { }
        public virtual Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData Data { get { throw null; } }
        public virtual bool HasData { get { throw null; } }
        public static Azure.Core.ResourceIdentifier CreateResourceIdentifier(string subscriptionId, string resourceGroupName, string clusterRp, string clusterResourceName, string clusterName, string extensionTypeName, string versionNumber) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeVersionResource> Get(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeVersionResource>> GetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class KubernetesConfigurationExtensionTypeData : Azure.ResourceManager.Models.ResourceData, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData>
    {
        internal KubernetesConfigurationExtensionTypeData() { }
        public Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeProperties Properties { get { throw null; } }
        protected virtual Azure.ResourceManager.Models.ResourceData JsonModelCreateCore(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected override void JsonModelWriteCore(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        protected virtual Azure.ResourceManager.Models.ResourceData PersistableModelCreateCore(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual System.BinaryData PersistableModelWriteCore(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public static partial class KubernetesConfigurationExtensionTypesExtensions
    {
        public static Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeResource> GetClusterExtensionType(this Azure.ResourceManager.ArmClient client, Azure.Core.ResourceIdentifier scope, string extensionTypeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public static System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeResource>> GetClusterExtensionTypeAsync(this Azure.ResourceManager.ArmClient client, Azure.Core.ResourceIdentifier scope, string extensionTypeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeResource GetClusterExtensionTypeResource(this Azure.ResourceManager.ArmClient client, Azure.Core.ResourceIdentifier id) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeCollection GetClusterExtensionTypes(this Azure.ResourceManager.ArmClient client, Azure.Core.ResourceIdentifier scope) { throw null; }
        public static Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeVersionResource> GetClusterExtensionTypeVersion(this Azure.ResourceManager.ArmClient client, Azure.Core.ResourceIdentifier scope, string versionNumber, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public static System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeVersionResource>> GetClusterExtensionTypeVersionAsync(this Azure.ResourceManager.ArmClient client, Azure.Core.ResourceIdentifier scope, string versionNumber, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeVersionResource GetClusterExtensionTypeVersionResource(this Azure.ResourceManager.ArmClient client, Azure.Core.ResourceIdentifier id) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeVersionCollection GetClusterExtensionTypeVersions(this Azure.ResourceManager.ArmClient client, Azure.Core.ResourceIdentifier scope) { throw null; }
        public static Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeResource> GetLocationExtensionType(this Azure.ResourceManager.Resources.SubscriptionResource subscriptionResource, string location, string extensionTypeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public static System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeResource>> GetLocationExtensionTypeAsync(this Azure.ResourceManager.Resources.SubscriptionResource subscriptionResource, string location, string extensionTypeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeResource GetLocationExtensionTypeResource(this Azure.ResourceManager.ArmClient client, Azure.Core.ResourceIdentifier id) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeCollection GetLocationExtensionTypes(this Azure.ResourceManager.Resources.SubscriptionResource subscriptionResource, string location) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeVersionResource GetLocationExtensionTypeVersionResource(this Azure.ResourceManager.ArmClient client, Azure.Core.ResourceIdentifier id) { throw null; }
    }
    public partial class KubernetesConfigurationExtensionTypeVersionForReleaseTrainData : Azure.ResourceManager.Models.ResourceData, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData>
    {
        internal KubernetesConfigurationExtensionTypeVersionForReleaseTrainData() { }
        public Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionForReleaseTrainProperties Properties { get { throw null; } }
        protected virtual Azure.ResourceManager.Models.ResourceData JsonModelCreateCore(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected override void JsonModelWriteCore(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        protected virtual Azure.ResourceManager.Models.ResourceData PersistableModelCreateCore(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual System.BinaryData PersistableModelWriteCore(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class LocationExtensionTypeCollection : Azure.ResourceManager.ArmCollection, System.Collections.Generic.IAsyncEnumerable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeResource>, System.Collections.Generic.IEnumerable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeResource>, System.Collections.IEnumerable
    {
        protected LocationExtensionTypeCollection() { }
        public virtual Azure.Response<bool> Exists(string extensionTypeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<bool>> ExistsAsync(string extensionTypeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeResource> Get(string extensionTypeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Pageable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeResource> GetAll(string publisherId = null, string offerId = null, string planId = null, string releaseTrain = null, string clusterType = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.AsyncPageable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeResource> GetAllAsync(string publisherId = null, string offerId = null, string planId = null, string releaseTrain = null, string clusterType = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeResource>> GetAsync(string extensionTypeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.NullableResponse<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeResource> GetIfExists(string extensionTypeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.NullableResponse<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeResource>> GetIfExistsAsync(string extensionTypeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        System.Collections.Generic.IAsyncEnumerator<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeResource> System.Collections.Generic.IAsyncEnumerable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeResource>.GetAsyncEnumerator(System.Threading.CancellationToken cancellationToken) { throw null; }
        System.Collections.Generic.IEnumerator<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeResource> System.Collections.Generic.IEnumerable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeResource>.GetEnumerator() { throw null; }
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() { throw null; }
    }
    public partial class LocationExtensionTypeResource : Azure.ResourceManager.ArmResource, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData>
    {
        public static readonly Azure.Core.ResourceType ResourceType;
        protected LocationExtensionTypeResource() { }
        public virtual Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData Data { get { throw null; } }
        public virtual bool HasData { get { throw null; } }
        public static Azure.Core.ResourceIdentifier CreateResourceIdentifier(string subscriptionId, string location, string extensionTypeName) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeResource> Get(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeResource>> GetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeVersionResource> GetLocationExtensionTypeVersion(string versionNumber, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeVersionResource>> GetLocationExtensionTypeVersionAsync(string versionNumber, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeVersionCollection GetLocationExtensionTypeVersions() { throw null; }
        Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class LocationExtensionTypeVersionCollection : Azure.ResourceManager.ArmCollection, System.Collections.Generic.IAsyncEnumerable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeVersionResource>, System.Collections.Generic.IEnumerable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeVersionResource>, System.Collections.IEnumerable
    {
        protected LocationExtensionTypeVersionCollection() { }
        public virtual Azure.Response<bool> Exists(string versionNumber, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<bool>> ExistsAsync(string versionNumber, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeVersionResource> Get(string versionNumber, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Pageable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeVersionResource> GetAll(string releaseTrain = null, string clusterType = null, string majorVersion = null, bool? showLatest = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.AsyncPageable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeVersionResource> GetAllAsync(string releaseTrain = null, string clusterType = null, string majorVersion = null, bool? showLatest = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeVersionResource>> GetAsync(string versionNumber, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.NullableResponse<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeVersionResource> GetIfExists(string versionNumber, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.NullableResponse<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeVersionResource>> GetIfExistsAsync(string versionNumber, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        System.Collections.Generic.IAsyncEnumerator<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeVersionResource> System.Collections.Generic.IAsyncEnumerable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeVersionResource>.GetAsyncEnumerator(System.Threading.CancellationToken cancellationToken) { throw null; }
        System.Collections.Generic.IEnumerator<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeVersionResource> System.Collections.Generic.IEnumerable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeVersionResource>.GetEnumerator() { throw null; }
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() { throw null; }
    }
    public partial class LocationExtensionTypeVersionResource : Azure.ResourceManager.ArmResource, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData>
    {
        public static readonly Azure.Core.ResourceType ResourceType;
        protected LocationExtensionTypeVersionResource() { }
        public virtual Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData Data { get { throw null; } }
        public virtual bool HasData { get { throw null; } }
        public static Azure.Core.ResourceIdentifier CreateResourceIdentifier(string subscriptionId, string location, string extensionTypeName, string versionNumber) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeVersionResource> Get(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeVersionResource>> GetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
}
namespace Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Mocking
{
    public partial class MockableKubernetesConfigurationExtensionTypesArmClient : Azure.ResourceManager.ArmResource
    {
        protected MockableKubernetesConfigurationExtensionTypesArmClient() { }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeResource> GetClusterExtensionType(Azure.Core.ResourceIdentifier scope, string extensionTypeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeResource>> GetClusterExtensionTypeAsync(Azure.Core.ResourceIdentifier scope, string extensionTypeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeResource GetClusterExtensionTypeResource(Azure.Core.ResourceIdentifier id) { throw null; }
        public virtual Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeCollection GetClusterExtensionTypes(Azure.Core.ResourceIdentifier scope) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeVersionResource> GetClusterExtensionTypeVersion(Azure.Core.ResourceIdentifier scope, string versionNumber, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeVersionResource>> GetClusterExtensionTypeVersionAsync(Azure.Core.ResourceIdentifier scope, string versionNumber, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeVersionResource GetClusterExtensionTypeVersionResource(Azure.Core.ResourceIdentifier id) { throw null; }
        public virtual Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.ClusterExtensionTypeVersionCollection GetClusterExtensionTypeVersions(Azure.Core.ResourceIdentifier scope) { throw null; }
        public virtual Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeResource GetLocationExtensionTypeResource(Azure.Core.ResourceIdentifier id) { throw null; }
        public virtual Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeVersionResource GetLocationExtensionTypeVersionResource(Azure.Core.ResourceIdentifier id) { throw null; }
    }
    public partial class MockableKubernetesConfigurationExtensionTypesSubscriptionResource : Azure.ResourceManager.ArmResource
    {
        protected MockableKubernetesConfigurationExtensionTypesSubscriptionResource() { }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeResource> GetLocationExtensionType(string location, string extensionTypeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeResource>> GetLocationExtensionTypeAsync(string location, string extensionTypeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.LocationExtensionTypeCollection GetLocationExtensionTypes(string location) { throw null; }
    }
}
namespace Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models
{
    public static partial class ArmKubernetesConfigurationExtensionTypesModelFactory
    {
        public static Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeClusterScopeSettings KubernetesConfigurationExtensionTypeClusterScopeSettings(Azure.Core.ResourceIdentifier id = null, string name = null, Azure.Core.ResourceType resourceType = default(Azure.Core.ResourceType), Azure.ResourceManager.Models.SystemData systemData = null, bool? isMultipleInstancesAllowed = default(bool?), string defaultReleaseNamespace = null) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeData KubernetesConfigurationExtensionTypeData(Azure.Core.ResourceIdentifier id = null, string name = null, Azure.Core.ResourceType resourceType = default(Azure.Core.ResourceType), Azure.ResourceManager.Models.SystemData systemData = null, Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeProperties properties = null) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypePlanInfo KubernetesConfigurationExtensionTypePlanInfo(string publisherId = null, string planId = null, string offerId = null) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeProperties KubernetesConfigurationExtensionTypeProperties(bool? isSystemExtension = default(bool?), bool? isManagedIdentityRequired = default(bool?), string description = null, string publisher = null, Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypePlanInfo planInfo = null, System.Collections.Generic.IEnumerable<string> supportedClusterTypes = null, Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeSupportedScopes supportedScopes = null) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeSupportedScopes KubernetesConfigurationExtensionTypeSupportedScopes(string defaultScope = null, Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeClusterScopeSettings clusterScopeSettings = null) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeUnsupportedKubernetesVersions KubernetesConfigurationExtensionTypeUnsupportedKubernetesVersions(System.Collections.Generic.IEnumerable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionUnsupportedKubernetesMatrixItem> connectedCluster = null, System.Collections.Generic.IEnumerable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionUnsupportedKubernetesMatrixItem> appliances = null, System.Collections.Generic.IEnumerable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionUnsupportedKubernetesMatrixItem> provisionedCluster = null, System.Collections.Generic.IEnumerable<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionUnsupportedKubernetesMatrixItem> managedCluster = null) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.KubernetesConfigurationExtensionTypeVersionForReleaseTrainData KubernetesConfigurationExtensionTypeVersionForReleaseTrainData(Azure.Core.ResourceIdentifier id = null, string name = null, Azure.Core.ResourceType resourceType = default(Azure.Core.ResourceType), Azure.ResourceManager.Models.SystemData systemData = null, Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionForReleaseTrainProperties properties = null) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionForReleaseTrainProperties KubernetesConfigurationExtensionTypeVersionForReleaseTrainProperties(string version = null, Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeUnsupportedKubernetesVersions unsupportedKubernetesVersions = null, System.Collections.Generic.IEnumerable<string> supportedClusterTypes = null) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionUnsupportedKubernetesMatrixItem KubernetesConfigurationExtensionTypeVersionUnsupportedKubernetesMatrixItem(System.Collections.Generic.IEnumerable<string> distributions = null, System.Collections.Generic.IEnumerable<string> unsupportedVersions = null) { throw null; }
    }
    public partial class KubernetesConfigurationExtensionTypeClusterScopeSettings : Azure.ResourceManager.Models.ResourceData, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeClusterScopeSettings>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeClusterScopeSettings>
    {
        internal KubernetesConfigurationExtensionTypeClusterScopeSettings() { }
        public string DefaultReleaseNamespace { get { throw null; } }
        public bool? IsMultipleInstancesAllowed { get { throw null; } }
        protected virtual Azure.ResourceManager.Models.ResourceData JsonModelCreateCore(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected override void JsonModelWriteCore(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        protected virtual Azure.ResourceManager.Models.ResourceData PersistableModelCreateCore(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual System.BinaryData PersistableModelWriteCore(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeClusterScopeSettings System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeClusterScopeSettings>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeClusterScopeSettings>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeClusterScopeSettings System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeClusterScopeSettings>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeClusterScopeSettings>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeClusterScopeSettings>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class KubernetesConfigurationExtensionTypePlanInfo : System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypePlanInfo>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypePlanInfo>
    {
        internal KubernetesConfigurationExtensionTypePlanInfo() { }
        public string OfferId { get { throw null; } }
        public string PlanId { get { throw null; } }
        public string PublisherId { get { throw null; } }
        protected virtual Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypePlanInfo JsonModelCreateCore(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual void JsonModelWriteCore(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        protected virtual Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypePlanInfo PersistableModelCreateCore(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual System.BinaryData PersistableModelWriteCore(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypePlanInfo System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypePlanInfo>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypePlanInfo>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypePlanInfo System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypePlanInfo>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypePlanInfo>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypePlanInfo>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class KubernetesConfigurationExtensionTypeProperties : System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeProperties>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeProperties>
    {
        internal KubernetesConfigurationExtensionTypeProperties() { }
        public string Description { get { throw null; } }
        public bool? IsManagedIdentityRequired { get { throw null; } }
        public bool? IsSystemExtension { get { throw null; } }
        public Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypePlanInfo PlanInfo { get { throw null; } }
        public string Publisher { get { throw null; } }
        public System.Collections.Generic.IList<string> SupportedClusterTypes { get { throw null; } }
        public Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeSupportedScopes SupportedScopes { get { throw null; } }
        protected virtual Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeProperties JsonModelCreateCore(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual void JsonModelWriteCore(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        protected virtual Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeProperties PersistableModelCreateCore(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual System.BinaryData PersistableModelWriteCore(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeProperties System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeProperties>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeProperties>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeProperties System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeProperties>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeProperties>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeProperties>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class KubernetesConfigurationExtensionTypeSupportedScopes : System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeSupportedScopes>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeSupportedScopes>
    {
        internal KubernetesConfigurationExtensionTypeSupportedScopes() { }
        public Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeClusterScopeSettings ClusterScopeSettings { get { throw null; } }
        public string DefaultScope { get { throw null; } }
        protected virtual Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeSupportedScopes JsonModelCreateCore(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual void JsonModelWriteCore(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        protected virtual Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeSupportedScopes PersistableModelCreateCore(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual System.BinaryData PersistableModelWriteCore(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeSupportedScopes System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeSupportedScopes>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeSupportedScopes>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeSupportedScopes System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeSupportedScopes>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeSupportedScopes>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeSupportedScopes>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class KubernetesConfigurationExtensionTypeUnsupportedKubernetesVersions : System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeUnsupportedKubernetesVersions>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeUnsupportedKubernetesVersions>
    {
        internal KubernetesConfigurationExtensionTypeUnsupportedKubernetesVersions() { }
        public System.Collections.Generic.IList<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionUnsupportedKubernetesMatrixItem> Appliances { get { throw null; } }
        public System.Collections.Generic.IList<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionUnsupportedKubernetesMatrixItem> ConnectedCluster { get { throw null; } }
        public System.Collections.Generic.IList<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionUnsupportedKubernetesMatrixItem> ManagedCluster { get { throw null; } }
        public System.Collections.Generic.IList<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionUnsupportedKubernetesMatrixItem> ProvisionedCluster { get { throw null; } }
        protected virtual Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeUnsupportedKubernetesVersions JsonModelCreateCore(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual void JsonModelWriteCore(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        protected virtual Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeUnsupportedKubernetesVersions PersistableModelCreateCore(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual System.BinaryData PersistableModelWriteCore(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeUnsupportedKubernetesVersions System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeUnsupportedKubernetesVersions>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeUnsupportedKubernetesVersions>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeUnsupportedKubernetesVersions System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeUnsupportedKubernetesVersions>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeUnsupportedKubernetesVersions>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeUnsupportedKubernetesVersions>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class KubernetesConfigurationExtensionTypeVersionForReleaseTrainProperties : System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionForReleaseTrainProperties>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionForReleaseTrainProperties>
    {
        internal KubernetesConfigurationExtensionTypeVersionForReleaseTrainProperties() { }
        public System.Collections.Generic.IList<string> SupportedClusterTypes { get { throw null; } }
        public Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeUnsupportedKubernetesVersions UnsupportedKubernetesVersions { get { throw null; } }
        public string Version { get { throw null; } }
        protected virtual Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionForReleaseTrainProperties JsonModelCreateCore(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual void JsonModelWriteCore(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        protected virtual Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionForReleaseTrainProperties PersistableModelCreateCore(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual System.BinaryData PersistableModelWriteCore(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionForReleaseTrainProperties System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionForReleaseTrainProperties>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionForReleaseTrainProperties>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionForReleaseTrainProperties System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionForReleaseTrainProperties>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionForReleaseTrainProperties>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionForReleaseTrainProperties>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class KubernetesConfigurationExtensionTypeVersionUnsupportedKubernetesMatrixItem : System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionUnsupportedKubernetesMatrixItem>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionUnsupportedKubernetesMatrixItem>
    {
        internal KubernetesConfigurationExtensionTypeVersionUnsupportedKubernetesMatrixItem() { }
        public System.Collections.Generic.IList<string> Distributions { get { throw null; } }
        public System.Collections.Generic.IList<string> UnsupportedVersions { get { throw null; } }
        protected virtual Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionUnsupportedKubernetesMatrixItem JsonModelCreateCore(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual void JsonModelWriteCore(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        protected virtual Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionUnsupportedKubernetesMatrixItem PersistableModelCreateCore(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual System.BinaryData PersistableModelWriteCore(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionUnsupportedKubernetesMatrixItem System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionUnsupportedKubernetesMatrixItem>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionUnsupportedKubernetesMatrixItem>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionUnsupportedKubernetesMatrixItem System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionUnsupportedKubernetesMatrixItem>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionUnsupportedKubernetesMatrixItem>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.ExtensionTypes.Models.KubernetesConfigurationExtensionTypeVersionUnsupportedKubernetesMatrixItem>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
}
