// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using Microsoft.TypeSpec.Generator.Customizations;

namespace Azure.AI.AgentServer.Responses.Models;

// These stubs keep shared OpenAI/Azure.AI.Extensions.OpenAI-owned protocol models from being re-emitted locally.
[CodeGenType("A2APreviewTool")] internal partial class StubA2APreviewTool { }
[CodeGenType("A2AToolCall")] internal partial class StubA2AToolCall { }
[CodeGenType("A2AToolCallOutput")] internal partial class StubA2AToolCallOutput { }
[CodeGenType("AISearchIndexResource")] internal partial class StubAISearchIndexResource { }
[CodeGenType("AgentReference")] internal partial class StubAgentReference { }
[CodeGenType("AgentsPagedResultOutputItem")] internal partial class StubAgentsPagedResultOutputItem { }
[CodeGenType("ApiErrorResponse")] internal partial class StubApiErrorResponse { }
[CodeGenType("ApplyPatchCallOutputStatusParam")] internal partial class StubApplyPatchCallOutputStatusParam { }
[CodeGenType("ApplyPatchCallStatusParam")] internal partial class StubApplyPatchCallStatusParam { }
[CodeGenType("ApplyPatchCreateFileOperationParam")] internal partial class StubApplyPatchCreateFileOperationParam { }
[CodeGenType("ApplyPatchDeleteFileOperationParam")] internal partial class StubApplyPatchDeleteFileOperationParam { }
[CodeGenType("ApplyPatchOperationParam")] internal partial class StubApplyPatchOperationParam { }
[CodeGenType("ApplyPatchToolCallItemParam")] internal partial class StubApplyPatchToolCallItemParam { }
[CodeGenType("ApplyPatchToolCallOutputItemParam")] internal partial class StubApplyPatchToolCallOutputItemParam { }
[CodeGenType("ApplyPatchUpdateFileOperationParam")] internal partial class StubApplyPatchUpdateFileOperationParam { }
[CodeGenType("AzureAISearchTool")] internal partial class StubAzureAISearchTool { }
[CodeGenType("AzureAISearchToolCall")] internal partial class StubAzureAISearchToolCall { }
[CodeGenType("AzureAISearchToolCallOutput")] internal partial class StubAzureAISearchToolCallOutput { }
[CodeGenType("AzureAISearchToolResource")] internal partial class StubAzureAISearchToolResource { }
[CodeGenType("AzureFunctionBinding")] internal partial class StubAzureFunctionBinding { }
[CodeGenType("AzureFunctionDefinition")] internal partial class StubAzureFunctionDefinition { }
[CodeGenType("AzureFunctionDefinitionFunction")] internal partial class StubAzureFunctionDefinitionFunction { }
[CodeGenType("AzureFunctionStorageQueue")] internal partial class StubAzureFunctionStorageQueue { }
[CodeGenType("AzureFunctionTool")] internal partial class StubAzureFunctionTool { }
[CodeGenType("AzureFunctionToolCall")] internal partial class StubAzureFunctionToolCall { }
[CodeGenType("AzureFunctionToolCallOutput")] internal partial class StubAzureFunctionToolCallOutput { }
[CodeGenType("BingCustomSearchConfiguration")] internal partial class StubBingCustomSearchConfiguration { }
[CodeGenType("BingCustomSearchPreviewTool")] internal partial class StubBingCustomSearchPreviewTool { }
[CodeGenType("BingCustomSearchToolCall")] internal partial class StubBingCustomSearchToolCall { }
[CodeGenType("BingCustomSearchToolCallOutput")] internal partial class StubBingCustomSearchToolCallOutput { }
[CodeGenType("BingCustomSearchToolParameters")] internal partial class StubBingCustomSearchToolParameters { }
[CodeGenType("BingGroundingSearchConfiguration")] internal partial class StubBingGroundingSearchConfiguration { }
[CodeGenType("BingGroundingSearchToolParameters")] internal partial class StubBingGroundingSearchToolParameters { }
[CodeGenType("BingGroundingTool")] internal partial class StubBingGroundingTool { }
[CodeGenType("BingGroundingToolCall")] internal partial class StubBingGroundingToolCall { }
[CodeGenType("BingGroundingToolCallOutput")] internal partial class StubBingGroundingToolCallOutput { }
[CodeGenType("BrowserAutomationPreviewTool")] internal partial class StubBrowserAutomationPreviewTool { }
[CodeGenType("BrowserAutomationToolCall")] internal partial class StubBrowserAutomationToolCall { }
[CodeGenType("BrowserAutomationToolCallOutput")] internal partial class StubBrowserAutomationToolCallOutput { }
[CodeGenType("BrowserAutomationToolConnectionParameters")] internal partial class StubBrowserAutomationToolConnectionParameters { }
[CodeGenType("BrowserAutomationToolParameters")] internal partial class StubBrowserAutomationToolParameters { }
[CodeGenType("CaptureStructuredOutputsTool")] internal partial class StubCaptureStructuredOutputsTool { }
[CodeGenType("CompactionSummaryItemParam")] internal partial class StubCompactionSummaryItemParam { }
[CodeGenType("ComputerCallOutputItemParam")] internal partial class StubComputerCallOutputItemParam { }
[CodeGenType("ContainerReferenceResource")] internal partial class StubContainerReferenceResource { }
[CodeGenType("ConversationParam")] internal partial class StubConversationParam { }
[CodeGenType("CreateResponse")] internal partial class StubCreateResponse { }
[CodeGenType("DeleteResponseResult")] internal partial class StubDeleteResponseResult { }
[CodeGenType("Error")] internal partial class StubError { }
[CodeGenType("FabricDataAgentToolCall")] internal partial class StubFabricDataAgentToolCall { }
[CodeGenType("FabricDataAgentToolCallOutput")] internal partial class StubFabricDataAgentToolCallOutput { }
[CodeGenType("FabricDataAgentToolParameters")] internal partial class StubFabricDataAgentToolParameters { }
[CodeGenType("FunctionCallOutputItemParam")] internal partial class StubFunctionCallOutputItemParam { }
[CodeGenType("FunctionShellAction")] internal partial class StubFunctionShellAction { }
[CodeGenType("FunctionShellActionParam")] internal partial class StubFunctionShellActionParam { }
[CodeGenType("FunctionShellCallEnvironment")] internal partial class StubFunctionShellCallEnvironment { }
[CodeGenType("FunctionShellCallItemParam")] internal partial class StubFunctionShellCallItemParam { }
[CodeGenType("FunctionShellCallItemParamEnvironment")] internal partial class StubFunctionShellCallItemParamEnvironment { }
[CodeGenType("FunctionShellCallItemParamEnvironmentContainerReferenceParam")] internal partial class StubFunctionShellCallItemParamEnvironmentContainerReferenceParam { }
[CodeGenType("FunctionShellCallItemParamEnvironmentLocalEnvironmentParam")] internal partial class StubFunctionShellCallItemParamEnvironmentLocalEnvironmentParam { }
[CodeGenType("FunctionShellCallItemParamEnvironmentType")] internal partial class StubFunctionShellCallItemParamEnvironmentType { }
[CodeGenType("FunctionShellCallOutputContent")] internal partial class StubFunctionShellCallOutputContent { }
[CodeGenType("FunctionShellCallOutputContentParam")] internal partial class StubFunctionShellCallOutputContentParam { }
[CodeGenType("FunctionShellCallOutputExitOutcome")] internal partial class StubFunctionShellCallOutputExitOutcome { }
[CodeGenType("FunctionShellCallOutputExitOutcomeParam")] internal partial class StubFunctionShellCallOutputExitOutcomeParam { }
[CodeGenType("FunctionShellCallOutputItemParam")] internal partial class StubFunctionShellCallOutputItemParam { }
[CodeGenType("FunctionShellCallOutputOutcome")] internal partial class StubFunctionShellCallOutputOutcome { }
[CodeGenType("FunctionShellCallOutputOutcomeParam")] internal partial class StubFunctionShellCallOutputOutcomeParam { }
[CodeGenType("FunctionShellCallOutputTimeoutOutcome")] internal partial class StubFunctionShellCallOutputTimeoutOutcome { }
[CodeGenType("FunctionShellCallOutputTimeoutOutcomeParam")] internal partial class StubFunctionShellCallOutputTimeoutOutcomeParam { }
[CodeGenType("Item")] internal partial class StubItem { }
[CodeGenType("ItemCodeInterpreterToolCall")] internal partial class StubItemCodeInterpreterToolCall { }
[CodeGenType("ItemComputerToolCall")] internal partial class StubItemComputerToolCall { }
[CodeGenType("ItemCustomToolCall")] internal partial class StubItemCustomToolCall { }
[CodeGenType("ItemCustomToolCallOutput")] internal partial class StubItemCustomToolCallOutput { }
[CodeGenType("ItemFileSearchToolCall")] internal partial class StubItemFileSearchToolCall { }
[CodeGenType("ItemFunctionToolCall")] internal partial class StubItemFunctionToolCall { }
[CodeGenType("ItemImageGenToolCall")] internal partial class StubItemImageGenToolCall { }
[CodeGenType("ItemLocalShellToolCall")] internal partial class StubItemLocalShellToolCall { }
[CodeGenType("ItemLocalShellToolCallOutput")] internal partial class StubItemLocalShellToolCallOutput { }
[CodeGenType("ItemLocalShellToolCallOutputStatus")] internal partial class StubItemLocalShellToolCallOutputStatus { }
[CodeGenType("ItemLocalShellToolCallStatus")] internal partial class StubItemLocalShellToolCallStatus { }
[CodeGenType("ItemMcpApprovalRequest")] internal partial class StubItemMcpApprovalRequest { }
[CodeGenType("ItemMcpListTools")] internal partial class StubItemMcpListTools { }
[CodeGenType("ItemMcpToolCall")] internal partial class StubItemMcpToolCall { }
[CodeGenType("ItemMessage")] internal partial class StubItemMessage { }
[CodeGenType("ItemOutputMessage")] internal partial class StubItemOutputMessage { }
[CodeGenType("ItemOutputMessageStatus")] internal partial class StubItemOutputMessageStatus { }
[CodeGenType("ItemReasoningItem")] internal partial class StubItemReasoningItem { }
[CodeGenType("ItemReferenceParam")] internal partial class StubItemReferenceParam { }
[CodeGenType("ItemWebSearchToolCall")] internal partial class StubItemWebSearchToolCall { }
[CodeGenType("LocalEnvironmentResource")] internal partial class StubLocalEnvironmentResource { }
[CodeGenType("LocalShellCallOutputStatusEnum")] internal partial class StubLocalShellCallOutputStatusEnum { }
[CodeGenType("LocalShellCallStatus")] internal partial class StubLocalShellCallStatus { }
[CodeGenType("LocalShellExecAction")] internal partial class StubLocalShellExecAction { }
[CodeGenType("LocalShellToolParam")] internal partial class StubLocalShellToolParam { }
[CodeGenType("MCPApprovalResponse")] internal partial class StubMCPApprovalResponse { }
[CodeGenType("MemorySearchPreviewTool")] internal partial class StubMemorySearchPreviewTool { }
[CodeGenType("MemorySearchToolCallItemParam")] internal partial class StubMemorySearchToolCallItemParam { }
[CodeGenType("MemorySearchToolCallItemResource")] internal partial class StubMemorySearchToolCallItemResource { }
[CodeGenType("MemorySearchToolCallItemResourceStatus")] internal partial class StubMemorySearchToolCallItemResourceStatus { }
[CodeGenType("MicrosoftFabricPreviewTool")] internal partial class StubMicrosoftFabricPreviewTool { }
[CodeGenType("OAuthConsentRequestOutputItem")] internal partial class StubOAuthConsentRequestOutputItem { }
[CodeGenType("OpenApiTool")] internal partial class StubOpenApiTool { }
[CodeGenType("OpenApiToolCall")] internal partial class StubOpenApiToolCall { }
[CodeGenType("OpenApiToolCallOutput")] internal partial class StubOpenApiToolCallOutput { }
[CodeGenType("OutputItem")] internal partial class StubOutputItem { }
[CodeGenType("OutputItemApplyPatchToolCall")] internal partial class StubOutputItemApplyPatchToolCall { }
[CodeGenType("OutputItemApplyPatchToolCallOutput")] internal partial class StubOutputItemApplyPatchToolCallOutput { }
[CodeGenType("OutputItemCodeInterpreterToolCall")] internal partial class StubOutputItemCodeInterpreterToolCall { }
[CodeGenType("OutputItemCompactionBody")] internal partial class StubOutputItemCompactionBody { }
[CodeGenType("OutputItemComputerToolCall")] internal partial class StubOutputItemComputerToolCall { }
[CodeGenType("OutputItemComputerToolCallOutput")] internal partial class StubOutputItemComputerToolCallOutput { }
[CodeGenType("OutputItemComputerToolCallOutputStatus")] internal partial class StubOutputItemComputerToolCallOutputStatus { }
[CodeGenType("OutputItemCustomToolCall")] internal partial class StubOutputItemCustomToolCall { }
[CodeGenType("OutputItemCustomToolCallOutput")] internal partial class StubOutputItemCustomToolCallOutput { }
[CodeGenType("OutputItemFileSearchToolCall")] internal partial class StubOutputItemFileSearchToolCall { }
[CodeGenType("OutputItemFunctionShellCall")] internal partial class StubOutputItemFunctionShellCall { }
[CodeGenType("OutputItemFunctionShellCallOutput")] internal partial class StubOutputItemFunctionShellCallOutput { }
[CodeGenType("OutputItemFunctionToolCall")] internal partial class StubOutputItemFunctionToolCall { }
[CodeGenType("OutputItemFunctionToolCallOutput")] internal partial class StubOutputItemFunctionToolCallOutput { }
[CodeGenType("OutputItemFunctionToolCallOutputStatus")] internal partial class StubOutputItemFunctionToolCallOutputStatus { }
[CodeGenType("OutputItemImageGenToolCall")] internal partial class StubOutputItemImageGenToolCall { }
[CodeGenType("OutputItemLocalShellToolCall")] internal partial class StubOutputItemLocalShellToolCall { }
[CodeGenType("OutputItemLocalShellToolCallOutput")] internal partial class StubOutputItemLocalShellToolCallOutput { }
[CodeGenType("OutputItemMcpApprovalRequest")] internal partial class StubOutputItemMcpApprovalRequest { }
[CodeGenType("OutputItemMcpApprovalResponseResource")] internal partial class StubOutputItemMcpApprovalResponseResource { }
[CodeGenType("OutputItemMcpListTools")] internal partial class StubOutputItemMcpListTools { }
[CodeGenType("OutputItemMcpToolCall")] internal partial class StubOutputItemMcpToolCall { }
[CodeGenType("OutputItemMessage")] internal partial class StubOutputItemMessage { }
[CodeGenType("OutputItemOutputMessage")] internal partial class StubOutputItemOutputMessage { }
[CodeGenType("OutputItemReasoningItem")] internal partial class StubOutputItemReasoningItem { }
[CodeGenType("OutputItemToolSearchCall")] internal partial class StubOutputItemToolSearchCall { }
[CodeGenType("OutputItemToolSearchOutput")] internal partial class StubOutputItemToolSearchOutput { }
[CodeGenType("OutputItemWebSearchToolCall")] internal partial class StubOutputItemWebSearchToolCall { }
[CodeGenType("OutputMessageContent")] internal partial class StubOutputMessageContent { }
[CodeGenType("OutputMessageContentOutputTextContent")] internal partial class StubOutputMessageContentOutputTextContent { }
[CodeGenType("OutputMessageContentRefusalContent")] internal partial class StubOutputMessageContentRefusalContent { }
[CodeGenType("OutputMessageContentType")] internal partial class StubOutputMessageContentType { }
[CodeGenType("ResponseAudioDeltaEvent")] internal partial class StubResponseAudioDeltaEvent { }
[CodeGenType("ResponseAudioDoneEvent")] internal partial class StubResponseAudioDoneEvent { }
[CodeGenType("ResponseAudioTranscriptDeltaEvent")] internal partial class StubResponseAudioTranscriptDeltaEvent { }
[CodeGenType("ResponseAudioTranscriptDoneEvent")] internal partial class StubResponseAudioTranscriptDoneEvent { }
[CodeGenType("ResponseCodeInterpreterCallCodeDeltaEvent")] internal partial class StubResponseCodeInterpreterCallCodeDeltaEvent { }
[CodeGenType("ResponseCodeInterpreterCallCodeDoneEvent")] internal partial class StubResponseCodeInterpreterCallCodeDoneEvent { }
[CodeGenType("ResponseCodeInterpreterCallCompletedEvent")] internal partial class StubResponseCodeInterpreterCallCompletedEvent { }
[CodeGenType("ResponseCodeInterpreterCallInProgressEvent")] internal partial class StubResponseCodeInterpreterCallInProgressEvent { }
[CodeGenType("ResponseCodeInterpreterCallInterpretingEvent")] internal partial class StubResponseCodeInterpreterCallInterpretingEvent { }
[CodeGenType("ResponseCompletedEvent")] internal partial class StubResponseCompletedEvent { }
[CodeGenType("ResponseContentPartAddedEvent")] internal partial class StubResponseContentPartAddedEvent { }
[CodeGenType("ResponseContentPartDoneEvent")] internal partial class StubResponseContentPartDoneEvent { }
[CodeGenType("ResponseCreatedEvent")] internal partial class StubResponseCreatedEvent { }
[CodeGenType("ResponseCustomToolCallInputDeltaEvent")] internal partial class StubResponseCustomToolCallInputDeltaEvent { }
[CodeGenType("ResponseCustomToolCallInputDoneEvent")] internal partial class StubResponseCustomToolCallInputDoneEvent { }
[CodeGenType("ResponseErrorCode")] internal partial class StubResponseErrorCode { }
[CodeGenType("ResponseErrorEvent")] internal partial class StubResponseErrorEvent { }
[CodeGenType("ResponseErrorInfo")] internal partial class StubResponseErrorInfo { }
[CodeGenType("ResponseFailedEvent")] internal partial class StubResponseFailedEvent { }
[CodeGenType("ResponseFileSearchCallCompletedEvent")] internal partial class StubResponseFileSearchCallCompletedEvent { }
[CodeGenType("ResponseFileSearchCallInProgressEvent")] internal partial class StubResponseFileSearchCallInProgressEvent { }
[CodeGenType("ResponseFileSearchCallSearchingEvent")] internal partial class StubResponseFileSearchCallSearchingEvent { }
[CodeGenType("ResponseFunctionCallArgumentsDeltaEvent")] internal partial class StubResponseFunctionCallArgumentsDeltaEvent { }
[CodeGenType("ResponseFunctionCallArgumentsDoneEvent")] internal partial class StubResponseFunctionCallArgumentsDoneEvent { }
[CodeGenType("ResponseImageGenCallCompletedEvent")] internal partial class StubResponseImageGenCallCompletedEvent { }
[CodeGenType("ResponseImageGenCallGeneratingEvent")] internal partial class StubResponseImageGenCallGeneratingEvent { }
[CodeGenType("ResponseImageGenCallInProgressEvent")] internal partial class StubResponseImageGenCallInProgressEvent { }
[CodeGenType("ResponseImageGenCallPartialImageEvent")] internal partial class StubResponseImageGenCallPartialImageEvent { }
[CodeGenType("ResponseInProgressEvent")] internal partial class StubResponseInProgressEvent { }
[CodeGenType("ResponseIncompleteDetails")] internal partial class StubResponseIncompleteDetails { }
[CodeGenType("ResponseIncompleteDetailsReason")] internal partial class StubResponseIncompleteDetailsReason { }
[CodeGenType("ResponseIncompleteEvent")] internal partial class StubResponseIncompleteEvent { }
[CodeGenType("ResponseMCPCallArgumentsDeltaEvent")] internal partial class StubResponseMCPCallArgumentsDeltaEvent { }
[CodeGenType("ResponseMCPCallArgumentsDoneEvent")] internal partial class StubResponseMCPCallArgumentsDoneEvent { }
[CodeGenType("ResponseMCPCallCompletedEvent")] internal partial class StubResponseMCPCallCompletedEvent { }
[CodeGenType("ResponseMCPCallFailedEvent")] internal partial class StubResponseMCPCallFailedEvent { }
[CodeGenType("ResponseMCPCallInProgressEvent")] internal partial class StubResponseMCPCallInProgressEvent { }
[CodeGenType("ResponseMCPListToolsCompletedEvent")] internal partial class StubResponseMCPListToolsCompletedEvent { }
[CodeGenType("ResponseMCPListToolsFailedEvent")] internal partial class StubResponseMCPListToolsFailedEvent { }
[CodeGenType("ResponseMCPListToolsInProgressEvent")] internal partial class StubResponseMCPListToolsInProgressEvent { }
[CodeGenType("ResponseObject")] internal partial class StubResponseObject { }
[CodeGenType("ResponseOutputItemAddedEvent")] internal partial class StubResponseOutputItemAddedEvent { }
[CodeGenType("ResponseOutputItemDoneEvent")] internal partial class StubResponseOutputItemDoneEvent { }
[CodeGenType("ResponseOutputTextAnnotationAddedEvent")] internal partial class StubResponseOutputTextAnnotationAddedEvent { }
[CodeGenType("ResponseQueuedEvent")] internal partial class StubResponseQueuedEvent { }
[CodeGenType("ResponseReasoningSummaryPartAddedEvent")] internal partial class StubResponseReasoningSummaryPartAddedEvent { }
[CodeGenType("ResponseReasoningSummaryPartDoneEvent")] internal partial class StubResponseReasoningSummaryPartDoneEvent { }
[CodeGenType("ResponseReasoningSummaryTextDeltaEvent")] internal partial class StubResponseReasoningSummaryTextDeltaEvent { }
[CodeGenType("ResponseReasoningSummaryTextDoneEvent")] internal partial class StubResponseReasoningSummaryTextDoneEvent { }
[CodeGenType("ResponseReasoningTextDeltaEvent")] internal partial class StubResponseReasoningTextDeltaEvent { }
[CodeGenType("ResponseReasoningTextDoneEvent")] internal partial class StubResponseReasoningTextDoneEvent { }
[CodeGenType("ResponseRefusalDeltaEvent")] internal partial class StubResponseRefusalDeltaEvent { }
[CodeGenType("ResponseRefusalDoneEvent")] internal partial class StubResponseRefusalDoneEvent { }
[CodeGenType("ResponseStatus")] internal partial class StubResponseStatus { }
[CodeGenType("ResponseStreamEvent")] internal partial class StubResponseStreamEvent { }
[CodeGenType("ResponseStreamEventType")] internal partial class StubResponseStreamEventType { }
[CodeGenType("ResponseTextDeltaEvent")] internal partial class StubResponseTextDeltaEvent { }
[CodeGenType("ResponseTextDoneEvent")] internal partial class StubResponseTextDoneEvent { }
[CodeGenType("ResponseUsage")] internal partial class StubResponseUsage { }
[CodeGenType("ResponseUsageInputTokensDetails")] internal partial class StubResponseUsageInputTokensDetails { }
[CodeGenType("ResponseUsageOutputTokensDetails")] internal partial class StubResponseUsageOutputTokensDetails { }
[CodeGenType("ResponseWebSearchCallCompletedEvent")] internal partial class StubResponseWebSearchCallCompletedEvent { }
[CodeGenType("ResponseWebSearchCallInProgressEvent")] internal partial class StubResponseWebSearchCallInProgressEvent { }
[CodeGenType("ResponseWebSearchCallSearchingEvent")] internal partial class StubResponseWebSearchCallSearchingEvent { }
[CodeGenType("SharepointGroundingToolCall")] internal partial class StubSharepointGroundingToolCall { }
[CodeGenType("SharepointGroundingToolCallOutput")] internal partial class StubSharepointGroundingToolCallOutput { }
[CodeGenType("SharepointGroundingToolParameters")] internal partial class StubSharepointGroundingToolParameters { }
[CodeGenType("SharepointPreviewTool")] internal partial class StubSharepointPreviewTool { }
[CodeGenType("StructuredOutputsOutputItem")] internal partial class StubStructuredOutputsOutputItem { }
[CodeGenType("ToolChoiceOptions")] internal partial class StubToolChoiceOptions { }
[CodeGenType("ToolSearchCallItemParam")] internal partial class StubToolSearchCallItemParam { }
[CodeGenType("ToolSearchOutputItemParam")] internal partial class StubToolSearchOutputItemParam { }
[CodeGenType("UnknownApplyPatchOperationParam")] internal partial class StubUnknownApplyPatchOperationParam { }
[CodeGenType("UnknownFunctionShellCallEnvironment")] internal partial class StubUnknownFunctionShellCallEnvironment { }
[CodeGenType("UnknownFunctionShellCallItemParamEnvironment")] internal partial class StubUnknownFunctionShellCallItemParamEnvironment { }
[CodeGenType("UnknownFunctionShellCallOutputOutcome")] internal partial class StubUnknownFunctionShellCallOutputOutcome { }
[CodeGenType("UnknownFunctionShellCallOutputOutcomeParam")] internal partial class StubUnknownFunctionShellCallOutputOutcomeParam { }
[CodeGenType("UnknownItem")] internal partial class StubUnknownItem { }
[CodeGenType("UnknownOutputItem")] internal partial class StubUnknownOutputItem { }
[CodeGenType("UnknownOutputMessageContent")] internal partial class StubUnknownOutputMessageContent { }
[CodeGenType("UnknownResponseStreamEvent")] internal partial class StubUnknownResponseStreamEvent { }
[CodeGenType("WorkIQPreviewTool")] internal partial class StubWorkIQPreviewTool { }
[CodeGenType("WorkIQPreviewToolParameters")] internal partial class StubWorkIQPreviewToolParameters { }
[CodeGenType("WorkflowActionOutputItem")] internal partial class StubWorkflowActionOutputItem { }
[CodeGenType("WorkflowActionOutputItemStatus")] internal partial class StubWorkflowActionOutputItemStatus { }
