// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Usage", "AZC0001:Use one of the following pre-approved namespace groups (https://azure.github.io/azure-sdk/registered_namespaces.html): Azure.AI, Azure.Analytics, Azure.Communication, Azure.Data, Azure.DigitalTwins, Azure.Iot, Azure.Learn, Azure.Media, Azure.Management, Azure.Messaging, Azure.Search, Azure.Security, Azure.Storage, Azure.Template, Azure.Identity, Microsoft.Extensions.Azure", Justification = "<Pending>", Scope = "namespace", Target = "~N:Azure.IoT.TimeSeriesInsights")]
[assembly: SuppressMessage("Usage", "AZC0001:Use one of the following pre-approved namespace groups (https://azure.github.io/azure-sdk/registered_namespaces.html): Azure.AI, Azure.Analytics, Azure.Communication, Azure.Data, Azure.DigitalTwins, Azure.Iot, Azure.Learn, Azure.Media, Azure.Management, Azure.Messaging, Azure.Search, Azure.Security, Azure.Storage, Azure.Template, Azure.Identity, Microsoft.Extensions.Azure", Justification = "<Pending>", Scope = "namespace", Target = "~N:Azure.IoT.TimeSeriesInsights.Models")]
[assembly: SuppressMessage("Usage", "AZC0015:Unexpected client method return type.", Justification = "<Pending>", Scope = "member", Target = "~M:Azure.IoT.TimeSeriesInsights.QueryClient.GetEventsAsync(Azure.IoT.TimeSeriesInsights.TimeSeriesId,System.DateTimeOffset,System.DateTimeOffset,Azure.IoT.TimeSeriesInsights.QueryEventsRequestOptions,System.Threading.CancellationToken)~Azure.IoT.TimeSeriesInsights.QueryAsyncResults")]
[assembly: SuppressMessage("Usage", "AZC0015:Unexpected client method return type.", Justification = "<Pending>", Scope = "member", Target = "~M:Azure.IoT.TimeSeriesInsights.QueryClient.GetEvents(Azure.IoT.TimeSeriesInsights.TimeSeriesId,System.DateTimeOffset,System.DateTimeOffset,Azure.IoT.TimeSeriesInsights.QueryEventsRequestOptions,System.Threading.CancellationToken)~Azure.IoT.TimeSeriesInsights.QueryResults")]
[assembly: SuppressMessage("Usage", "AZC0015:Unexpected client method return type.", Justification = "<Pending>", Scope = "member", Target = "~M:Azure.IoT.TimeSeriesInsights.QueryClient.GetEventsAsync(Azure.IoT.TimeSeriesInsights.TimeSeriesId,System.DateTimeOffset,System.DateTimeOffset,Azure.IoT.TimeSeriesInsights.QueryEventsRequestOptions,System.Threading.CancellationToken)~Azure.IoT.TimeSeriesInsights.QueryResults")]
[assembly: SuppressMessage("Usage", "AZC0015:Unexpected client method return type.", Justification = "<Pending>", Scope = "member", Target = "~M:Azure.IoT.TimeSeriesInsights.QueryClient.GetEvents(Azure.IoT.TimeSeriesInsights.TimeSeriesId,System.TimeSpan,System.Nullable{System.DateTimeOffset},Azure.IoT.TimeSeriesInsights.QueryEventsRequestOptions,System.Threading.CancellationToken)~Azure.IoT.TimeSeriesInsights.QueryResults")]
[assembly: SuppressMessage("Usage", "AZC0015:Unexpected client method return type.", Justification = "<Pending>", Scope = "member", Target = "~M:Azure.IoT.TimeSeriesInsights.QueryClient.GetEventsAsync(Azure.IoT.TimeSeriesInsights.TimeSeriesId,System.TimeSpan,System.Nullable{System.DateTimeOffset},Azure.IoT.TimeSeriesInsights.QueryEventsRequestOptions,System.Threading.CancellationToken)~Azure.IoT.TimeSeriesInsights.QueryResults")]
[assembly: SuppressMessage("Usage", "AZC0015:Unexpected client method return type.", Justification = "<Pending>", Scope = "member", Target = "~M:Azure.IoT.TimeSeriesInsights.QueryClient.GetSeries(Azure.IoT.TimeSeriesInsights.TimeSeriesId,System.DateTimeOffset,System.DateTimeOffset,Azure.IoT.TimeSeriesInsights.QuerySeriesRequestOptions,System.Threading.CancellationToken)~Azure.IoT.TimeSeriesInsights.QueryResults")]
[assembly: SuppressMessage("Usage", "AZC0015:Unexpected client method return type.", Justification = "<Pending>", Scope = "member", Target = "~M:Azure.IoT.TimeSeriesInsights.QueryClient.GetSeries(Azure.IoT.TimeSeriesInsights.TimeSeriesId,System.TimeSpan,System.Nullable{System.DateTimeOffset},Azure.IoT.TimeSeriesInsights.QuerySeriesRequestOptions,System.Threading.CancellationToken)~Azure.IoT.TimeSeriesInsights.QueryResults")]
[assembly: SuppressMessage("Usage", "AZC0015:Unexpected client method return type.", Justification = "<Pending>", Scope = "member", Target = "~M:Azure.IoT.TimeSeriesInsights.QueryClient.GetSeriesAsync(Azure.IoT.TimeSeriesInsights.TimeSeriesId,System.DateTimeOffset,System.DateTimeOffset,Azure.IoT.TimeSeriesInsights.QuerySeriesRequestOptions,System.Threading.CancellationToken)~Azure.IoT.TimeSeriesInsights.QueryResults")]
[assembly: SuppressMessage("Usage", "AZC0015:Unexpected client method return type.", Justification = "<Pending>", Scope = "member", Target = "~M:Azure.IoT.TimeSeriesInsights.QueryClient.GetSeriesAsync(Azure.IoT.TimeSeriesInsights.TimeSeriesId,System.TimeSpan,System.Nullable{System.DateTimeOffset},Azure.IoT.TimeSeriesInsights.QuerySeriesRequestOptions,System.Threading.CancellationToken)~Azure.IoT.TimeSeriesInsights.QueryResults")]
[assembly: SuppressMessage("Usage", "AZC0015:Unexpected client method return type.", Justification = "<Pending>", Scope = "member", Target = "~M:Azure.IoT.TimeSeriesInsights.QueryClient.QueryAggregateSeries(Azure.IoT.TimeSeriesInsights.TimeSeriesId,System.DateTimeOffset,System.DateTimeOffset,System.TimeSpan,Azure.IoT.TimeSeriesInsights.QueryAggregateSeriesRequestOptions,System.Threading.CancellationToken)~Azure.IoT.TimeSeriesInsights.QueryResults")]
[assembly: SuppressMessage("Usage", "AZC0015:Unexpected client method return type.", Justification = "<Pending>", Scope = "member", Target = "~M:Azure.IoT.TimeSeriesInsights.QueryClient.QueryAggregateSeries(Azure.IoT.TimeSeriesInsights.TimeSeriesId,System.TimeSpan,System.TimeSpan,System.Nullable{System.DateTimeOffset},Azure.IoT.TimeSeriesInsights.QueryAggregateSeriesRequestOptions,System.Threading.CancellationToken)~Azure.IoT.TimeSeriesInsights.QueryResults")]
[assembly: SuppressMessage("Usage", "AZC0015:Unexpected client method return type.", Justification = "<Pending>", Scope = "member", Target = "~M:Azure.IoT.TimeSeriesInsights.QueryClient.QueryAggregateSeriesAsync(Azure.IoT.TimeSeriesInsights.TimeSeriesId,System.DateTimeOffset,System.DateTimeOffset,System.TimeSpan,Azure.IoT.TimeSeriesInsights.QueryAggregateSeriesRequestOptions,System.Threading.CancellationToken)~Azure.IoT.TimeSeriesInsights.QueryResults")]
[assembly: SuppressMessage("Usage", "AZC0015:Unexpected client method return type.", Justification = "<Pending>", Scope = "member", Target = "~M:Azure.IoT.TimeSeriesInsights.QueryClient.QueryAggregateSeriesAsync(Azure.IoT.TimeSeriesInsights.TimeSeriesId,System.TimeSpan,System.TimeSpan,System.Nullable{System.DateTimeOffset},Azure.IoT.TimeSeriesInsights.QueryAggregateSeriesRequestOptions,System.Threading.CancellationToken)~Azure.IoT.TimeSeriesInsights.QueryResults")]
