// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// </auto-generated>

namespace Microsoft.Azure.Management.StorSimple.Fluent.Models
{
    using Microsoft.Azure;
    using Microsoft.Azure.Management;
    using Microsoft.Azure.Management.StorSimple;
    using Microsoft.Azure.Management.StorSimple.Fluent;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The OData filters to be used for backups.
    /// </summary>
    public partial class BackupFilterInner
    {
        /// <summary>
        /// Initializes a new instance of the BackupFilterInner class.
        /// </summary>
        public BackupFilterInner()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BackupFilterInner class.
        /// </summary>
        /// <param name="backupPolicyId">Specifies the backupPolicyId of the
        /// backups to be filtered. Only 'Equality' operator is supported for
        /// this property.</param>
        /// <param name="volumeId">Specifies the volumeId of the backups to be
        /// filtered. Only 'Equality' operator is supported for this
        /// property.</param>
        /// <param name="createdTime">Specifies the creation time of the
        /// backups to be filtered. Only 'Greater Than or Equal To' and 'Lesser
        /// Than or Equal To' operators are supported for this
        /// property.</param>
        public BackupFilterInner(string backupPolicyId = default(string), string volumeId = default(string), System.DateTime? createdTime = default(System.DateTime?))
        {
            BackupPolicyId = backupPolicyId;
            VolumeId = volumeId;
            CreatedTime = createdTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets specifies the backupPolicyId of the backups to be
        /// filtered. Only 'Equality' operator is supported for this property.
        /// </summary>
        [JsonProperty(PropertyName = "backupPolicyId")]
        public string BackupPolicyId { get; set; }

        /// <summary>
        /// Gets or sets specifies the volumeId of the backups to be filtered.
        /// Only 'Equality' operator is supported for this property.
        /// </summary>
        [JsonProperty(PropertyName = "volumeId")]
        public string VolumeId { get; set; }

        /// <summary>
        /// Gets or sets specifies the creation time of the backups to be
        /// filtered. Only 'Greater Than or Equal To' and 'Lesser Than or Equal
        /// To' operators are supported for this property.
        /// </summary>
        [JsonProperty(PropertyName = "createdTime")]
        public System.DateTime? CreatedTime { get; set; }

    }
}
