// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using System.Runtime.CompilerServices;
using Azure.Core;
using Azure.ResourceManager.ContainerRegistry;
using Azure.ResourceManager.ContainerRegistry.Models;

[assembly: TypeForwardedTo(typeof(ContainerRegistryAgentPoolResource))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryAgentPoolData))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryAgentPoolCollection))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryRunResource))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryRunData))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryRunCollection))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryTaskResource))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryTaskData))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryTaskCollection))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryTaskRunResource))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryTaskRunData))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryTaskRunCollection))]

// suppress this type because both this project, and its dependency Azure.ResourceManager.ContainerRegistry.Tasks define it
// and they are the same.
[assembly: CodeGenSuppressType("ContainerRegistryProvisioningState")]

// Models
[assembly: TypeForwardedTo(typeof(ContainerRegistryAgentPoolListResult))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryAgentPoolPatch))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryAgentPoolQueueStatus))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryAgentProperties))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryBaseImageDependency))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryBaseImageDependencyType))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryBaseImageTrigger))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryBaseImageTriggerType))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryCredentials))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryDockerBuildStep))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryEncodedTaskStep))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryFileTaskStep))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryImageDescriptor))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryImageUpdateTrigger))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryOverrideTaskStepProperties))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryPlatformProperties))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryProvisioningState))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryRunGetLogResult))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryRunListResult))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryRunPatch))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryRunStatus))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryRunType))]
[assembly: TypeForwardedTo(typeof(ContainerRegistrySecretObject))]
[assembly: TypeForwardedTo(typeof(ContainerRegistrySecretObjectType))]
[assembly: TypeForwardedTo(typeof(ContainerRegistrySourceTrigger))]
[assembly: TypeForwardedTo(typeof(ContainerRegistrySourceTriggerDescriptor))]
[assembly: TypeForwardedTo(typeof(ContainerRegistrySourceTriggerEvent))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryTaskListResult))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryTaskPatch))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryTaskRunListResult))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryTaskRunPatch))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryTaskStatus))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryTaskStepProperties))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryTaskStepType))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryTimerTrigger))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryTimerTriggerDescriptor))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryTriggerProperties))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryTriggerStatus))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryUpdateTriggerPayloadType))]

[assembly: TypeForwardedTo(typeof(ContainerRegistryBaseImageTriggerUpdateContent))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryCpuVariant))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryDockerBuildContent))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryDockerBuildStepUpdateContent))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryEncodedTaskRunContent))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryEncodedTaskStepUpdateContent))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryFileTaskRunContent))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryFileTaskStepUpdateContent))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryOS))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryOSArchitecture))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryPlatformUpdateContent))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryRunArgument))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryRunContent))]
[assembly: TypeForwardedTo(typeof(ContainerRegistrySourceTriggerUpdateContent))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryTaskOverridableValue))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryTaskRunContent))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryTaskStepUpdateContent))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryTimerTriggerUpdateContent))]
[assembly: TypeForwardedTo(typeof(ContainerRegistryTriggerUpdateContent))]
[assembly: TypeForwardedTo(typeof(CustomRegistryCredentials))]
[assembly: TypeForwardedTo(typeof(SourceCodeRepoAuthInfo))]
[assembly: TypeForwardedTo(typeof(SourceCodeRepoAuthInfoUpdateContent))]
[assembly: TypeForwardedTo(typeof(SourceCodeRepoAuthTokenType))]
[assembly: TypeForwardedTo(typeof(SourceCodeRepoProperties))]
[assembly: TypeForwardedTo(typeof(SourceCodeRepoUpdateContent))]
[assembly: TypeForwardedTo(typeof(SourceControlType))]
[assembly: TypeForwardedTo(typeof(SourceRegistryCredentials))]
[assembly: TypeForwardedTo(typeof(SourceRegistryLoginMode))]
[assembly: TypeForwardedTo(typeof(SourceUploadDefinition))]
