namespace Microsoft.Azure.Management.V2.Resource.Core
{
    public enum Region
    {
        [EnumName("westus")]
        US_WEST,
        [EnumName("centralus")]
        US_CENTRAL,
        [EnumName("eastus")]
        US_EAST,
        [EnumName("eastus2")]
        US_EAST2,
        [EnumName("northcentralus")]
        US_NORTH_CENTRAL,
        [EnumName("southcentralus")]
        US_SOUTH_CENTRAL,
        [EnumName("northeurope")]
        EUROPE_NORTH,
        [EnumName("westeurope")]
        EUROPE_WEST,
        [EnumName("eastasia")]
        ASIA_EAST,
        [EnumName("southeastasia")]
        ASIA_SOUTHEAST,
        [EnumName("japaneast")]
        JAPAN_EAST,
        [EnumName("japanwest")]
        JAPAN_WEST,
        [EnumName("brazilsouth")]
        BRAZIL_SOUTH,
        [EnumName("australiaeast")]
        AUSTRALIA_EAST,
        [EnumName("australiasoutheast")]
        AUSTRALIA_SOUTHEAST,
        [EnumName("centralindia")]
        INDIA_CENTRAL,
        [EnumName("southindia")]
        INDIA_SOUTH,
        [EnumName("westindia")]
        INDIA_WEST
    }
}