// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Datafactory.Models
{

    /// <summary>
    /// Defines values for SalesforceSourceReadBehavior.
    /// </summary>
    public static class SalesforceSourceReadBehavior
    {
        public const string Query = "Query";
        public const string QueryAll = "QueryAll";
    }
}
