<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>This is the Azure.ResourceManager.Education client library for developing .NET applications with rich experience.</Description>
    <AssemblyTitle>SDK Code Generation Azure.ResourceManager.Education</AssemblyTitle>
    <Version>1.0.0-beta.1</Version>
    <PackageTags>Azure.ResourceManager.Education</PackageTags>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
</Project>
