// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using System.Diagnostics.CodeAnalysis;

// AZC0015: We return AsyncCollectionResult<T> and CollectionResult<T> instead of Pageable<T>.
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult<AgentRecord>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.GetAgent(System.String,System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult<AgentRecord>>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.GetAgentAsync(System.String,System.Threading.CancellationToken)")]

[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult<AgentVersion>>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.CreateAgentVersionAsync(System.String,Azure.AI.Projects.Agents.ProjectsAgentVersionCreationOptions,System.String,System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult<AgentVersion>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.CreateAgentVersion(System.String,Azure.AI.Projects.Agents.ProjectsAgentVersionCreationOptions,System.String,System.Threading.CancellationToken)")]

[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult<AgentVersion>>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.CreateAgentVersionFromManifestAsync(System.String,System.String,Azure.AI.Projects.Agents.AgentManifestOptions,System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult<AgentVersion>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.CreateAgentVersionFromManifest(System.String,System.String,Azure.AI.Projects.Agents.AgentManifestOptions,System.Threading.CancellationToken)")]

[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns AsyncCollectionResult<AgentRecord>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.GetAgentsAsync(System.Nullable{Azure.AI.Projects.Agents.ProjectsAgentKind},System.Nullable{System.Int32},System.Nullable{Azure.AI.Projects.Agents.AgentListOrder},System.String,System.String,System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns CollectionResult<AgentRecord>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.GetAgents(System.Nullable{Azure.AI.Projects.Agents.ProjectsAgentKind},System.Nullable{System.Int32},System.Nullable{Azure.AI.Projects.Agents.AgentListOrder},System.String,System.String,System.Threading.CancellationToken)")]

[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns AsyncCollectionResult<AgentVersion>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.GetAgentVersionsAsync(System.String,System.Nullable{System.Int32},System.Nullable{Azure.AI.Projects.Agents.AgentListOrder},System.String,System.String,System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns CollectionResult<AgentVersion>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.GetAgentVersions(System.String,System.Nullable{System.Int32},System.Nullable{Azure.AI.Projects.Agents.AgentListOrder},System.String,System.String,System.Threading.CancellationToken)")]

[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.DeleteAgentVersionAsync(System.String,System.String,System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.DeleteAgentVersion(System.String,System.String,System.Threading.CancellationToken)")]

[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.DeleteAgentAsync(System.String,System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.DeleteAgent(System.String,System.Threading.CancellationToken)")]

// AgentsClient.RestClient
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.CreateAgentAsync(System.ClientModel.BinaryContent,System.String,System.ClientModel.Primitives.RequestOptions)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.CreateAgent(System.ClientModel.BinaryContent,System.String,System.ClientModel.Primitives.RequestOptions)")]

[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.CreateAgentVersionAsync(System.String,System.ClientModel.BinaryContent,System.String,System.ClientModel.Primitives.RequestOptions)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.CreateAgentVersion(System.String,System.ClientModel.BinaryContent,System.String,System.ClientModel.Primitives.RequestOptions)")]

[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.CreateAgentVersionFromManifestAsync(System.String,System.ClientModel.BinaryContent,System.ClientModel.Primitives.RequestOptions)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.CreateAgentVersionFromManifest(System.String,System.ClientModel.BinaryContent,System.ClientModel.Primitives.RequestOptions)")]

[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.CreateAgentFromManifestAsync(System.ClientModel.BinaryContent,System.ClientModel.Primitives.RequestOptions)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.CreateAgentFromManifest(System.ClientModel.BinaryContent,System.ClientModel.Primitives.RequestOptions)")]

[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.GetAgentVersionAsync(System.String,System.String,System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.GetAgentVersion(System.String,System.String,System.Threading.CancellationToken)")]

[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.GetAgentVersionAsync(System.String,System.String,System.ClientModel.Primitives.RequestOptions)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.GetAgentVersion(System.String,System.String,System.ClientModel.Primitives.RequestOptions)")]

[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.GetAgentAsync(System.String,System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.GetAgent(System.String,System.Threading.CancellationToken)")]

[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.GetAgentAsync(System.String,System.ClientModel.Primitives.RequestOptions)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.GetAgent(System.String,System.ClientModel.Primitives.RequestOptions)")]

[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.UpdateAgentAsync(System.String,System.ClientModel.BinaryContent,System.String,System.ClientModel.Primitives.RequestOptions)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.UpdateAgent(System.String,System.ClientModel.BinaryContent,System.String,System.ClientModel.Primitives.RequestOptions)")]

[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.UpdateAgentFromManifestAsync(System.String,System.ClientModel.BinaryContent,System.ClientModel.Primitives.RequestOptions)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.UpdateAgentFromManifest(System.String,System.ClientModel.BinaryContent,System.ClientModel.Primitives.RequestOptions)")]

[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.DeleteAgentAsync(System.String,System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.DeleteAgent(System.String,System.Threading.CancellationToken)")]

[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.DeleteAgentVersionAsync(System.String,System.String,System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.DeleteAgentVersion(System.String,System.String,System.Threading.CancellationToken)")]

[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.DeleteAgentAsync(System.String,System.ClientModel.Primitives.RequestOptions)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.DeleteAgent(System.String,System.ClientModel.Primitives.RequestOptions)")]

[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.DeleteAgentVersionAsync(System.String,System.String,System.ClientModel.Primitives.RequestOptions)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.DeleteAgentVersion(System.String,System.String,System.ClientModel.Primitives.RequestOptions)")]

[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult<ProjectsAgentRecord>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.CreateAgentVersion(System.String,Azure.AI.Projects.Agents.ProjectsAgentDefinition,System.Collections.Generic.IDictionary{System.String,System.String},System.String,Azure.AI.Projects.Agents.AgentBlueprintReference,System.Nullable{Azure.AI.Projects.Agents.AgentDefinitionOptInKeys},System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult<ProjectsAgentRecord>>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.CreateAgentVersionAsync(System.String,Azure.AI.Projects.Agents.ProjectsAgentDefinition,System.Collections.Generic.IDictionary{System.String,System.String},System.String,Azure.AI.Projects.Agents.AgentBlueprintReference,System.Nullable{Azure.AI.Projects.Agents.AgentDefinitionOptInKeys},System.Threading.CancellationToken)")]

[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.PatchAgentObject(System.String,Azure.AI.Projects.Agents.PatchAgentOptions,System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.PatchAgentObjectAsync(System.String,Azure.AI.Projects.Agents.PatchAgentOptions,System.Threading.CancellationToken)")]

[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.CreateSession(System.String,System.String,System.ClientModel.BinaryContent,System.String,System.ClientModel.Primitives.RequestOptions)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.CreateSessionAsync(System.String,System.String,System.ClientModel.BinaryContent,System.String,System.ClientModel.Primitives.RequestOptions)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult<AgentSessionResource>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.CreateSession(System.String,System.String,Azure.AI.Projects.Agents.VersionIndicator,System.String,System.Nullable{Azure.AI.Projects.Agents.AgentDefinitionOptInKeys},System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult<AgentSessionResource>>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.CreateSessionAsync(System.String,System.String,Azure.AI.Projects.Agents.VersionIndicator,System.String,System.Nullable{Azure.AI.Projects.Agents.AgentDefinitionOptInKeys},System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult<AgentSessionResource>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.CreateSession(System.String,System.String,Azure.AI.Projects.Agents.VersionIndicator,System.String,System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult<AgentSessionResource>>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.CreateSessionAsync(System.String,System.String,Azure.AI.Projects.Agents.VersionIndicator,System.String,System.Threading.CancellationToken)")]

[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.GetSession(System.String,System.String,System.String,System.ClientModel.Primitives.RequestOptions)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.GetSessionAsync(System.String,System.String,System.String,System.ClientModel.Primitives.RequestOptions)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult<AgentSessionResource>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.GetSession(System.String,System.String,System.Nullable{Azure.AI.Projects.Agents.AgentDefinitionOptInKeys},System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult<AgentSessionResource>>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.GetSessionAsync(System.String,System.String,System.Nullable{Azure.AI.Projects.Agents.AgentDefinitionOptInKeys},System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult<AgentSessionResource>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.GetSession(System.String,System.String,System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult<AgentSessionResource>>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.GetSessionAsync(System.String,System.String,System.Threading.CancellationToken)")]

[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.DeleteSessionAsync(System.String,System.String,System.String,System.String,System.ClientModel.Primitives.RequestOptions)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.DeleteSession(System.String,System.String,System.String,System.String,System.ClientModel.Primitives.RequestOptions)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.DeleteSession(System.String,System.String,System.String,System.Nullable{Azure.AI.Projects.Agents.AgentDefinitionOptInKeys},System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.DeleteSessionAsync(System.String,System.String,System.String,System.Nullable{Azure.AI.Projects.Agents.AgentDefinitionOptInKeys},System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.DeleteSession(System.String,System.String,System.String,System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.DeleteSessionAsync(System.String,System.String,System.String,System.Threading.CancellationToken)")]

[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns CollectionResult<AgentSessionResource>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.GetSessions(System.String,System.Nullable{System.Int32},System.Nullable{Azure.AI.Projects.Agents.AgentListOrder},System.String,System.String,System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns AsyncCollectionResult<AgentSessionResource>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.GetSessionsAsync(System.String,System.Nullable{System.Int32},System.Nullable{Azure.AI.Projects.Agents.AgentListOrder},System.String,System.String,System.Threading.CancellationToken)")]

[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult<SessionLogEvent>>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.GetSessionLogStreamAsync(System.String,System.String,System.String,System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult<SessionLogEvent>.", Scope = "member", Target = "~M:Azure.AI.Projects.Agents.AgentAdministrationClient.GetSessionLogStream(System.String,System.String,System.String,System.Threading.CancellationToken)")]

// AZC0007 Suppress the warning on AgentAdministrationClient creation.
[assembly: SuppressMessage("Usage", "AZC0007", Justification = "Custom constructor for AgentsClient.", Scope = "member", Target = "~T:Azure.AI.Projects.Agents.AgentAdministrationClient")]
