// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core;

namespace Azure.Messaging.EventGrid.Namespaces
{
    /// <summary> Failed LockToken information. </summary>
    public partial class FailedLockToken
    {
        /// <summary> Initializes a new instance of FailedLockToken. </summary>
        /// <param name="lockToken"> LockToken value. </param>
        /// <param name="errorCode"> Error code related to the token. Example of such error codes are BadToken: which indicates the Token is not formatted correctly, TokenLost: which indicates that token is not found, and InternalServerError: For any internal server errors. </param>
        /// <param name="errorDescription"> Description of the token error. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="lockToken"/>, <paramref name="errorCode"/> or <paramref name="errorDescription"/> is null. </exception>
        internal FailedLockToken(string lockToken, string errorCode, string errorDescription)
        {
            Argument.AssertNotNull(lockToken, nameof(lockToken));
            Argument.AssertNotNull(errorCode, nameof(errorCode));
            Argument.AssertNotNull(errorDescription, nameof(errorDescription));

            LockToken = lockToken;
            ErrorCode = errorCode;
            ErrorDescription = errorDescription;
        }

        /// <summary> LockToken value. </summary>
        public string LockToken { get; }
        /// <summary> Error code related to the token. Example of such error codes are BadToken: which indicates the Token is not formatted correctly, TokenLost: which indicates that token is not found, and InternalServerError: For any internal server errors. </summary>
        public string ErrorCode { get; }
        /// <summary> Description of the token error. </summary>
        public string ErrorDescription { get; }
    }
}
