// <auto-generated/>

using Azure.ResourceManager.ContainerServiceFleet;
using Azure.ResourceManager.ContainerServiceFleet.Models;
using System.ClientModel.Primitives;
using Azure.ResourceManager.Models;
using Azure.ResourceManager.Resources.Models;

namespace Azure.ResourceManager.ContainerServiceFleet;

[ModelReaderWriterBuildable(typeof(AutoUpgradeProfileData))]
[ModelReaderWriterBuildable(typeof(AutoUpgradeProfileResource))]
[ModelReaderWriterBuildable(typeof(ContainerServiceFleetData))]
[ModelReaderWriterBuildable(typeof(ContainerServiceFleetMemberData))]
[ModelReaderWriterBuildable(typeof(ContainerServiceFleetMemberResource))]
[ModelReaderWriterBuildable(typeof(ContainerServiceFleetResource))]
[ModelReaderWriterBuildable(typeof(ContainerServiceFleetUpdateRunData))]
[ModelReaderWriterBuildable(typeof(ContainerServiceFleetUpdateRunResource))]
[ModelReaderWriterBuildable(typeof(FleetUpdateStrategyData))]
[ModelReaderWriterBuildable(typeof(FleetUpdateStrategyResource))]
[ModelReaderWriterBuildable(typeof(ContainerServiceFleetManagedClusterUpdate))]
[ModelReaderWriterBuildable(typeof(AutoUpgradeNodeImageSelection))]
[ModelReaderWriterBuildable(typeof(AutoUpgradeProfileGenerateResult))]
[ModelReaderWriterBuildable(typeof(AutoUpgradeProfileListResult))]
[ModelReaderWriterBuildable(typeof(AutoUpgradeProfileStatus))]
[ModelReaderWriterBuildable(typeof(ContainerServiceFleetAgentProfile))]
[ModelReaderWriterBuildable(typeof(ContainerServiceFleetAPIServerAccessProfile))]
[ModelReaderWriterBuildable(typeof(ContainerServiceFleetListResult))]
[ModelReaderWriterBuildable(typeof(ContainerServiceFleetManagedClusterUpgradeSpec))]
[ModelReaderWriterBuildable(typeof(ContainerServiceFleetMemberListResult))]
[ModelReaderWriterBuildable(typeof(ContainerServiceFleetMemberPatch))]
[ModelReaderWriterBuildable(typeof(ContainerServiceFleetMemberStatus))]
[ModelReaderWriterBuildable(typeof(ContainerServiceFleetPatch))]
[ModelReaderWriterBuildable(typeof(ContainerServiceFleetSkipProperties))]
[ModelReaderWriterBuildable(typeof(ContainerServiceFleetSkipTarget))]
[ModelReaderWriterBuildable(typeof(ContainerServiceFleetStatus))]
[ModelReaderWriterBuildable(typeof(ContainerServiceFleetUpdateGroup))]
[ModelReaderWriterBuildable(typeof(ContainerServiceFleetUpdateGroupStatus))]
[ModelReaderWriterBuildable(typeof(ContainerServiceFleetUpdateRunListResult))]
[ModelReaderWriterBuildable(typeof(ContainerServiceFleetUpdateRunStatus))]
[ModelReaderWriterBuildable(typeof(ContainerServiceFleetUpdateRunStrategy))]
[ModelReaderWriterBuildable(typeof(ContainerServiceFleetUpdateStage))]
[ModelReaderWriterBuildable(typeof(ContainerServiceFleetUpdateStageStatus))]
[ModelReaderWriterBuildable(typeof(ContainerServiceFleetUpdateStatus))]
[ModelReaderWriterBuildable(typeof(ContainerServiceFleetWaitStatus))]
[ModelReaderWriterBuildable(typeof(FleetCredentialResult))]
[ModelReaderWriterBuildable(typeof(FleetCredentialResults))]
[ModelReaderWriterBuildable(typeof(FleetHubProfile))]
[ModelReaderWriterBuildable(typeof(FleetUpdateStrategyListResult))]
[ModelReaderWriterBuildable(typeof(MemberUpdateStatus))]
[ModelReaderWriterBuildable(typeof(NodeImageSelection))]
[ModelReaderWriterBuildable(typeof(NodeImageSelectionStatus))]
[ModelReaderWriterBuildable(typeof(NodeImageVersion))]
[ModelReaderWriterBuildable(typeof(SystemData))]
[ModelReaderWriterBuildable(typeof(ManagedServiceIdentity))]
[ModelReaderWriterBuildable(typeof(WritableSubResource))]
[ModelReaderWriterBuildable(typeof(SubResource))]
public partial class AzureResourceManagerContainerServiceFleetContext
{
}
