<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Contains the core functionality for defining Azure infrastructure with dotnet code.</Description>
    <Version>1.6.0-beta.2</Version>
    <!--The ApiCompatVersion is managed automatically and should not generally be modified manually.-->
    <ApiCompatVersion>1.5.0</ApiCompatVersion>
    <TargetFrameworks>$(RequiredTargetFrameworks)</TargetFrameworks>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
  </PropertyGroup>
</Project>
