// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using System.Diagnostics.CodeAnalysis;

// Suppress AZC0034 warnings for types that have naming conflicts with FormRecognizer and DocumentIntelligence SDKs.
// These conflicts are expected as Content Understanding is the next iterations of the Document Intelligence service.
// The types are intentionally named to match the service specification and maintain consistency across Azure AI SDKs.
[assembly: SuppressMessage("Design", "AZC0034", Justification = "Type name conflicts with FormRecognizer/DocumentIntelligence are expected. These types match the service specification and maintain consistency across Azure AI SDKs.", Scope = "type", Target = "~T:Azure.AI.ContentUnderstanding.AnalyzeResult")]
[assembly: SuppressMessage("Design", "AZC0034", Justification = "Type name conflicts with FormRecognizer/DocumentIntelligence are expected. These types match the service specification and maintain consistency across Azure AI SDKs.", Scope = "type", Target = "~T:Azure.AI.ContentUnderstanding.CopyAuthorization")]
[assembly: SuppressMessage("Design", "AZC0034", Justification = "Type name conflicts with FormRecognizer/DocumentIntelligence are expected. These types match the service specification and maintain consistency across Azure AI SDKs.", Scope = "type", Target = "~T:Azure.AI.ContentUnderstanding.DocumentBarcode")]
[assembly: SuppressMessage("Design", "AZC0034", Justification = "Type name conflicts with FormRecognizer/DocumentIntelligence are expected. These types match the service specification and maintain consistency across Azure AI SDKs.", Scope = "type", Target = "~T:Azure.AI.ContentUnderstanding.DocumentBarcodeKind")]
[assembly: SuppressMessage("Design", "AZC0034", Justification = "Type name conflicts with FormRecognizer/DocumentIntelligence are expected. These types match the service specification and maintain consistency across Azure AI SDKs.", Scope = "type", Target = "~T:Azure.AI.ContentUnderstanding.DocumentCaption")]
[assembly: SuppressMessage("Design", "AZC0034", Justification = "Type name conflicts with FormRecognizer/DocumentIntelligence are expected. These types match the service specification and maintain consistency across Azure AI SDKs.", Scope = "type", Target = "~T:Azure.AI.ContentUnderstanding.DocumentFigure")]
[assembly: SuppressMessage("Design", "AZC0034", Justification = "Type name conflicts with FormRecognizer/DocumentIntelligence are expected. These types match the service specification and maintain consistency across Azure AI SDKs.", Scope = "type", Target = "~T:Azure.AI.ContentUnderstanding.DocumentFootnote")]
[assembly: SuppressMessage("Design", "AZC0034", Justification = "Type name conflicts with FormRecognizer/DocumentIntelligence are expected. These types match the service specification and maintain consistency across Azure AI SDKs.", Scope = "type", Target = "~T:Azure.AI.ContentUnderstanding.DocumentFormula")]
[assembly: SuppressMessage("Design", "AZC0034", Justification = "Type name conflicts with FormRecognizer/DocumentIntelligence are expected. These types match the service specification and maintain consistency across Azure AI SDKs.", Scope = "type", Target = "~T:Azure.AI.ContentUnderstanding.DocumentFormulaKind")]
[assembly: SuppressMessage("Design", "AZC0034", Justification = "Type name conflicts with FormRecognizer/DocumentIntelligence are expected. These types match the service specification and maintain consistency across Azure AI SDKs.", Scope = "type", Target = "~T:Azure.AI.ContentUnderstanding.DocumentLine")]
[assembly: SuppressMessage("Design", "AZC0034", Justification = "Type name conflicts with FormRecognizer/DocumentIntelligence are expected. These types match the service specification and maintain consistency across Azure AI SDKs.", Scope = "type", Target = "~T:Azure.AI.ContentUnderstanding.DocumentPage")]
[assembly: SuppressMessage("Design", "AZC0034", Justification = "Type name conflicts with FormRecognizer/DocumentIntelligence are expected. These types match the service specification and maintain consistency across Azure AI SDKs.", Scope = "type", Target = "~T:Azure.AI.ContentUnderstanding.DocumentParagraph")]
[assembly: SuppressMessage("Design", "AZC0034", Justification = "Type name conflicts with FormRecognizer/DocumentIntelligence are expected. These types match the service specification and maintain consistency across Azure AI SDKs.", Scope = "type", Target = "~T:Azure.AI.ContentUnderstanding.DocumentSection")]
[assembly: SuppressMessage("Design", "AZC0034", Justification = "Type name conflicts with FormRecognizer/DocumentIntelligence are expected. These types match the service specification and maintain consistency across Azure AI SDKs.", Scope = "type", Target = "~T:Azure.AI.ContentUnderstanding.DocumentTable")]
[assembly: SuppressMessage("Design", "AZC0034", Justification = "Type name conflicts with FormRecognizer/DocumentIntelligence are expected. These types match the service specification and maintain consistency across Azure AI SDKs.", Scope = "type", Target = "~T:Azure.AI.ContentUnderstanding.DocumentTableCell")]
[assembly: SuppressMessage("Design", "AZC0034", Justification = "Type name conflicts with FormRecognizer/DocumentIntelligence are expected. These types match the service specification and maintain consistency across Azure AI SDKs.", Scope = "type", Target = "~T:Azure.AI.ContentUnderstanding.DocumentTableCellKind")]
[assembly: SuppressMessage("Design", "AZC0034", Justification = "Type name conflicts with FormRecognizer/DocumentIntelligence are expected. These types match the service specification and maintain consistency across Azure AI SDKs.", Scope = "type", Target = "~T:Azure.AI.ContentUnderstanding.DocumentWord")]
[assembly: SuppressMessage("Design", "AZC0034", Justification = "Type name conflicts with FormRecognizer/DocumentIntelligence are expected. These types match the service specification and maintain consistency across Azure AI SDKs.", Scope = "type", Target = "~T:Azure.AI.ContentUnderstanding.LengthUnit")]
