<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Azure.Provisioning.AlertsManagement simplifies declarative resource provisioning in .NET.</Description>
    <Version>1.0.0-beta.1</Version>
    <TypespecAdditionalOptions>namespace=Azure.Provisioning.AlertsManagement;emitter-output-dir=$(MSBuildProjectDirectory)/..;api-version=2025-05-25-preview</TypespecAdditionalOptions>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Provisioning" />
  </ItemGroup>

</Project>
