// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;

namespace Azure.AI.OpenAI
{
    public partial class CompletionsUsage
    {
        internal static CompletionsUsage DeserializeCompletionsUsage(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                // Handle deserialization of "usage":null in payloads
                return null;
            }

            int completionTokens = default;
            int promptTokens = default;
            int totalTokens = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("completion_tokens"u8))
                {
                    completionTokens = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("prompt_tokens"u8))
                {
                    promptTokens = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("total_tokens"u8))
                {
                    totalTokens = property.Value.GetInt32();
                    continue;
                }
            }
            return new CompletionsUsage(completionTokens, promptTokens, totalTokens);
        }
    }
}
