// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core;

namespace Azure.AI.OpenAI
{
    /// <summary> Schema to create a prompt completion from a deployment. </summary>
    public partial class EmbeddingsOptions
    {
        internal string InternalNonAzureModelName { get; set; }

        /// <inheritdoc cref="EmbeddingsOptions.EmbeddingsOptions(System.Collections.Generic.IEnumerable{string})"/>
        public EmbeddingsOptions(string input)
            : this(new string[] { input })
        {
        }
    }
}
