// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Batch.Protocol.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for JobScheduleState.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum JobScheduleState
    {
        [EnumMember(Value = "active")]
        Active,
        [EnumMember(Value = "completed")]
        Completed,
        [EnumMember(Value = "disabled")]
        Disabled,
        [EnumMember(Value = "terminating")]
        Terminating,
        [EnumMember(Value = "deleting")]
        Deleting
    }
    internal static class JobScheduleStateEnumExtension
    {
        internal static string ToSerializedValue(this JobScheduleState? value)
        {
            return value == null ? null : ((JobScheduleState)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this JobScheduleState value)
        {
            switch( value )
            {
                case JobScheduleState.Active:
                    return "active";
                case JobScheduleState.Completed:
                    return "completed";
                case JobScheduleState.Disabled:
                    return "disabled";
                case JobScheduleState.Terminating:
                    return "terminating";
                case JobScheduleState.Deleting:
                    return "deleting";
            }
            return null;
        }

        internal static JobScheduleState? ParseJobScheduleState(this string value)
        {
            switch( value )
            {
                case "active":
                    return JobScheduleState.Active;
                case "completed":
                    return JobScheduleState.Completed;
                case "disabled":
                    return JobScheduleState.Disabled;
                case "terminating":
                    return JobScheduleState.Terminating;
                case "deleting":
                    return JobScheduleState.Deleting;
            }
            return null;
        }
    }
}
