// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Batch.Protocol.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Options for reimaging a compute node.
    /// </summary>
    public partial class NodeReimageParameter
    {
        /// <summary>
        /// Initializes a new instance of the NodeReimageParameter class.
        /// </summary>
        public NodeReimageParameter()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NodeReimageParameter class.
        /// </summary>
        /// <param name="nodeReimageOption">When to reimage the compute node
        /// and what to do with currently running tasks.</param>
        public NodeReimageParameter(ComputeNodeReimageOption? nodeReimageOption = default(ComputeNodeReimageOption?))
        {
            NodeReimageOption = nodeReimageOption;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets when to reimage the compute node and what to do with
        /// currently running tasks.
        /// </summary>
        /// <remarks>
        /// Values are:
        ///
        /// requeue - Terminate running task processes and requeue the tasks.
        /// The tasks will run again when a node is available. Reimage the node
        /// as soon as tasks have been terminated.
        /// terminate - Terminate running tasks. The tasks will not run again.
        /// Reimage the node as soon as tasks have been terminated.
        /// taskcompletion - Allow currently running tasks to complete.
        /// Schedule no new tasks while waiting. Reimage the node when all
        /// tasks have completed.
        /// retaineddata - Allow currently running tasks to complete, then wait
        /// for all task data retention periods to expire. Schedule no new
        /// tasks while waiting. Reimage the node when all task retention
        /// periods have expired.
        ///
        /// The default value is requeue. Possible values include: 'requeue',
        /// 'terminate', 'taskCompletion', 'retainedData'
        /// </remarks>
        [JsonProperty(PropertyName = "nodeReimageOption")]
        public ComputeNodeReimageOption? NodeReimageOption { get; set; }

    }
}
