<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>1.0.0-beta.1</Version>
    <PackageId>Azure.ResourceManager.Marketplace.Reviews</PackageId>
    <Description>Azure Resource Manager client SDK for Azure Marketplace Reviews.</Description>
    <PackageTags>azure;management;arm;resource manager;marketplace;reviews</PackageTags>
  </PropertyGroup>
</Project>