<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RequiredTargetFrameworks>net10.0</RequiredTargetFrameworks>
    <TargetFramework>$(RequiredTargetFrameworks)</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
    <IsGeneratorLibrary>true</IsGeneratorLibrary>
    <IsPackable>false</IsPackable>
    <IncludeOperationsSharedSource>true</IncludeOperationsSharedSource>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\src\Extensions.Plugin.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.TypeSpec.Generator.ClientModel" />
    <PackageReference Include="Microsoft.TypeSpec.Generator.Input" />
    <PackageReference Include="Moq" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>
  <ItemGroup>
    <None Update="TestHelpers\Configuration.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="**\TestData\**\*.cs" />
    <None Include="**\TestData\**\*.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
