namespace Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes
{
    public partial class AzureResourceManagerKubernetesConfiguration_PrivateLinkScopesContext : System.ClientModel.Primitives.ModelReaderWriterContext
    {
        internal AzureResourceManagerKubernetesConfiguration_PrivateLinkScopesContext() { }
        public static Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.AzureResourceManagerKubernetesConfiguration_PrivateLinkScopesContext Default { get { throw null; } }
        protected override bool TryGetTypeBuilderCore(System.Type type, out System.ClientModel.Primitives.ModelReaderWriterTypeBuilder builder) { throw null; }
    }
    public partial class KubernetesConfigurationPrivateLinkScopeCollection : Azure.ResourceManager.ArmCollection, System.Collections.Generic.IAsyncEnumerable<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>, System.Collections.Generic.IEnumerable<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>, System.Collections.IEnumerable
    {
        protected KubernetesConfigurationPrivateLinkScopeCollection() { }
        public virtual Azure.ResourceManager.ArmOperation<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> CreateOrUpdate(Azure.WaitUntil waitUntil, string scopeName, Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData data, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.ResourceManager.ArmOperation<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>> CreateOrUpdateAsync(Azure.WaitUntil waitUntil, string scopeName, Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData data, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Response<bool> Exists(string scopeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<bool>> ExistsAsync(string scopeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> Get(string scopeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Pageable<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> GetAll(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.AsyncPageable<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> GetAllAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>> GetAsync(string scopeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.NullableResponse<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> GetIfExists(string scopeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.NullableResponse<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>> GetIfExistsAsync(string scopeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        System.Collections.Generic.IAsyncEnumerator<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> System.Collections.Generic.IAsyncEnumerable<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>.GetAsyncEnumerator(System.Threading.CancellationToken cancellationToken) { throw null; }
        System.Collections.Generic.IEnumerator<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> System.Collections.Generic.IEnumerable<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>.GetEnumerator() { throw null; }
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() { throw null; }
    }
    public partial class KubernetesConfigurationPrivateLinkScopeData : Azure.ResourceManager.Models.TrackedResourceData, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>
    {
        public KubernetesConfigurationPrivateLinkScopeData(Azure.Core.AzureLocation location) { }
        public Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties Properties { get { throw null; } set { } }
        protected virtual Azure.ResourceManager.Models.ResourceData JsonModelCreateCore(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected override void JsonModelWriteCore(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        protected virtual Azure.ResourceManager.Models.ResourceData PersistableModelCreateCore(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual System.BinaryData PersistableModelWriteCore(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class KubernetesConfigurationPrivateLinkScopeResource : Azure.ResourceManager.ArmResource, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>
    {
        public static readonly Azure.Core.ResourceType ResourceType;
        protected KubernetesConfigurationPrivateLinkScopeResource() { }
        public virtual Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData Data { get { throw null; } }
        public virtual bool HasData { get { throw null; } }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> AddTag(string key, string value, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>> AddTagAsync(string key, string value, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public static Azure.Core.ResourceIdentifier CreateResourceIdentifier(string subscriptionId, string resourceGroupName, string scopeName) { throw null; }
        public virtual Azure.ResourceManager.ArmOperation Delete(Azure.WaitUntil waitUntil, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.ResourceManager.ArmOperation> DeleteAsync(Azure.WaitUntil waitUntil, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> Get(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>> GetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateEndpointConnectionResource> GetPrivateEndpointConnection(string privateEndpointConnectionName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateEndpointConnectionResource>> GetPrivateEndpointConnectionAsync(string privateEndpointConnectionName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateEndpointConnectionCollection GetPrivateEndpointConnections() { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateLinkResource> GetPrivateLinkResource(string groupName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateLinkResource>> GetPrivateLinkResourceAsync(string groupName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateLinkResourceCollection GetPrivateLinkResources() { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> RemoveTag(string key, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>> RemoveTagAsync(string key, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> SetTags(System.Collections.Generic.IDictionary<string, string> tags, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>> SetTagsAsync(System.Collections.Generic.IDictionary<string, string> tags, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> Update(Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch patch, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>> UpdateAsync(Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch patch, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
    }
    public static partial class KubernetesConfigurationPrivateLinkScopesExtensions
    {
        public static Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> GetKubernetesConfigurationPrivateLinkScope(this Azure.ResourceManager.Resources.ResourceGroupResource resourceGroupResource, string scopeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public static System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>> GetKubernetesConfigurationPrivateLinkScopeAsync(this Azure.ResourceManager.Resources.ResourceGroupResource resourceGroupResource, string scopeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource GetKubernetesConfigurationPrivateLinkScopeResource(this Azure.ResourceManager.ArmClient client, Azure.Core.ResourceIdentifier id) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeCollection GetKubernetesConfigurationPrivateLinkScopes(this Azure.ResourceManager.Resources.ResourceGroupResource resourceGroupResource) { throw null; }
        public static Azure.Pageable<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> GetKubernetesConfigurationPrivateLinkScopes(this Azure.ResourceManager.Resources.SubscriptionResource subscriptionResource, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public static Azure.AsyncPageable<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> GetKubernetesConfigurationPrivateLinkScopesAsync(this Azure.ResourceManager.Resources.SubscriptionResource subscriptionResource, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateEndpointConnectionResource GetPrivateEndpointConnectionResource(this Azure.ResourceManager.ArmClient client, Azure.Core.ResourceIdentifier id) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateLinkResource GetPrivateLinkResource(this Azure.ResourceManager.ArmClient client, Azure.Core.ResourceIdentifier id) { throw null; }
    }
    public partial class KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData : Azure.ResourceManager.Models.ResourceData, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData>
    {
        public KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData() { }
        public string PrivateEndpointId { get { throw null; } }
        public Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState PrivateLinkServiceConnectionState { get { throw null; } set { } }
        public Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState? ProvisioningState { get { throw null; } }
        protected virtual Azure.ResourceManager.Models.ResourceData JsonModelCreateCore(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected override void JsonModelWriteCore(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        protected virtual Azure.ResourceManager.Models.ResourceData PersistableModelCreateCore(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual System.BinaryData PersistableModelWriteCore(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class KubernetesConfigurationPrivateLinkScopesPrivateLinkResourceData : Azure.ResourceManager.Models.ResourceData, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateLinkResourceData>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateLinkResourceData>
    {
        internal KubernetesConfigurationPrivateLinkScopesPrivateLinkResourceData() { }
        public string GroupId { get { throw null; } }
        public System.Collections.Generic.IReadOnlyList<string> RequiredMembers { get { throw null; } }
        public System.Collections.Generic.IList<string> RequiredZoneNames { get { throw null; } }
        protected virtual Azure.ResourceManager.Models.ResourceData JsonModelCreateCore(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected override void JsonModelWriteCore(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        protected virtual Azure.ResourceManager.Models.ResourceData PersistableModelCreateCore(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual System.BinaryData PersistableModelWriteCore(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateLinkResourceData System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateLinkResourceData>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateLinkResourceData>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateLinkResourceData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateLinkResourceData>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateLinkResourceData>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateLinkResourceData>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class PrivateEndpointConnectionCollection : Azure.ResourceManager.ArmCollection, System.Collections.Generic.IAsyncEnumerable<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateEndpointConnectionResource>, System.Collections.Generic.IEnumerable<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateEndpointConnectionResource>, System.Collections.IEnumerable
    {
        protected PrivateEndpointConnectionCollection() { }
        public virtual Azure.ResourceManager.ArmOperation<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateEndpointConnectionResource> CreateOrUpdate(Azure.WaitUntil waitUntil, string privateEndpointConnectionName, Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData data, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.ResourceManager.ArmOperation<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateEndpointConnectionResource>> CreateOrUpdateAsync(Azure.WaitUntil waitUntil, string privateEndpointConnectionName, Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData data, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Response<bool> Exists(string privateEndpointConnectionName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<bool>> ExistsAsync(string privateEndpointConnectionName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateEndpointConnectionResource> Get(string privateEndpointConnectionName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Pageable<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateEndpointConnectionResource> GetAll(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.AsyncPageable<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateEndpointConnectionResource> GetAllAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateEndpointConnectionResource>> GetAsync(string privateEndpointConnectionName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.NullableResponse<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateEndpointConnectionResource> GetIfExists(string privateEndpointConnectionName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.NullableResponse<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateEndpointConnectionResource>> GetIfExistsAsync(string privateEndpointConnectionName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        System.Collections.Generic.IAsyncEnumerator<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateEndpointConnectionResource> System.Collections.Generic.IAsyncEnumerable<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateEndpointConnectionResource>.GetAsyncEnumerator(System.Threading.CancellationToken cancellationToken) { throw null; }
        System.Collections.Generic.IEnumerator<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateEndpointConnectionResource> System.Collections.Generic.IEnumerable<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateEndpointConnectionResource>.GetEnumerator() { throw null; }
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() { throw null; }
    }
    public partial class PrivateEndpointConnectionResource : Azure.ResourceManager.ArmResource, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData>
    {
        public static readonly Azure.Core.ResourceType ResourceType;
        protected PrivateEndpointConnectionResource() { }
        public virtual Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData Data { get { throw null; } }
        public virtual bool HasData { get { throw null; } }
        public static Azure.Core.ResourceIdentifier CreateResourceIdentifier(string subscriptionId, string resourceGroupName, string scopeName, string privateEndpointConnectionName) { throw null; }
        public virtual Azure.ResourceManager.ArmOperation Delete(Azure.WaitUntil waitUntil, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.ResourceManager.ArmOperation> DeleteAsync(Azure.WaitUntil waitUntil, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateEndpointConnectionResource> Get(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateEndpointConnectionResource>> GetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        public virtual Azure.ResourceManager.ArmOperation<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateEndpointConnectionResource> Update(Azure.WaitUntil waitUntil, Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData data, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.ResourceManager.ArmOperation<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateEndpointConnectionResource>> UpdateAsync(Azure.WaitUntil waitUntil, Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData data, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
    }
    public partial class PrivateLinkResource : Azure.ResourceManager.ArmResource, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateLinkResourceData>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateLinkResourceData>
    {
        public static readonly Azure.Core.ResourceType ResourceType;
        protected PrivateLinkResource() { }
        public virtual Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateLinkResourceData Data { get { throw null; } }
        public virtual bool HasData { get { throw null; } }
        public static Azure.Core.ResourceIdentifier CreateResourceIdentifier(string subscriptionId, string resourceGroupName, string scopeName, string groupName) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateLinkResource> Get(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateLinkResource>> GetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateLinkResourceData System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateLinkResourceData>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateLinkResourceData>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateLinkResourceData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateLinkResourceData>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateLinkResourceData>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateLinkResourceData>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class PrivateLinkResourceCollection : Azure.ResourceManager.ArmCollection, System.Collections.Generic.IAsyncEnumerable<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateLinkResource>, System.Collections.Generic.IEnumerable<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateLinkResource>, System.Collections.IEnumerable
    {
        protected PrivateLinkResourceCollection() { }
        public virtual Azure.Response<bool> Exists(string groupName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<bool>> ExistsAsync(string groupName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateLinkResource> Get(string groupName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Pageable<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateLinkResource> GetAll(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.AsyncPageable<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateLinkResource> GetAllAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateLinkResource>> GetAsync(string groupName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.NullableResponse<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateLinkResource> GetIfExists(string groupName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.NullableResponse<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateLinkResource>> GetIfExistsAsync(string groupName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        System.Collections.Generic.IAsyncEnumerator<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateLinkResource> System.Collections.Generic.IAsyncEnumerable<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateLinkResource>.GetAsyncEnumerator(System.Threading.CancellationToken cancellationToken) { throw null; }
        System.Collections.Generic.IEnumerator<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateLinkResource> System.Collections.Generic.IEnumerable<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateLinkResource>.GetEnumerator() { throw null; }
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() { throw null; }
    }
}
namespace Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Mocking
{
    public partial class MockableKubernetesConfigurationPrivateLinkScopesArmClient : Azure.ResourceManager.ArmResource
    {
        protected MockableKubernetesConfigurationPrivateLinkScopesArmClient() { }
        public virtual Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource GetKubernetesConfigurationPrivateLinkScopeResource(Azure.Core.ResourceIdentifier id) { throw null; }
        public virtual Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateEndpointConnectionResource GetPrivateEndpointConnectionResource(Azure.Core.ResourceIdentifier id) { throw null; }
        public virtual Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.PrivateLinkResource GetPrivateLinkResource(Azure.Core.ResourceIdentifier id) { throw null; }
    }
    public partial class MockableKubernetesConfigurationPrivateLinkScopesResourceGroupResource : Azure.ResourceManager.ArmResource
    {
        protected MockableKubernetesConfigurationPrivateLinkScopesResourceGroupResource() { }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> GetKubernetesConfigurationPrivateLinkScope(string scopeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>> GetKubernetesConfigurationPrivateLinkScopeAsync(string scopeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeCollection GetKubernetesConfigurationPrivateLinkScopes() { throw null; }
    }
    public partial class MockableKubernetesConfigurationPrivateLinkScopesSubscriptionResource : Azure.ResourceManager.ArmResource
    {
        protected MockableKubernetesConfigurationPrivateLinkScopesSubscriptionResource() { }
        public virtual Azure.Pageable<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> GetKubernetesConfigurationPrivateLinkScopes(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.AsyncPageable<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> GetKubernetesConfigurationPrivateLinkScopesAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
    }
}
namespace Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models
{
    public static partial class ArmKubernetesConfigurationPrivateLinkScopesModelFactory
    {
        public static Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData KubernetesConfigurationPrivateLinkScopeData(Azure.Core.ResourceIdentifier id = null, string name = null, Azure.Core.ResourceType resourceType = default(Azure.Core.ResourceType), Azure.ResourceManager.Models.SystemData systemData = null, System.Collections.Generic.IDictionary<string, string> tags = null, Azure.Core.AzureLocation location = default(Azure.Core.AzureLocation), Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties properties = null) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch KubernetesConfigurationPrivateLinkScopePatch(System.Collections.Generic.IDictionary<string, string> tags = null) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties KubernetesConfigurationPrivateLinkScopeProperties(Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.PublicNetworkAccessType? publicNetworkAccess = default(Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.PublicNetworkAccessType?), Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.ProvisioningState? provisioningState = default(Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.ProvisioningState?), string clusterResourceId = null, string privateLinkScopeId = null, System.Collections.Generic.IEnumerable<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData> privateEndpointConnections = null) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData(Azure.Core.ResourceIdentifier id = null, string name = null, Azure.Core.ResourceType resourceType = default(Azure.Core.ResourceType), Azure.ResourceManager.Models.SystemData systemData = null, Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState privateLinkServiceConnectionState = null, Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState? provisioningState = default(Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState?), string privateEndpointId = null) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateLinkResourceData KubernetesConfigurationPrivateLinkScopesPrivateLinkResourceData(Azure.Core.ResourceIdentifier id = null, string name = null, Azure.Core.ResourceType resourceType = default(Azure.Core.ResourceType), Azure.ResourceManager.Models.SystemData systemData = null, string groupId = null, System.Collections.Generic.IEnumerable<string> requiredMembers = null, System.Collections.Generic.IEnumerable<string> requiredZoneNames = null) { throw null; }
    }
    public partial class KubernetesConfigurationPrivateLinkScopePatch : System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch>
    {
        public KubernetesConfigurationPrivateLinkScopePatch() { }
        public System.Collections.Generic.IDictionary<string, string> Tags { get { throw null; } }
        protected virtual Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch JsonModelCreateCore(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual void JsonModelWriteCore(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        protected virtual Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch PersistableModelCreateCore(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual System.BinaryData PersistableModelWriteCore(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class KubernetesConfigurationPrivateLinkScopeProperties : System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties>
    {
        public KubernetesConfigurationPrivateLinkScopeProperties(string clusterResourceId) { }
        public string ClusterResourceId { get { throw null; } set { } }
        public System.Collections.Generic.IReadOnlyList<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionData> PrivateEndpointConnections { get { throw null; } }
        public string PrivateLinkScopeId { get { throw null; } }
        public Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.ProvisioningState? ProvisioningState { get { throw null; } }
        public Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.PublicNetworkAccessType? PublicNetworkAccess { get { throw null; } set { } }
        protected virtual Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties JsonModelCreateCore(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual void JsonModelWriteCore(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        protected virtual Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties PersistableModelCreateCore(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual System.BinaryData PersistableModelWriteCore(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public readonly partial struct KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState : System.IEquatable<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState>
    {
        private readonly object _dummy;
        private readonly int _dummyPrimitive;
        public KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState(string value) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState Creating { get { throw null; } }
        public static Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState Deleting { get { throw null; } }
        public static Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState Failed { get { throw null; } }
        public static Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState Succeeded { get { throw null; } }
        public bool Equals(Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState other) { throw null; }
        public override bool Equals(object obj) { throw null; }
        public override int GetHashCode() { throw null; }
        public static bool operator ==(Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState left, Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState right) { throw null; }
        public static implicit operator Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState (string value) { throw null; }
        public static implicit operator Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState? (string value) { throw null; }
        public static bool operator !=(Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState left, Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState right) { throw null; }
        public override string ToString() { throw null; }
    }
    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public readonly partial struct KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus : System.IEquatable<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus>
    {
        private readonly object _dummy;
        private readonly int _dummyPrimitive;
        public KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus(string value) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus Approved { get { throw null; } }
        public static Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus Pending { get { throw null; } }
        public static Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus Rejected { get { throw null; } }
        public bool Equals(Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus other) { throw null; }
        public override bool Equals(object obj) { throw null; }
        public override int GetHashCode() { throw null; }
        public static bool operator ==(Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus left, Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus right) { throw null; }
        public static implicit operator Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus (string value) { throw null; }
        public static implicit operator Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus? (string value) { throw null; }
        public static bool operator !=(Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus left, Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus right) { throw null; }
        public override string ToString() { throw null; }
    }
    public partial class KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState : System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState>
    {
        public KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState() { }
        public string ActionsRequired { get { throw null; } set { } }
        public string Description { get { throw null; } set { } }
        public Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus? Status { get { throw null; } set { } }
        protected virtual Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState JsonModelCreateCore(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual void JsonModelWriteCore(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        protected virtual Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState PersistableModelCreateCore(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual System.BinaryData PersistableModelWriteCore(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public readonly partial struct ProvisioningState : System.IEquatable<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.ProvisioningState>
    {
        private readonly object _dummy;
        private readonly int _dummyPrimitive;
        public ProvisioningState(string value) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.ProvisioningState Canceled { get { throw null; } }
        public static Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.ProvisioningState Creating { get { throw null; } }
        public static Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.ProvisioningState Deleting { get { throw null; } }
        public static Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.ProvisioningState Failed { get { throw null; } }
        public static Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.ProvisioningState Succeeded { get { throw null; } }
        public static Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.ProvisioningState Updating { get { throw null; } }
        public bool Equals(Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.ProvisioningState other) { throw null; }
        public override bool Equals(object obj) { throw null; }
        public override int GetHashCode() { throw null; }
        public static bool operator ==(Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.ProvisioningState left, Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.ProvisioningState right) { throw null; }
        public static implicit operator Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.ProvisioningState (string value) { throw null; }
        public static implicit operator Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.ProvisioningState? (string value) { throw null; }
        public static bool operator !=(Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.ProvisioningState left, Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.ProvisioningState right) { throw null; }
        public override string ToString() { throw null; }
    }
    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public readonly partial struct PublicNetworkAccessType : System.IEquatable<Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.PublicNetworkAccessType>
    {
        private readonly object _dummy;
        private readonly int _dummyPrimitive;
        public PublicNetworkAccessType(string value) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.PublicNetworkAccessType Disabled { get { throw null; } }
        public static Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.PublicNetworkAccessType Enabled { get { throw null; } }
        public bool Equals(Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.PublicNetworkAccessType other) { throw null; }
        public override bool Equals(object obj) { throw null; }
        public override int GetHashCode() { throw null; }
        public static bool operator ==(Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.PublicNetworkAccessType left, Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.PublicNetworkAccessType right) { throw null; }
        public static implicit operator Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.PublicNetworkAccessType (string value) { throw null; }
        public static implicit operator Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.PublicNetworkAccessType? (string value) { throw null; }
        public static bool operator !=(Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.PublicNetworkAccessType left, Azure.ResourceManager.KubernetesConfiguration._PrivateLinkScopes.Models.PublicNetworkAccessType right) { throw null; }
        public override string ToString() { throw null; }
    }
}
