namespace Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes
{
    public partial class AzureResourceManagerKubernetesConfigurationPrivateLinkScopesContext : System.ClientModel.Primitives.ModelReaderWriterContext
    {
        internal AzureResourceManagerKubernetesConfigurationPrivateLinkScopesContext() { }
        public static Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.AzureResourceManagerKubernetesConfigurationPrivateLinkScopesContext Default { get { throw null; } }
        protected override bool TryGetTypeBuilderCore(System.Type type, out System.ClientModel.Primitives.ModelReaderWriterTypeBuilder builder) { throw null; }
    }
    public partial class KubernetesConfigurationPrivateEndpointConnectionCollection : Azure.ResourceManager.ArmCollection, System.Collections.Generic.IAsyncEnumerable<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionResource>, System.Collections.Generic.IEnumerable<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionResource>, System.Collections.IEnumerable
    {
        protected KubernetesConfigurationPrivateEndpointConnectionCollection() { }
        public virtual Azure.ResourceManager.ArmOperation<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionResource> CreateOrUpdate(Azure.WaitUntil waitUntil, string privateEndpointConnectionName, Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionData data, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.ResourceManager.ArmOperation<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionResource>> CreateOrUpdateAsync(Azure.WaitUntil waitUntil, string privateEndpointConnectionName, Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionData data, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Response<bool> Exists(string privateEndpointConnectionName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<bool>> ExistsAsync(string privateEndpointConnectionName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionResource> Get(string privateEndpointConnectionName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Pageable<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionResource> GetAll(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.AsyncPageable<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionResource> GetAllAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionResource>> GetAsync(string privateEndpointConnectionName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.NullableResponse<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionResource> GetIfExists(string privateEndpointConnectionName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.NullableResponse<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionResource>> GetIfExistsAsync(string privateEndpointConnectionName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        System.Collections.Generic.IAsyncEnumerator<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionResource> System.Collections.Generic.IAsyncEnumerable<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionResource>.GetAsyncEnumerator(System.Threading.CancellationToken cancellationToken) { throw null; }
        System.Collections.Generic.IEnumerator<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionResource> System.Collections.Generic.IEnumerable<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionResource>.GetEnumerator() { throw null; }
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() { throw null; }
    }
    public partial class KubernetesConfigurationPrivateEndpointConnectionData : Azure.ResourceManager.Models.ResourceData, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionData>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionData>
    {
        public KubernetesConfigurationPrivateEndpointConnectionData() { }
        public Azure.Core.ResourceIdentifier PrivateEndpointId { get { throw null; } }
        public Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState PrivateLinkServiceConnectionState { get { throw null; } set { } }
        public Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState? ProvisioningState { get { throw null; } }
        protected virtual Azure.ResourceManager.Models.ResourceData JsonModelCreateCore(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected override void JsonModelWriteCore(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        protected virtual Azure.ResourceManager.Models.ResourceData PersistableModelCreateCore(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual System.BinaryData PersistableModelWriteCore(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionData System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionData>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionData>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionData>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionData>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionData>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class KubernetesConfigurationPrivateEndpointConnectionResource : Azure.ResourceManager.ArmResource, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionData>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionData>
    {
        public static readonly Azure.Core.ResourceType ResourceType;
        protected KubernetesConfigurationPrivateEndpointConnectionResource() { }
        public virtual Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionData Data { get { throw null; } }
        public virtual bool HasData { get { throw null; } }
        public static Azure.Core.ResourceIdentifier CreateResourceIdentifier(string subscriptionId, string resourceGroupName, string scopeName, string privateEndpointConnectionName) { throw null; }
        public virtual Azure.ResourceManager.ArmOperation Delete(Azure.WaitUntil waitUntil, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.ResourceManager.ArmOperation> DeleteAsync(Azure.WaitUntil waitUntil, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionResource> Get(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionResource>> GetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionData System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionData>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionData>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionData>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionData>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionData>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        public virtual Azure.ResourceManager.ArmOperation<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionResource> Update(Azure.WaitUntil waitUntil, Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionData data, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.ResourceManager.ArmOperation<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionResource>> UpdateAsync(Azure.WaitUntil waitUntil, Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionData data, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
    }
    public partial class KubernetesConfigurationPrivateLinkResource : Azure.ResourceManager.ArmResource, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResourceData>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResourceData>
    {
        public static readonly Azure.Core.ResourceType ResourceType;
        protected KubernetesConfigurationPrivateLinkResource() { }
        public virtual Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResourceData Data { get { throw null; } }
        public virtual bool HasData { get { throw null; } }
        public static Azure.Core.ResourceIdentifier CreateResourceIdentifier(string subscriptionId, string resourceGroupName, string scopeName, string groupName) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResource> Get(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResource>> GetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResourceData System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResourceData>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResourceData>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResourceData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResourceData>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResourceData>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResourceData>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class KubernetesConfigurationPrivateLinkResourceCollection : Azure.ResourceManager.ArmCollection, System.Collections.Generic.IAsyncEnumerable<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResource>, System.Collections.Generic.IEnumerable<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResource>, System.Collections.IEnumerable
    {
        protected KubernetesConfigurationPrivateLinkResourceCollection() { }
        public virtual Azure.Response<bool> Exists(string groupName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<bool>> ExistsAsync(string groupName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResource> Get(string groupName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Pageable<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResource> GetAll(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.AsyncPageable<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResource> GetAllAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResource>> GetAsync(string groupName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.NullableResponse<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResource> GetIfExists(string groupName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.NullableResponse<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResource>> GetIfExistsAsync(string groupName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        System.Collections.Generic.IAsyncEnumerator<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResource> System.Collections.Generic.IAsyncEnumerable<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResource>.GetAsyncEnumerator(System.Threading.CancellationToken cancellationToken) { throw null; }
        System.Collections.Generic.IEnumerator<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResource> System.Collections.Generic.IEnumerable<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResource>.GetEnumerator() { throw null; }
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() { throw null; }
    }
    public partial class KubernetesConfigurationPrivateLinkResourceData : Azure.ResourceManager.Models.ResourceData, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResourceData>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResourceData>
    {
        internal KubernetesConfigurationPrivateLinkResourceData() { }
        public string GroupId { get { throw null; } }
        public System.Collections.Generic.IReadOnlyList<string> RequiredMembers { get { throw null; } }
        public System.Collections.Generic.IList<string> RequiredZoneNames { get { throw null; } }
        protected virtual Azure.ResourceManager.Models.ResourceData JsonModelCreateCore(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected override void JsonModelWriteCore(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        protected virtual Azure.ResourceManager.Models.ResourceData PersistableModelCreateCore(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual System.BinaryData PersistableModelWriteCore(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResourceData System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResourceData>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResourceData>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResourceData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResourceData>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResourceData>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResourceData>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class KubernetesConfigurationPrivateLinkScopeCollection : Azure.ResourceManager.ArmCollection, System.Collections.Generic.IAsyncEnumerable<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>, System.Collections.Generic.IEnumerable<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>, System.Collections.IEnumerable
    {
        protected KubernetesConfigurationPrivateLinkScopeCollection() { }
        public virtual Azure.ResourceManager.ArmOperation<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> CreateOrUpdate(Azure.WaitUntil waitUntil, string scopeName, Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData data, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.ResourceManager.ArmOperation<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>> CreateOrUpdateAsync(Azure.WaitUntil waitUntil, string scopeName, Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData data, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Response<bool> Exists(string scopeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<bool>> ExistsAsync(string scopeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> Get(string scopeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Pageable<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> GetAll(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.AsyncPageable<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> GetAllAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>> GetAsync(string scopeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.NullableResponse<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> GetIfExists(string scopeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.NullableResponse<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>> GetIfExistsAsync(string scopeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        System.Collections.Generic.IAsyncEnumerator<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> System.Collections.Generic.IAsyncEnumerable<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>.GetAsyncEnumerator(System.Threading.CancellationToken cancellationToken) { throw null; }
        System.Collections.Generic.IEnumerator<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> System.Collections.Generic.IEnumerable<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>.GetEnumerator() { throw null; }
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() { throw null; }
    }
    public partial class KubernetesConfigurationPrivateLinkScopeData : Azure.ResourceManager.Models.TrackedResourceData, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>
    {
        public KubernetesConfigurationPrivateLinkScopeData(Azure.Core.AzureLocation location) { }
        public Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties Properties { get { throw null; } set { } }
        protected virtual Azure.ResourceManager.Models.ResourceData JsonModelCreateCore(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected override void JsonModelWriteCore(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        protected virtual Azure.ResourceManager.Models.ResourceData PersistableModelCreateCore(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual System.BinaryData PersistableModelWriteCore(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class KubernetesConfigurationPrivateLinkScopeResource : Azure.ResourceManager.ArmResource, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>
    {
        public static readonly Azure.Core.ResourceType ResourceType;
        protected KubernetesConfigurationPrivateLinkScopeResource() { }
        public virtual Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData Data { get { throw null; } }
        public virtual bool HasData { get { throw null; } }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> AddTag(string key, string value, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>> AddTagAsync(string key, string value, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public static Azure.Core.ResourceIdentifier CreateResourceIdentifier(string subscriptionId, string resourceGroupName, string scopeName) { throw null; }
        public virtual Azure.ResourceManager.ArmOperation Delete(Azure.WaitUntil waitUntil, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.ResourceManager.ArmOperation> DeleteAsync(Azure.WaitUntil waitUntil, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> Get(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>> GetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionResource> GetKubernetesConfigurationPrivateEndpointConnection(string privateEndpointConnectionName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionResource>> GetKubernetesConfigurationPrivateEndpointConnectionAsync(string privateEndpointConnectionName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionCollection GetKubernetesConfigurationPrivateEndpointConnections() { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResource> GetKubernetesConfigurationPrivateLinkResource(string groupName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResource>> GetKubernetesConfigurationPrivateLinkResourceAsync(string groupName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResourceCollection GetKubernetesConfigurationPrivateLinkResources() { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> RemoveTag(string key, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>> RemoveTagAsync(string key, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> SetTags(System.Collections.Generic.IDictionary<string, string> tags, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>> SetTagsAsync(System.Collections.Generic.IDictionary<string, string> tags, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> Update(Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch patch, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>> UpdateAsync(Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch patch, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
    }
    public static partial class KubernetesConfigurationPrivateLinkScopesExtensions
    {
        public static Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionResource GetKubernetesConfigurationPrivateEndpointConnectionResource(this Azure.ResourceManager.ArmClient client, Azure.Core.ResourceIdentifier id) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResource GetKubernetesConfigurationPrivateLinkResource(this Azure.ResourceManager.ArmClient client, Azure.Core.ResourceIdentifier id) { throw null; }
        public static Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> GetKubernetesConfigurationPrivateLinkScope(this Azure.ResourceManager.Resources.ResourceGroupResource resourceGroupResource, string scopeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public static System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>> GetKubernetesConfigurationPrivateLinkScopeAsync(this Azure.ResourceManager.Resources.ResourceGroupResource resourceGroupResource, string scopeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource GetKubernetesConfigurationPrivateLinkScopeResource(this Azure.ResourceManager.ArmClient client, Azure.Core.ResourceIdentifier id) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeCollection GetKubernetesConfigurationPrivateLinkScopes(this Azure.ResourceManager.Resources.ResourceGroupResource resourceGroupResource) { throw null; }
        public static Azure.Pageable<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> GetKubernetesConfigurationPrivateLinkScopes(this Azure.ResourceManager.Resources.SubscriptionResource subscriptionResource, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public static Azure.AsyncPageable<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> GetKubernetesConfigurationPrivateLinkScopesAsync(this Azure.ResourceManager.Resources.SubscriptionResource subscriptionResource, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
    }
}
namespace Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Mocking
{
    public partial class MockableKubernetesConfigurationPrivateLinkScopesArmClient : Azure.ResourceManager.ArmResource
    {
        protected MockableKubernetesConfigurationPrivateLinkScopesArmClient() { }
        public virtual Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionResource GetKubernetesConfigurationPrivateEndpointConnectionResource(Azure.Core.ResourceIdentifier id) { throw null; }
        public virtual Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResource GetKubernetesConfigurationPrivateLinkResource(Azure.Core.ResourceIdentifier id) { throw null; }
        public virtual Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource GetKubernetesConfigurationPrivateLinkScopeResource(Azure.Core.ResourceIdentifier id) { throw null; }
    }
    public partial class MockableKubernetesConfigurationPrivateLinkScopesResourceGroupResource : Azure.ResourceManager.ArmResource
    {
        protected MockableKubernetesConfigurationPrivateLinkScopesResourceGroupResource() { }
        public virtual Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> GetKubernetesConfigurationPrivateLinkScope(string scopeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource>> GetKubernetesConfigurationPrivateLinkScopeAsync(string scopeName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeCollection GetKubernetesConfigurationPrivateLinkScopes() { throw null; }
    }
    public partial class MockableKubernetesConfigurationPrivateLinkScopesSubscriptionResource : Azure.ResourceManager.ArmResource
    {
        protected MockableKubernetesConfigurationPrivateLinkScopesSubscriptionResource() { }
        public virtual Azure.Pageable<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> GetKubernetesConfigurationPrivateLinkScopes(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.AsyncPageable<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeResource> GetKubernetesConfigurationPrivateLinkScopesAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
    }
}
namespace Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models
{
    public static partial class ArmKubernetesConfigurationPrivateLinkScopesModelFactory
    {
        public static Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionData KubernetesConfigurationPrivateEndpointConnectionData(Azure.Core.ResourceIdentifier id = null, string name = null, Azure.Core.ResourceType resourceType = default(Azure.Core.ResourceType), Azure.ResourceManager.Models.SystemData systemData = null, Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState privateLinkServiceConnectionState = null, Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState? provisioningState = default(Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState?), Azure.Core.ResourceIdentifier privateEndpointId = null) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkResourceData KubernetesConfigurationPrivateLinkResourceData(Azure.Core.ResourceIdentifier id = null, string name = null, Azure.Core.ResourceType resourceType = default(Azure.Core.ResourceType), Azure.ResourceManager.Models.SystemData systemData = null, string groupId = null, System.Collections.Generic.IEnumerable<string> requiredMembers = null, System.Collections.Generic.IEnumerable<string> requiredZoneNames = null) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateLinkScopeData KubernetesConfigurationPrivateLinkScopeData(Azure.Core.ResourceIdentifier id = null, string name = null, Azure.Core.ResourceType resourceType = default(Azure.Core.ResourceType), Azure.ResourceManager.Models.SystemData systemData = null, System.Collections.Generic.IDictionary<string, string> tags = null, Azure.Core.AzureLocation location = default(Azure.Core.AzureLocation), Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties properties = null) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch KubernetesConfigurationPrivateLinkScopePatch(System.Collections.Generic.IDictionary<string, string> tags = null) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties KubernetesConfigurationPrivateLinkScopeProperties(Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePublicNetworkAccessType? publicNetworkAccess = default(Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePublicNetworkAccessType?), Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProvisioningState? provisioningState = default(Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProvisioningState?), Azure.Core.ResourceIdentifier clusterResourceId = null, System.Guid? privateLinkScopeId = default(System.Guid?), System.Collections.Generic.IEnumerable<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionData> privateEndpointConnections = null) { throw null; }
    }
    public partial class KubernetesConfigurationPrivateLinkScopePatch : System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch>
    {
        public KubernetesConfigurationPrivateLinkScopePatch() { }
        public System.Collections.Generic.IDictionary<string, string> Tags { get { throw null; } }
        protected virtual Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch JsonModelCreateCore(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual void JsonModelWriteCore(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        protected virtual Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch PersistableModelCreateCore(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual System.BinaryData PersistableModelWriteCore(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePatch>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class KubernetesConfigurationPrivateLinkScopeProperties : System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties>
    {
        public KubernetesConfigurationPrivateLinkScopeProperties(Azure.Core.ResourceIdentifier clusterResourceId) { }
        public Azure.Core.ResourceIdentifier ClusterResourceId { get { throw null; } set { } }
        public System.Collections.Generic.IReadOnlyList<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.KubernetesConfigurationPrivateEndpointConnectionData> PrivateEndpointConnections { get { throw null; } }
        public System.Guid? PrivateLinkScopeId { get { throw null; } }
        public Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProvisioningState? ProvisioningState { get { throw null; } }
        public Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePublicNetworkAccessType? PublicNetworkAccess { get { throw null; } set { } }
        protected virtual Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties JsonModelCreateCore(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual void JsonModelWriteCore(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        protected virtual Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties PersistableModelCreateCore(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual System.BinaryData PersistableModelWriteCore(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProperties>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public readonly partial struct KubernetesConfigurationPrivateLinkScopeProvisioningState : System.IEquatable<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProvisioningState>
    {
        private readonly object _dummy;
        private readonly int _dummyPrimitive;
        public KubernetesConfigurationPrivateLinkScopeProvisioningState(string value) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProvisioningState Canceled { get { throw null; } }
        public static Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProvisioningState Creating { get { throw null; } }
        public static Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProvisioningState Deleting { get { throw null; } }
        public static Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProvisioningState Failed { get { throw null; } }
        public static Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProvisioningState Succeeded { get { throw null; } }
        public static Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProvisioningState Updating { get { throw null; } }
        public bool Equals(Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProvisioningState other) { throw null; }
        public override bool Equals(object obj) { throw null; }
        public override int GetHashCode() { throw null; }
        public static bool operator ==(Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProvisioningState left, Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProvisioningState right) { throw null; }
        public static implicit operator Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProvisioningState (string value) { throw null; }
        public static implicit operator Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProvisioningState? (string value) { throw null; }
        public static bool operator !=(Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProvisioningState left, Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopeProvisioningState right) { throw null; }
        public override string ToString() { throw null; }
    }
    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public readonly partial struct KubernetesConfigurationPrivateLinkScopePublicNetworkAccessType : System.IEquatable<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePublicNetworkAccessType>
    {
        private readonly object _dummy;
        private readonly int _dummyPrimitive;
        public KubernetesConfigurationPrivateLinkScopePublicNetworkAccessType(string value) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePublicNetworkAccessType Disabled { get { throw null; } }
        public static Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePublicNetworkAccessType Enabled { get { throw null; } }
        public bool Equals(Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePublicNetworkAccessType other) { throw null; }
        public override bool Equals(object obj) { throw null; }
        public override int GetHashCode() { throw null; }
        public static bool operator ==(Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePublicNetworkAccessType left, Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePublicNetworkAccessType right) { throw null; }
        public static implicit operator Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePublicNetworkAccessType (string value) { throw null; }
        public static implicit operator Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePublicNetworkAccessType? (string value) { throw null; }
        public static bool operator !=(Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePublicNetworkAccessType left, Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopePublicNetworkAccessType right) { throw null; }
        public override string ToString() { throw null; }
    }
    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public readonly partial struct KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState : System.IEquatable<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState>
    {
        private readonly object _dummy;
        private readonly int _dummyPrimitive;
        public KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState(string value) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState Creating { get { throw null; } }
        public static Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState Deleting { get { throw null; } }
        public static Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState Failed { get { throw null; } }
        public static Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState Succeeded { get { throw null; } }
        public bool Equals(Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState other) { throw null; }
        public override bool Equals(object obj) { throw null; }
        public override int GetHashCode() { throw null; }
        public static bool operator ==(Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState left, Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState right) { throw null; }
        public static implicit operator Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState (string value) { throw null; }
        public static implicit operator Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState? (string value) { throw null; }
        public static bool operator !=(Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState left, Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointConnectionProvisioningState right) { throw null; }
        public override string ToString() { throw null; }
    }
    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public readonly partial struct KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus : System.IEquatable<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus>
    {
        private readonly object _dummy;
        private readonly int _dummyPrimitive;
        public KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus(string value) { throw null; }
        public static Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus Approved { get { throw null; } }
        public static Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus Pending { get { throw null; } }
        public static Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus Rejected { get { throw null; } }
        public bool Equals(Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus other) { throw null; }
        public override bool Equals(object obj) { throw null; }
        public override int GetHashCode() { throw null; }
        public static bool operator ==(Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus left, Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus right) { throw null; }
        public static implicit operator Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus (string value) { throw null; }
        public static implicit operator Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus? (string value) { throw null; }
        public static bool operator !=(Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus left, Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus right) { throw null; }
        public override string ToString() { throw null; }
    }
    public partial class KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState : System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState>
    {
        public KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState() { }
        public string ActionsRequired { get { throw null; } set { } }
        public string Description { get { throw null; } set { } }
        public Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateEndpointServiceConnectionStatus? Status { get { throw null; } set { } }
        protected virtual Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState JsonModelCreateCore(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual void JsonModelWriteCore(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        protected virtual Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState PersistableModelCreateCore(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        protected virtual System.BinaryData PersistableModelWriteCore(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.KubernetesConfiguration.PrivateLinkScopes.Models.KubernetesConfigurationPrivateLinkScopesPrivateLinkServiceConnectionState>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
}
