// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// Hand-written: these items derive from OpenAI.Responses.ResponseItem, whose only
// accessible constructor is `protected internal ResponseItem(ResponseItemKind)`. The
// emitter cannot produce a subclass that also forwards this package's Azure attribution
// fields, so the type is maintained here and mapped away in client.tsp via @@alternateType.
// The attribution fields are carried over JsonPatch, as they are for every other item type.

#nullable disable

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using Azure.AI.Extensions.OpenAI;
using OpenAI.Responses;

namespace Azure.AI.AgentServer.Responses.Models
{
    /// <summary> ResponseCustomToolCallOutputItem. </summary>
    [Experimental("AAIP002")]
    public partial class OutputItemCustomToolCallOutput : ResponseItem
    {
        /// <summary> Keeps track of any properties unknown to the library. </summary>
        private protected readonly IDictionary<string, BinaryData> _additionalBinaryDataProperties;

        /// <summary> Initializes a new instance of <see cref="OutputItemCustomToolCallOutput"/>. </summary>
        /// <param name="callId"> The call ID, used to map this custom tool call output to a custom tool call. </param>
        /// <param name="output">
        /// The output from the custom tool call generated by your code.
        ///   Can be a string or an list of output content.
        /// </param>
        /// <param name="status">
        /// The status of the item. One of `in_progress`, `completed`, or
        ///   `incomplete`. Populated when items are returned via API.
        /// </param>
        internal OutputItemCustomToolCallOutput(string callId, BinaryData output, FunctionCallOutputStatusEnum status) : base("custom_tool_call_output")
        {
            CallId = callId;
            Output = output;
            Status = status;
        }

        /// <summary> Initializes a new instance of <see cref="OutputItemCustomToolCallOutput"/>. </summary>
        /// <param name="type"></param>
        /// <param name="createdBy"> The information about the creator of the item. </param>
        /// <param name="agentReference"> The agent that created the item. </param>
        /// <param name="responseId"> The response on which the item is created. </param>
        /// <param name="id"> The unique ID of the custom tool call output in the OpenAI platform. </param>
        /// <param name="callId"> The call ID, used to map this custom tool call output to a custom tool call. </param>
        /// <param name="output">
        /// The output from the custom tool call generated by your code.
        ///   Can be a string or an list of output content.
        /// </param>
        /// <param name="status">
        /// The status of the item. One of `in_progress`, `completed`, or
        ///   `incomplete`. Populated when items are returned via API.
        /// </param>
        /// <param name="additionalBinaryDataProperties"> Keeps track of any properties unknown to the library. </param>
        internal OutputItemCustomToolCallOutput(ResponseItemKind @type, string id, string callId, BinaryData output, FunctionCallOutputStatusEnum status, IDictionary<string, BinaryData> additionalBinaryDataProperties) : base(@type)
        {
            Id = id;
            CallId = callId;
            Output = output;
            Status = status;
            _additionalBinaryDataProperties = additionalBinaryDataProperties;
        }

        /// <summary> The call ID, used to map this custom tool call output to a custom tool call. </summary>
        public string CallId { get; }

        /// <summary>
        /// The output from the custom tool call generated by your code.
        ///   Can be a string or an list of output content.
        /// <para> To assign an object to this property use <see cref="BinaryData.FromObjectAsJson{T}(T, JsonSerializerOptions?)"/>. </para>
        /// <para> To assign an already formatted json string to this property use <see cref="BinaryData.FromString(string)"/>. </para>
        /// <para>
        /// <remarks>
        /// Supported types:
        /// <list type="bullet">
        /// <item>
        /// <description> <see cref="string"/>. </description>
        /// </item>
        /// <item>
        /// <description> <see cref="IList{T}"/> where <c>T</c> is of type <see cref="FunctionAndCustomToolCallOutput"/>. </description>
        /// </item>
        /// </list>
        /// </remarks>
        /// </para>
        /// <para>
        /// Examples:
        /// <list type="bullet">
        /// <item>
        /// <term> BinaryData.FromObjectAsJson("foo"). </term>
        /// <description> Creates a payload of "foo". </description>
        /// </item>
        /// <item>
        /// <term> BinaryData.FromString("\"foo\""). </term>
        /// <description> Creates a payload of "foo". </description>
        /// </item>
        /// <item>
        /// <term> BinaryData.FromObjectAsJson(new { key = "value" }). </term>
        /// <description> Creates a payload of { "key": "value" }. </description>
        /// </item>
        /// <item>
        /// <term> BinaryData.FromString("{\"key\": \"value\"}"). </term>
        /// <description> Creates a payload of { "key": "value" }. </description>
        /// </item>
        /// </list>
        /// </para>
        /// </summary>
        public BinaryData Output { get; }

        /// <summary>
        /// The status of the item. One of `in_progress`, `completed`, or
        ///   `incomplete`. Populated when items are returned via API.
        /// </summary>
        public FunctionCallOutputStatusEnum Status { get; }
    }
}
