namespace Azure.ResourceManager.CarbonOptimization
{
    public static partial class CarbonOptimizationExtensions
    {
        public static Azure.Pageable<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmission> GetCarbonEmissionReports(this Azure.ResourceManager.Resources.TenantResource tenantResource, Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryContent content, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public static Azure.AsyncPageable<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmission> GetCarbonEmissionReportsAsync(this Azure.ResourceManager.Resources.TenantResource tenantResource, Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryContent content, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public static Azure.Response<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionAvailableDateRange> QueryCarbonEmissionAvailableDateRange(this Azure.ResourceManager.Resources.TenantResource tenantResource, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public static System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionAvailableDateRange>> QueryCarbonEmissionAvailableDateRangeAsync(this Azure.ResourceManager.Resources.TenantResource tenantResource, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
    }
}
namespace Azure.ResourceManager.CarbonOptimization.Mocking
{
    public partial class MockableCarbonOptimizationTenantResource : Azure.ResourceManager.ArmResource
    {
        protected MockableCarbonOptimizationTenantResource() { }
        public virtual Azure.Pageable<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmission> GetCarbonEmissionReports(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryContent content, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.AsyncPageable<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmission> GetCarbonEmissionReportsAsync(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryContent content, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual Azure.Response<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionAvailableDateRange> QueryCarbonEmissionAvailableDateRange(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionAvailableDateRange>> QueryCarbonEmissionAvailableDateRangeAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) { throw null; }
    }
}
namespace Azure.ResourceManager.CarbonOptimization.Models
{
    public static partial class ArmCarbonOptimizationModelFactory
    {
        public static Azure.ResourceManager.CarbonOptimization.Models.CarbonEmission CarbonEmission(string dataType = null, double totalCarbonEmission = 0, double totalCarbonEmissionLastMonth = 0, double changeRatioForLastMonth = 0, double totalCarbonEmission12MonthsAgo = 0, double changeRatioFor12Months = 0, double? changeValueMonthOverMonth = default(double?)) { throw null; }
        public static Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionAvailableDateRange CarbonEmissionAvailableDateRange(System.DateTimeOffset startOn = default(System.DateTimeOffset), System.DateTimeOffset endOn = default(System.DateTimeOffset)) { throw null; }
        public static Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionItemDetail CarbonEmissionItemDetail(double totalCarbonEmission = 0, double totalCarbonEmissionLastMonth = 0, double changeRatioForLastMonth = 0, double totalCarbonEmission12MonthsAgo = 0, double changeRatioFor12Months = 0, double? changeValueMonthOverMonth = default(double?), string itemName = null, string groupName = null, Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType categoryType = default(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType)) { throw null; }
        public static Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionMonthlySummary CarbonEmissionMonthlySummary(double totalCarbonEmission = 0, double totalCarbonEmissionLastMonth = 0, double changeRatioForLastMonth = 0, double totalCarbonEmission12MonthsAgo = 0, double changeRatioFor12Months = 0, double? changeValueMonthOverMonth = default(double?), string date = null, double carbonIntensity = 0) { throw null; }
        public static Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionOverallSummary CarbonEmissionOverallSummary(double totalCarbonEmission = 0, double totalCarbonEmissionLastMonth = 0, double changeRatioForLastMonth = 0, double totalCarbonEmission12MonthsAgo = 0, double changeRatioFor12Months = 0, double? changeValueMonthOverMonth = default(double?)) { throw null; }
        public static Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryContent CarbonEmissionQueryContent(string reportType = null, Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryDateRange dateRange = null, System.Collections.Generic.IEnumerable<string> subscriptionList = null, System.Collections.Generic.IEnumerable<string> resourceGroupUrlList = null, System.Collections.Generic.IEnumerable<string> resourceTypeList = null, System.Collections.Generic.IEnumerable<string> locationList = null, System.Collections.Generic.IEnumerable<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope> carbonScopeList = null) { throw null; }
        public static Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionTopItemMonthlySummary CarbonEmissionTopItemMonthlySummary(double totalCarbonEmission = 0, double totalCarbonEmissionLastMonth = 0, double changeRatioForLastMonth = 0, double totalCarbonEmission12MonthsAgo = 0, double changeRatioFor12Months = 0, double? changeValueMonthOverMonth = default(double?), string itemName = null, Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType categoryType = default(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType), string date = null) { throw null; }
        public static Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionTopItemsSummary CarbonEmissionTopItemsSummary(double totalCarbonEmission = 0, double totalCarbonEmissionLastMonth = 0, double changeRatioForLastMonth = 0, double totalCarbonEmission12MonthsAgo = 0, double changeRatioFor12Months = 0, double? changeValueMonthOverMonth = default(double?), string itemName = null, Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType categoryType = default(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType)) { throw null; }
        public static Azure.ResourceManager.CarbonOptimization.Models.ItemDetailsQueryContent ItemDetailsQueryContent(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryDateRange dateRange = null, System.Collections.Generic.IEnumerable<string> subscriptionList = null, System.Collections.Generic.IEnumerable<string> resourceGroupUrlList = null, System.Collections.Generic.IEnumerable<string> resourceTypeList = null, System.Collections.Generic.IEnumerable<string> locationList = null, System.Collections.Generic.IEnumerable<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope> carbonScopeList = null, Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType categoryType = default(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType), string orderBy = null, string sortDirection = null, string groupCategory = null, int pageSize = 0, string skipToken = null) { throw null; }
        public static Azure.ResourceManager.CarbonOptimization.Models.MonthlySummaryReportQueryContent MonthlySummaryReportQueryContent(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryDateRange dateRange = null, System.Collections.Generic.IEnumerable<string> subscriptionList = null, System.Collections.Generic.IEnumerable<string> resourceGroupUrlList = null, System.Collections.Generic.IEnumerable<string> resourceTypeList = null, System.Collections.Generic.IEnumerable<string> locationList = null, System.Collections.Generic.IEnumerable<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope> carbonScopeList = null) { throw null; }
        public static Azure.ResourceManager.CarbonOptimization.Models.OverallSummaryReportQueryContent OverallSummaryReportQueryContent(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryDateRange dateRange = null, System.Collections.Generic.IEnumerable<string> subscriptionList = null, System.Collections.Generic.IEnumerable<string> resourceGroupUrlList = null, System.Collections.Generic.IEnumerable<string> resourceTypeList = null, System.Collections.Generic.IEnumerable<string> locationList = null, System.Collections.Generic.IEnumerable<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope> carbonScopeList = null) { throw null; }
        public static Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionItemDetail ResourceCarbonEmissionItemDetail(double totalCarbonEmission = 0, double totalCarbonEmissionLastMonth = 0, double changeRatioForLastMonth = 0, double totalCarbonEmission12MonthsAgo = 0, double changeRatioFor12Months = 0, double? changeValueMonthOverMonth = default(double?), string itemName = null, string groupName = null, Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType categoryType = default(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType), string subscriptionId = null, string resourceGroup = null, Azure.Core.ResourceIdentifier resourceId = null, Azure.Core.AzureLocation? location = default(Azure.Core.AzureLocation?), Azure.Core.ResourceType? resourceType = default(Azure.Core.ResourceType?), string resourceTypeFriendlyName = null, string resourceProvider = null) { throw null; }
        public static Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionTopItemMonthlySummary ResourceCarbonEmissionTopItemMonthlySummary(double totalCarbonEmission = 0, double totalCarbonEmissionLastMonth = 0, double changeRatioForLastMonth = 0, double totalCarbonEmission12MonthsAgo = 0, double changeRatioFor12Months = 0, double? changeValueMonthOverMonth = default(double?), string itemName = null, Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType categoryType = default(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType), string date = null, string subscriptionId = null, string resourceGroup = null) { throw null; }
        public static Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionTopItemsSummary ResourceCarbonEmissionTopItemsSummary(double totalCarbonEmission = 0, double totalCarbonEmissionLastMonth = 0, double changeRatioForLastMonth = 0, double totalCarbonEmission12MonthsAgo = 0, double changeRatioFor12Months = 0, double? changeValueMonthOverMonth = default(double?), string itemName = null, Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType categoryType = default(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType), string subscriptionId = null, string resourceGroup = null) { throw null; }
        public static Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionItemDetail ResourceGroupCarbonEmissionItemDetail(double totalCarbonEmission = 0, double totalCarbonEmissionLastMonth = 0, double changeRatioForLastMonth = 0, double totalCarbonEmission12MonthsAgo = 0, double changeRatioFor12Months = 0, double? changeValueMonthOverMonth = default(double?), string itemName = null, string groupName = null, Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType categoryType = default(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType), string subscriptionId = null) { throw null; }
        public static Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionTopItemMonthlySummary ResourceGroupCarbonEmissionTopItemMonthlySummary(double totalCarbonEmission = 0, double totalCarbonEmissionLastMonth = 0, double changeRatioForLastMonth = 0, double totalCarbonEmission12MonthsAgo = 0, double changeRatioFor12Months = 0, double? changeValueMonthOverMonth = default(double?), string itemName = null, Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType categoryType = default(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType), string date = null, string subscriptionId = null) { throw null; }
        public static Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionTopItemsSummary ResourceGroupCarbonEmissionTopItemsSummary(double totalCarbonEmission = 0, double totalCarbonEmissionLastMonth = 0, double changeRatioForLastMonth = 0, double totalCarbonEmission12MonthsAgo = 0, double changeRatioFor12Months = 0, double? changeValueMonthOverMonth = default(double?), string itemName = null, Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType categoryType = default(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType), string subscriptionId = null) { throw null; }
        public static Azure.ResourceManager.CarbonOptimization.Models.ResourceTypeCarbonEmissionItemDetail ResourceTypeCarbonEmissionItemDetail(double totalCarbonEmission = 0, double totalCarbonEmissionLastMonth = 0, double changeRatioForLastMonth = 0, double totalCarbonEmission12MonthsAgo = 0, double changeRatioFor12Months = 0, double? changeValueMonthOverMonth = default(double?), string itemName = null, string resourceTypeFriendlyName = null, Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType categoryType = default(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType)) { throw null; }
        public static Azure.ResourceManager.CarbonOptimization.Models.TopItemsMonthlySummaryReportQueryContent TopItemsMonthlySummaryReportQueryContent(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryDateRange dateRange = null, System.Collections.Generic.IEnumerable<string> subscriptionList = null, System.Collections.Generic.IEnumerable<string> resourceGroupUrlList = null, System.Collections.Generic.IEnumerable<string> resourceTypeList = null, System.Collections.Generic.IEnumerable<string> locationList = null, System.Collections.Generic.IEnumerable<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope> carbonScopeList = null, Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType categoryType = default(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType), int topItems = 0) { throw null; }
        public static Azure.ResourceManager.CarbonOptimization.Models.TopItemsSummaryReportQueryContent TopItemsSummaryReportQueryContent(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryDateRange dateRange = null, System.Collections.Generic.IEnumerable<string> subscriptionList = null, System.Collections.Generic.IEnumerable<string> resourceGroupUrlList = null, System.Collections.Generic.IEnumerable<string> resourceTypeList = null, System.Collections.Generic.IEnumerable<string> locationList = null, System.Collections.Generic.IEnumerable<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope> carbonScopeList = null, Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType categoryType = default(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType), int topItems = 0) { throw null; }
    }
    public abstract partial class CarbonEmission : System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmission>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmission>
    {
        protected CarbonEmission(double totalCarbonEmission, double totalCarbonEmissionLastMonth, double changeRatioForLastMonth, double totalCarbonEmission12MonthsAgo, double changeRatioFor12Months) { }
        public double ChangeRatioFor12Months { get { throw null; } }
        public double ChangeRatioForLastMonth { get { throw null; } }
        public double? ChangeValueMonthOverMonth { get { throw null; } }
        public double TotalCarbonEmission { get { throw null; } }
        public double TotalCarbonEmission12MonthsAgo { get { throw null; } }
        public double TotalCarbonEmissionLastMonth { get { throw null; } }
        Azure.ResourceManager.CarbonOptimization.Models.CarbonEmission System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmission>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmission>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.CarbonOptimization.Models.CarbonEmission System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmission>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmission>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmission>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class CarbonEmissionAvailableDateRange : System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionAvailableDateRange>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionAvailableDateRange>
    {
        internal CarbonEmissionAvailableDateRange() { }
        public System.DateTimeOffset EndOn { get { throw null; } }
        public System.DateTimeOffset StartOn { get { throw null; } }
        Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionAvailableDateRange System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionAvailableDateRange>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionAvailableDateRange>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionAvailableDateRange System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionAvailableDateRange>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionAvailableDateRange>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionAvailableDateRange>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public readonly partial struct CarbonEmissionCategoryType : System.IEquatable<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType>
    {
        private readonly object _dummy;
        private readonly int _dummyPrimitive;
        public CarbonEmissionCategoryType(string value) { throw null; }
        public static Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType Location { get { throw null; } }
        public static Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType Resource { get { throw null; } }
        public static Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType ResourceGroup { get { throw null; } }
        public static Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType ResourceType { get { throw null; } }
        public static Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType ServiceType { get { throw null; } }
        public static Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType Subscription { get { throw null; } }
        public bool Equals(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType other) { throw null; }
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override bool Equals(object obj) { throw null; }
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override int GetHashCode() { throw null; }
        public static bool operator ==(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType left, Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType right) { throw null; }
        public static implicit operator Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType (string value) { throw null; }
        public static bool operator !=(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType left, Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType right) { throw null; }
        public override string ToString() { throw null; }
    }
    public partial class CarbonEmissionItemDetail : Azure.ResourceManager.CarbonOptimization.Models.CarbonEmission, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionItemDetail>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionItemDetail>
    {
        internal CarbonEmissionItemDetail() : base (default(double), default(double), default(double), default(double), default(double)) { }
        public Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType CategoryType { get { throw null; } }
        public string GroupName { get { throw null; } }
        public string ItemName { get { throw null; } }
        Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionItemDetail System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionItemDetail>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionItemDetail>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionItemDetail System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionItemDetail>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionItemDetail>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionItemDetail>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class CarbonEmissionMonthlySummary : Azure.ResourceManager.CarbonOptimization.Models.CarbonEmission, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionMonthlySummary>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionMonthlySummary>
    {
        internal CarbonEmissionMonthlySummary() : base (default(double), default(double), default(double), default(double), default(double)) { }
        public double CarbonIntensity { get { throw null; } }
        public string Date { get { throw null; } }
        Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionMonthlySummary System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionMonthlySummary>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionMonthlySummary>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionMonthlySummary System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionMonthlySummary>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionMonthlySummary>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionMonthlySummary>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class CarbonEmissionOverallSummary : Azure.ResourceManager.CarbonOptimization.Models.CarbonEmission, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionOverallSummary>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionOverallSummary>
    {
        internal CarbonEmissionOverallSummary() : base (default(double), default(double), default(double), default(double), default(double)) { }
        Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionOverallSummary System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionOverallSummary>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionOverallSummary>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionOverallSummary System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionOverallSummary>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionOverallSummary>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionOverallSummary>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public abstract partial class CarbonEmissionQueryContent : System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryContent>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryContent>
    {
        protected CarbonEmissionQueryContent(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryDateRange dateRange, System.Collections.Generic.IEnumerable<string> subscriptionList, System.Collections.Generic.IEnumerable<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope> carbonScopeList) { }
        public System.Collections.Generic.IList<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope> CarbonScopeList { get { throw null; } }
        public Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryDateRange DateRange { get { throw null; } }
        public System.Collections.Generic.IList<string> LocationList { get { throw null; } }
        public System.Collections.Generic.IList<string> ResourceGroupUrlList { get { throw null; } }
        public System.Collections.Generic.IList<string> ResourceTypeList { get { throw null; } }
        public System.Collections.Generic.IList<string> SubscriptionList { get { throw null; } }
        Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryContent System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryContent>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryContent>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryContent System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryContent>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryContent>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryContent>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class CarbonEmissionQueryDateRange : System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryDateRange>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryDateRange>
    {
        public CarbonEmissionQueryDateRange(System.DateTimeOffset startOn, System.DateTimeOffset endOn) { }
        public System.DateTimeOffset EndOn { get { throw null; } }
        public System.DateTimeOffset StartOn { get { throw null; } }
        Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryDateRange System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryDateRange>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryDateRange>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryDateRange System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryDateRange>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryDateRange>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryDateRange>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public readonly partial struct CarbonEmissionQueryScope : System.IEquatable<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope>
    {
        private readonly object _dummy;
        private readonly int _dummyPrimitive;
        public CarbonEmissionQueryScope(string value) { throw null; }
        public static Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope Scope1 { get { throw null; } }
        public static Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope Scope2 { get { throw null; } }
        public static Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope Scope3 { get { throw null; } }
        public bool Equals(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope other) { throw null; }
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override bool Equals(object obj) { throw null; }
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override int GetHashCode() { throw null; }
        public static bool operator ==(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope left, Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope right) { throw null; }
        public static implicit operator Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope (string value) { throw null; }
        public static bool operator !=(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope left, Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope right) { throw null; }
        public override string ToString() { throw null; }
    }
    public partial class CarbonEmissionTopItemMonthlySummary : Azure.ResourceManager.CarbonOptimization.Models.CarbonEmission, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionTopItemMonthlySummary>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionTopItemMonthlySummary>
    {
        internal CarbonEmissionTopItemMonthlySummary() : base (default(double), default(double), default(double), default(double), default(double)) { }
        public Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType CategoryType { get { throw null; } }
        public string Date { get { throw null; } }
        public string ItemName { get { throw null; } }
        Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionTopItemMonthlySummary System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionTopItemMonthlySummary>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionTopItemMonthlySummary>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionTopItemMonthlySummary System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionTopItemMonthlySummary>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionTopItemMonthlySummary>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionTopItemMonthlySummary>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class CarbonEmissionTopItemsSummary : Azure.ResourceManager.CarbonOptimization.Models.CarbonEmission, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionTopItemsSummary>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionTopItemsSummary>
    {
        internal CarbonEmissionTopItemsSummary() : base (default(double), default(double), default(double), default(double), default(double)) { }
        public Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType CategoryType { get { throw null; } }
        public string ItemName { get { throw null; } }
        Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionTopItemsSummary System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionTopItemsSummary>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionTopItemsSummary>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionTopItemsSummary System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionTopItemsSummary>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionTopItemsSummary>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionTopItemsSummary>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class ItemDetailsQueryContent : Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryContent, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.ItemDetailsQueryContent>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ItemDetailsQueryContent>
    {
        public ItemDetailsQueryContent(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryDateRange dateRange, System.Collections.Generic.IEnumerable<string> subscriptionList, System.Collections.Generic.IEnumerable<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope> carbonScopeList, Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType categoryType, string orderBy, string sortDirection, string groupCategory, int pageSize) : base (default(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryDateRange), default(System.Collections.Generic.IEnumerable<string>), default(System.Collections.Generic.IEnumerable<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope>)) { }
        public Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType CategoryType { get { throw null; } }
        public string GroupCategory { get { throw null; } }
        public string OrderBy { get { throw null; } }
        public int PageSize { get { throw null; } }
        public string SkipToken { get { throw null; } set { } }
        public string SortDirection { get { throw null; } }
        Azure.ResourceManager.CarbonOptimization.Models.ItemDetailsQueryContent System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.ItemDetailsQueryContent>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.ItemDetailsQueryContent>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.CarbonOptimization.Models.ItemDetailsQueryContent System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ItemDetailsQueryContent>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ItemDetailsQueryContent>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ItemDetailsQueryContent>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class MonthlySummaryReportQueryContent : Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryContent, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.MonthlySummaryReportQueryContent>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.MonthlySummaryReportQueryContent>
    {
        public MonthlySummaryReportQueryContent(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryDateRange dateRange, System.Collections.Generic.IEnumerable<string> subscriptionList, System.Collections.Generic.IEnumerable<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope> carbonScopeList) : base (default(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryDateRange), default(System.Collections.Generic.IEnumerable<string>), default(System.Collections.Generic.IEnumerable<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope>)) { }
        Azure.ResourceManager.CarbonOptimization.Models.MonthlySummaryReportQueryContent System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.MonthlySummaryReportQueryContent>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.MonthlySummaryReportQueryContent>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.CarbonOptimization.Models.MonthlySummaryReportQueryContent System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.MonthlySummaryReportQueryContent>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.MonthlySummaryReportQueryContent>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.MonthlySummaryReportQueryContent>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class OverallSummaryReportQueryContent : Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryContent, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.OverallSummaryReportQueryContent>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.OverallSummaryReportQueryContent>
    {
        public OverallSummaryReportQueryContent(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryDateRange dateRange, System.Collections.Generic.IEnumerable<string> subscriptionList, System.Collections.Generic.IEnumerable<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope> carbonScopeList) : base (default(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryDateRange), default(System.Collections.Generic.IEnumerable<string>), default(System.Collections.Generic.IEnumerable<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope>)) { }
        Azure.ResourceManager.CarbonOptimization.Models.OverallSummaryReportQueryContent System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.OverallSummaryReportQueryContent>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.OverallSummaryReportQueryContent>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.CarbonOptimization.Models.OverallSummaryReportQueryContent System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.OverallSummaryReportQueryContent>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.OverallSummaryReportQueryContent>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.OverallSummaryReportQueryContent>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class ResourceCarbonEmissionItemDetail : Azure.ResourceManager.CarbonOptimization.Models.CarbonEmission, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionItemDetail>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionItemDetail>
    {
        internal ResourceCarbonEmissionItemDetail() : base (default(double), default(double), default(double), default(double), default(double)) { }
        public Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType CategoryType { get { throw null; } }
        public string GroupName { get { throw null; } }
        public string ItemName { get { throw null; } }
        public Azure.Core.AzureLocation? Location { get { throw null; } }
        public string ResourceGroup { get { throw null; } }
        public Azure.Core.ResourceIdentifier ResourceId { get { throw null; } }
        public string ResourceProvider { get { throw null; } }
        public Azure.Core.ResourceType? ResourceType { get { throw null; } }
        public string ResourceTypeFriendlyName { get { throw null; } }
        public string SubscriptionId { get { throw null; } }
        Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionItemDetail System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionItemDetail>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionItemDetail>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionItemDetail System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionItemDetail>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionItemDetail>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionItemDetail>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class ResourceCarbonEmissionTopItemMonthlySummary : Azure.ResourceManager.CarbonOptimization.Models.CarbonEmission, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionTopItemMonthlySummary>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionTopItemMonthlySummary>
    {
        internal ResourceCarbonEmissionTopItemMonthlySummary() : base (default(double), default(double), default(double), default(double), default(double)) { }
        public Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType CategoryType { get { throw null; } }
        public string Date { get { throw null; } }
        public string ItemName { get { throw null; } }
        public string ResourceGroup { get { throw null; } }
        public string SubscriptionId { get { throw null; } }
        Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionTopItemMonthlySummary System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionTopItemMonthlySummary>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionTopItemMonthlySummary>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionTopItemMonthlySummary System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionTopItemMonthlySummary>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionTopItemMonthlySummary>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionTopItemMonthlySummary>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class ResourceCarbonEmissionTopItemsSummary : Azure.ResourceManager.CarbonOptimization.Models.CarbonEmission, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionTopItemsSummary>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionTopItemsSummary>
    {
        internal ResourceCarbonEmissionTopItemsSummary() : base (default(double), default(double), default(double), default(double), default(double)) { }
        public Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType CategoryType { get { throw null; } }
        public string ItemName { get { throw null; } }
        public string ResourceGroup { get { throw null; } }
        public string SubscriptionId { get { throw null; } }
        Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionTopItemsSummary System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionTopItemsSummary>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionTopItemsSummary>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionTopItemsSummary System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionTopItemsSummary>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionTopItemsSummary>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceCarbonEmissionTopItemsSummary>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class ResourceGroupCarbonEmissionItemDetail : Azure.ResourceManager.CarbonOptimization.Models.CarbonEmission, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionItemDetail>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionItemDetail>
    {
        internal ResourceGroupCarbonEmissionItemDetail() : base (default(double), default(double), default(double), default(double), default(double)) { }
        public Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType CategoryType { get { throw null; } }
        public string GroupName { get { throw null; } }
        public string ItemName { get { throw null; } }
        public string SubscriptionId { get { throw null; } }
        Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionItemDetail System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionItemDetail>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionItemDetail>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionItemDetail System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionItemDetail>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionItemDetail>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionItemDetail>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class ResourceGroupCarbonEmissionTopItemMonthlySummary : Azure.ResourceManager.CarbonOptimization.Models.CarbonEmission, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionTopItemMonthlySummary>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionTopItemMonthlySummary>
    {
        internal ResourceGroupCarbonEmissionTopItemMonthlySummary() : base (default(double), default(double), default(double), default(double), default(double)) { }
        public Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType CategoryType { get { throw null; } }
        public string Date { get { throw null; } }
        public string ItemName { get { throw null; } }
        public string SubscriptionId { get { throw null; } }
        Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionTopItemMonthlySummary System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionTopItemMonthlySummary>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionTopItemMonthlySummary>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionTopItemMonthlySummary System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionTopItemMonthlySummary>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionTopItemMonthlySummary>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionTopItemMonthlySummary>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class ResourceGroupCarbonEmissionTopItemsSummary : Azure.ResourceManager.CarbonOptimization.Models.CarbonEmission, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionTopItemsSummary>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionTopItemsSummary>
    {
        internal ResourceGroupCarbonEmissionTopItemsSummary() : base (default(double), default(double), default(double), default(double), default(double)) { }
        public Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType CategoryType { get { throw null; } }
        public string ItemName { get { throw null; } }
        public string SubscriptionId { get { throw null; } }
        Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionTopItemsSummary System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionTopItemsSummary>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionTopItemsSummary>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionTopItemsSummary System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionTopItemsSummary>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionTopItemsSummary>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceGroupCarbonEmissionTopItemsSummary>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class ResourceTypeCarbonEmissionItemDetail : Azure.ResourceManager.CarbonOptimization.Models.CarbonEmission, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceTypeCarbonEmissionItemDetail>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceTypeCarbonEmissionItemDetail>
    {
        internal ResourceTypeCarbonEmissionItemDetail() : base (default(double), default(double), default(double), default(double), default(double)) { }
        public Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType CategoryType { get { throw null; } }
        public string ItemName { get { throw null; } }
        public string ResourceTypeFriendlyName { get { throw null; } }
        Azure.ResourceManager.CarbonOptimization.Models.ResourceTypeCarbonEmissionItemDetail System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceTypeCarbonEmissionItemDetail>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceTypeCarbonEmissionItemDetail>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.CarbonOptimization.Models.ResourceTypeCarbonEmissionItemDetail System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceTypeCarbonEmissionItemDetail>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceTypeCarbonEmissionItemDetail>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.ResourceTypeCarbonEmissionItemDetail>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class TopItemsMonthlySummaryReportQueryContent : Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryContent, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.TopItemsMonthlySummaryReportQueryContent>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.TopItemsMonthlySummaryReportQueryContent>
    {
        public TopItemsMonthlySummaryReportQueryContent(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryDateRange dateRange, System.Collections.Generic.IEnumerable<string> subscriptionList, System.Collections.Generic.IEnumerable<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope> carbonScopeList, Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType categoryType, int topItems) : base (default(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryDateRange), default(System.Collections.Generic.IEnumerable<string>), default(System.Collections.Generic.IEnumerable<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope>)) { }
        public Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType CategoryType { get { throw null; } }
        public int TopItems { get { throw null; } }
        Azure.ResourceManager.CarbonOptimization.Models.TopItemsMonthlySummaryReportQueryContent System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.TopItemsMonthlySummaryReportQueryContent>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.TopItemsMonthlySummaryReportQueryContent>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.CarbonOptimization.Models.TopItemsMonthlySummaryReportQueryContent System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.TopItemsMonthlySummaryReportQueryContent>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.TopItemsMonthlySummaryReportQueryContent>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.TopItemsMonthlySummaryReportQueryContent>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
    public partial class TopItemsSummaryReportQueryContent : Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryContent, System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.TopItemsSummaryReportQueryContent>, System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.TopItemsSummaryReportQueryContent>
    {
        public TopItemsSummaryReportQueryContent(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryDateRange dateRange, System.Collections.Generic.IEnumerable<string> subscriptionList, System.Collections.Generic.IEnumerable<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope> carbonScopeList, Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType categoryType, int topItems) : base (default(Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryDateRange), default(System.Collections.Generic.IEnumerable<string>), default(System.Collections.Generic.IEnumerable<Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionQueryScope>)) { }
        public Azure.ResourceManager.CarbonOptimization.Models.CarbonEmissionCategoryType CategoryType { get { throw null; } }
        public int TopItems { get { throw null; } }
        Azure.ResourceManager.CarbonOptimization.Models.TopItemsSummaryReportQueryContent System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.TopItemsSummaryReportQueryContent>.Create(ref System.Text.Json.Utf8JsonReader reader, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        void System.ClientModel.Primitives.IJsonModel<Azure.ResourceManager.CarbonOptimization.Models.TopItemsSummaryReportQueryContent>.Write(System.Text.Json.Utf8JsonWriter writer, System.ClientModel.Primitives.ModelReaderWriterOptions options) { }
        Azure.ResourceManager.CarbonOptimization.Models.TopItemsSummaryReportQueryContent System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.TopItemsSummaryReportQueryContent>.Create(System.BinaryData data, System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        string System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.TopItemsSummaryReportQueryContent>.GetFormatFromOptions(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
        System.BinaryData System.ClientModel.Primitives.IPersistableModel<Azure.ResourceManager.CarbonOptimization.Models.TopItemsSummaryReportQueryContent>.Write(System.ClientModel.Primitives.ModelReaderWriterOptions options) { throw null; }
    }
}
