// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Threading;
using System.Threading.Tasks;
using Azure.Core;
using Azure.Core.Pipeline;
using Azure.ResourceManager.Resources;

namespace Azure.ResourceManager
{
    /// <inheritdoc/>
#pragma warning disable SA1649 // File name should match first type name
    public abstract class ArmOperationRehydration<T>
#pragma warning restore SA1649 // File name should match first type name
    {
        /// <summary> Initializes a new instance of the <see cref="ArmOperationRehydration"/> class. </summary>
        /// <param name="client"> The client parameters to use in these operations. </param>
        /// <param name="id"> The id of the ArmOperation. </param>
        public ArmOperationRehydration(ArmClient client, string id)
        {
            Argument.AssertNotNull(id, nameof(id));
            Argument.AssertNotNull(client, nameof(client));

            Client = client;
            Id = id;
        }

        /// <summary>
        /// Gets the <see cref="ArmClient"/> this resource client was created from.
        /// </summary>
        protected internal virtual ArmClient Client { get; }

        /// <summary>
        /// Gets the pipeline.
        /// </summary>
        protected internal virtual HttpPipeline Pipeline => Client.Pipeline;

        /// <summary>
        /// Gets the diagnostic options.
        /// </summary>
        protected internal virtual DiagnosticsOptions Diagnostics => Client.Diagnostics;

        /// <summary>
        /// Gets the operation id.
        /// </summary>
        protected internal virtual string Id { get; private set; }

        // <summary> Rehydrate an LRO. </summary>
        /// <param name="waitUntil"> "F:Azure.WaitUntil.Completed" if the method should wait to return until the long-running operation has completed on the service; "F:Azure.WaitUntil.Started" if it should return after starting the operation. For more information on long-running operations, please see <see href="https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/LongRunningOperations.md"> Azure.Core Long-Running Operation samples</see>. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual async Task<ArmOperation<T>> RehydrateAsync(WaitUntil waitUntil, CancellationToken cancellationToken = default)
        {
            var clientDiagnostics = new ClientDiagnostics("Azure.ResourceManager", "", Diagnostics);
            using var scope = clientDiagnostics.CreateScope("ArmOperationRehydration.Rehydrate");
            scope.Start();
            try
            {
                Type genericType = typeof(T);
                IOperationSource<T> source;
                if (genericType == typeof(GenericResource))
                {
                    source = (IOperationSource<T>)(new GenericResourceOperationSource(Client));
                }
                else
                {
                    throw new ArgumentOutOfRangeException($"Not expected generic type: {genericType}");
                }
                var operation = new ResourcesArmOperation<T>(source, clientDiagnostics, Pipeline, Id);
                if (waitUntil == WaitUntil.Completed)
                    await operation.WaitForCompletionResponseAsync(cancellationToken).ConfigureAwait(false);
                return operation;
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        // <summary> Rehydrate an LRO. </summary>
        /// <param name="waitUntil"> "F:Azure.WaitUntil.Completed" if the method should wait to return until the long-running operation has completed on the service; "F:Azure.WaitUntil.Started" if it should return after starting the operation. For more information on long-running operations, please see <see href="https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/LongRunningOperations.md"> Azure.Core Long-Running Operation samples</see>. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual ArmOperation<T> Rehydrate(WaitUntil waitUntil, CancellationToken cancellationToken = default)
        {
            var clientDiagnostics = new ClientDiagnostics("Azure.ResourceManager.ContainerService", "", Diagnostics);
            using var scope = clientDiagnostics.CreateScope("ContainerServiceArmOperationRehydration.Rehydrate");
            scope.Start();
            try
            {
                Type genericType = typeof(T);
                IOperationSource<T> source;
                if (genericType == typeof(GenericResource))
                {
                    source = (IOperationSource<T>)(new GenericResourceOperationSource(Client));
                }
                else
                {
                    throw new ArgumentOutOfRangeException($"Not expected generic type: {genericType}");
                }
                var operation = new ResourcesArmOperation<T>(source, clientDiagnostics, Pipeline, Id);
                if (waitUntil == WaitUntil.Completed)
                    operation.WaitForCompletionResponse(cancellationToken);
                return operation;
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }
    }
}
