// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using Microsoft.TypeSpec.Generator.Customizations;

// Preserve enum values and ordinals that shipped from the reflection-based provisioning generator.
[assembly: CodeGenEnumValue("ApplicationGatewayCustomErrorStatusCode", "HttpStatus499", 0)]
[assembly: CodeGenEnumValue("ApplicationGatewayCustomErrorStatusCode", "HttpStatus400", 1)]
[assembly: CodeGenEnumValue("ApplicationGatewayCustomErrorStatusCode", "HttpStatus403", 2)]
[assembly: CodeGenEnumValue("ApplicationGatewayCustomErrorStatusCode", "HttpStatus404", 3)]
[assembly: CodeGenEnumValue("ApplicationGatewayCustomErrorStatusCode", "HttpStatus405", 4)]
[assembly: CodeGenEnumValue("ApplicationGatewayCustomErrorStatusCode", "HttpStatus408", 5)]
[assembly: CodeGenEnumValue("ApplicationGatewayCustomErrorStatusCode", "HttpStatus500", 6)]
[assembly: CodeGenEnumValue("ApplicationGatewayCustomErrorStatusCode", "HttpStatus502", 7)]
[assembly: CodeGenEnumValue("ApplicationGatewayCustomErrorStatusCode", "HttpStatus503", 8)]
[assembly: CodeGenEnumValue("ApplicationGatewayCustomErrorStatusCode", "HttpStatus504", 9)]

[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsECDiffieHellmanRsaWithAes256CbcSha384", 0, WireName = "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsECDiffieHellmanRsaWithAes128CbcSha256", 1, WireName = "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsECDiffieHellmanRsaWithAes256CbcSha", 2, WireName = "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsECDiffieHellmanRsaWithAes128CbcSha", 3, WireName = "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsDHERsaWithAes256GcmSha384", 4, WireName = "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsDHERsaWithAes128GcmSha256", 5, WireName = "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsDHERsaWithAes256CbcSha", 6, WireName = "TLS_DHE_RSA_WITH_AES_256_CBC_SHA")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsDHERsaWithAes128CbcSha", 7, WireName = "TLS_DHE_RSA_WITH_AES_128_CBC_SHA")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsRsaWithAes256GcmSha384", 8, WireName = "TLS_RSA_WITH_AES_256_GCM_SHA384")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsRsaWithAes128GcmSha256", 9, WireName = "TLS_RSA_WITH_AES_128_GCM_SHA256")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsRsaWithAes256CbcSha256", 10, WireName = "TLS_RSA_WITH_AES_256_CBC_SHA256")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsRsaWithAes128CbcSha256", 11, WireName = "TLS_RSA_WITH_AES_128_CBC_SHA256")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsRsaWithAes256CbcSha", 12, WireName = "TLS_RSA_WITH_AES_256_CBC_SHA")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsRsaWithAes128CbcSha", 13, WireName = "TLS_RSA_WITH_AES_128_CBC_SHA")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsECDiffieHellmanECDsaWithAes256GcmSha384", 14, WireName = "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsECDiffieHellmanECDsaWithAes128GcmSha256", 15, WireName = "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsECDiffieHellmanECDsaWithAes256CbcSha384", 16, WireName = "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsECDiffieHellmanECDsaWithAes128CbcSha256", 17, WireName = "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsECDiffieHellmanECDsaWithAes256CbcSha", 18, WireName = "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsECDiffieHellmanECDsaWithAes128CbcSha", 19, WireName = "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsDheDssWithAes256CbcSha256", 20, WireName = "TLS_DHE_DSS_WITH_AES_256_CBC_SHA256")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsDheDssWithAes128CbcSha256", 21, WireName = "TLS_DHE_DSS_WITH_AES_128_CBC_SHA256")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsDheDssWithAes256CbcSha", 22, WireName = "TLS_DHE_DSS_WITH_AES_256_CBC_SHA")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsDheDssWithAes128CbcSha", 23, WireName = "TLS_DHE_DSS_WITH_AES_128_CBC_SHA")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsRsaWith3DesEdeCbcSha", 24, WireName = "TLS_RSA_WITH_3DES_EDE_CBC_SHA")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsDheDssWith3DesEdeCbcSha", 25, WireName = "TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsECDiffieHellmanRsaWithAes128GcmSha256", 26, WireName = "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslCipherSuite", "TlsECDiffieHellmanRsaWithAes256GcmSha384", 27, WireName = "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384")]

[assembly: CodeGenEnumValue("ApplicationGatewaySslProtocol", "Tls1_0", 0, WireName = "TLSv1_0")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslProtocol", "Tls1_1", 1, WireName = "TLSv1_1")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslProtocol", "Tls1_2", 2, WireName = "TLSv1_2")]
[assembly: CodeGenEnumValue("ApplicationGatewaySslProtocol", "TLSv13", 3, WireName = "TLSv1_3")]

[assembly: CodeGenEnumValue("ConnectionMonitorEndpointType", "AzureVm", 0, WireName = "AzureVM")]
[assembly: CodeGenEnumValue("ConnectionMonitorEndpointType", "AzureVNet", 1)]
[assembly: CodeGenEnumValue("ConnectionMonitorEndpointType", "AzureSubnet", 2)]
[assembly: CodeGenEnumValue("ConnectionMonitorEndpointType", "ExternalAddress", 3)]
[assembly: CodeGenEnumValue("ConnectionMonitorEndpointType", "MMAWorkspaceMachine", 4)]
[assembly: CodeGenEnumValue("ConnectionMonitorEndpointType", "MMAWorkspaceNetwork", 5)]
[assembly: CodeGenEnumValue("ConnectionMonitorEndpointType", "AzureArcVm", 6, WireName = "AzureArcVM")]
[assembly: CodeGenEnumValue("ConnectionMonitorEndpointType", "AzureVmss", 7, WireName = "AzureVMSS")]
[assembly: CodeGenEnumValue("ConnectionMonitorEndpointType", "AzureArcNetwork", 8)]

[assembly: CodeGenEnumValue("DdosCustomPolicyProtocol", "Tcp", 0)]
[assembly: CodeGenEnumValue("DdosCustomPolicyProtocol", "Udp", 1)]
[assembly: CodeGenEnumValue("DdosCustomPolicyProtocol", "Syn", 2)]

[assembly: CodeGenEnumValue("DdosSettingsProtectionCoverage", "Basic", 0)]
[assembly: CodeGenEnumValue("DdosSettingsProtectionCoverage", "Standard", 1)]

[assembly: CodeGenEnumValue("FirewallPolicyIntrusionDetectionProfileType", "Basic", 0)]
[assembly: CodeGenEnumValue("FirewallPolicyIntrusionDetectionProfileType", "Standard", 1)]
[assembly: CodeGenEnumValue("FirewallPolicyIntrusionDetectionProfileType", "Advanced", 2)]
[assembly: CodeGenEnumValue("FirewallPolicyIntrusionDetectionProfileType", "Off", 3)]
[assembly: CodeGenEnumValue("FirewallPolicyIntrusionDetectionProfileType", "Emerging", 4)]
[assembly: CodeGenEnumValue("FirewallPolicyIntrusionDetectionProfileType", "Core", 5)]
[assembly: CodeGenEnumValue("FirewallPolicyIntrusionDetectionProfileType", "Extended", 6)]

[assembly: CodeGenEnumValue("IPsecIntegrity", "MD5", 0)]
[assembly: CodeGenEnumValue("IPsecIntegrity", "Sha1", 1, WireName = "SHA1")]
[assembly: CodeGenEnumValue("IPsecIntegrity", "Sha256", 2, WireName = "SHA256")]
[assembly: CodeGenEnumValue("IPsecIntegrity", "Sha384", 3, WireName = "SHA384")]
[assembly: CodeGenEnumValue("IPsecIntegrity", "GcmAes256", 4, WireName = "GCMAES256")]
[assembly: CodeGenEnumValue("IPsecIntegrity", "GcmAes128", 5, WireName = "GCMAES128")]

[assembly: CodeGenEnumValue("LoadBalancerBackendAddressAdminState", "Drain", 0)]
[assembly: CodeGenEnumValue("LoadBalancerBackendAddressAdminState", "None", 1)]
[assembly: CodeGenEnumValue("LoadBalancerBackendAddressAdminState", "Up", 2)]
[assembly: CodeGenEnumValue("LoadBalancerBackendAddressAdminState", "Down", 3)]

[assembly: CodeGenEnumValue("ManagedRuleSensitivityType", "None", 0)]
[assembly: CodeGenEnumValue("ManagedRuleSensitivityType", "Low", 1)]
[assembly: CodeGenEnumValue("ManagedRuleSensitivityType", "Medium", 2)]
[assembly: CodeGenEnumValue("ManagedRuleSensitivityType", "High", 3)]

[assembly: CodeGenEnumValue("PfsGroup", "None", 0)]
[assembly: CodeGenEnumValue("PfsGroup", "Pfs1", 1, WireName = "PFS1")]
[assembly: CodeGenEnumValue("PfsGroup", "Pfs2", 2, WireName = "PFS2")]
[assembly: CodeGenEnumValue("PfsGroup", "Pfs2048", 3, WireName = "PFS2048")]
[assembly: CodeGenEnumValue("PfsGroup", "Ecp256", 4, WireName = "ECP256")]
[assembly: CodeGenEnumValue("PfsGroup", "Ecp384", 5, WireName = "ECP384")]
[assembly: CodeGenEnumValue("PfsGroup", "Pfs24", 6, WireName = "PFS24")]
[assembly: CodeGenEnumValue("PfsGroup", "Pfs14", 7, WireName = "PFS14")]
[assembly: CodeGenEnumValue("PfsGroup", "Pfs", 8, WireName = "PFSMM")]

[assembly: CodeGenEnumValue("VpnAuthenticationType", "AAD", 0)]
[assembly: CodeGenEnumValue("VpnAuthenticationType", "Certificate", 1)]
[assembly: CodeGenEnumValue("VpnAuthenticationType", "Radius", 2)]
[assembly: CodeGenEnumValue("VpnAuthenticationType", "Aad", 3, WireName = "AAD")]
