// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Orbital.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Response for an API service call that lists the resource IDs of
    /// resources associated with another resource.
    /// </summary>
    public partial class ResourceIdListResult
    {
        /// <summary>
        /// Initializes a new instance of the ResourceIdListResult class.
        /// </summary>
        public ResourceIdListResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ResourceIdListResult class.
        /// </summary>
        /// <param name="value">A list of Azure Resource IDs.</param>
        /// <param name="nextLink">The URL to get the next set of
        /// results.</param>
        public ResourceIdListResult(IList<ResourceIdListResultValueItem> value = default(IList<ResourceIdListResultValueItem>), string nextLink = default(string))
        {
            Value = value;
            NextLink = nextLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets a list of Azure Resource IDs.
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<ResourceIdListResultValueItem> Value { get; set; }

        /// <summary>
        /// Gets the URL to get the next set of results.
        /// </summary>
        [JsonProperty(PropertyName = "nextLink")]
        public string NextLink { get; private set; }

    }
}
