// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Text;
using Azure.Core;
using Azure.ResourceManager.Resources;

namespace Azure.ResourceManager.CognitiveServices.Models
{
    public partial class CognitiveServicesMultiRegionSettings
    {
        BinaryData global::System.ClientModel.Primitives.IPersistableModel<CognitiveServicesMultiRegionSettings>.Write(ModelReaderWriterOptions options)
        {
            var format = options.Format == "W" ? ((IPersistableModel<ResourceGroupData>)this).GetFormatFromOptions(options) : options.Format;

            switch (format)
            {
                case "J":
                    return ModelReaderWriter.Write(this, options);
                case "bicep":
                    return SerializeBicep(options);
                default:
                    throw new FormatException($"The model {nameof(ResourceGroupData)} does not support '{options.Format}' format.");
            }
        }

        private BinaryData SerializeBicep(ModelReaderWriterOptions options)
        {
            StringBuilder sb = new StringBuilder();
            if (Optional.IsDefined(RoutingMethod))
            {
                sb.AppendLine($"  routingMethod: '{RoutingMethod.Value}'");
            }
            if (Optional.IsCollectionDefined(Regions))
            {
                sb.AppendLine($"  regions: [");
                foreach (var item in Regions)
                {
                    sb.AppendLine($"    {{");
                    sb.AppendChildObject(item, options, true);
                    sb.AppendLine($"    }}");
                }
                sb.AppendLine($"  ]");
            }
            return BinaryData.FromString(sb.ToString());
        }
    }
}
