// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#nullable disable

#pragma warning disable CS1591

using System.Threading;
using Microsoft.TypeSpec.Generator.Customizations;

namespace Azure.ResourceManager.SecurityCenter.Mocking
{
    // Suppress malformed generated JIT policy forwarding helpers; the collection-level APIs remain generated.
    [CodeGenSuppress("GetAllowedConnectionsAsync", typeof(CancellationToken))]
    [CodeGenSuppress("GetAllowedConnections", typeof(CancellationToken))]
    [CodeGenSuppress("GetDiscoveredSecuritySolutionsAsync", typeof(CancellationToken))]
    [CodeGenSuppress("GetDiscoveredSecuritySolutions", typeof(CancellationToken))]
    [CodeGenSuppress("GetExternalSecuritySolutionsAsync", typeof(CancellationToken))]
    [CodeGenSuppress("GetExternalSecuritySolutions", typeof(CancellationToken))]
    [CodeGenSuppress("GetJitNetworkAccessPoliciesAsync", typeof(CancellationToken))]
    [CodeGenSuppress("GetJitNetworkAccessPolicies", typeof(CancellationToken))]
    [CodeGenSuppress("GetMdeOnboardingsAsync", typeof(CancellationToken))]
    [CodeGenSuppress("GetMdeOnboardings", typeof(CancellationToken))]
    [CodeGenSuppress("GetSecuritySolutionsAsync", typeof(CancellationToken))]
    [CodeGenSuppress("GetSecuritySolutions", typeof(CancellationToken))]
    [CodeGenSuppress("GetTopologiesAsync", typeof(CancellationToken))]
    [CodeGenSuppress("GetTopologies", typeof(CancellationToken))]
    public partial class MockableSecurityCenterSubscriptionResource
    {
        public virtual Azure.AsyncPageable<AdaptiveApplicationControlGroupResource> GetAdaptiveApplicationControlGroupsAsync(bool? includePathRecommendations = default, bool? summary = default, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Pageable<AdaptiveApplicationControlGroupResource> GetAdaptiveApplicationControlGroups(bool? includePathRecommendations = default, bool? summary = default, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.AsyncPageable<CustomAssessmentAutomationResource> GetCustomAssessmentAutomationsAsync(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Pageable<CustomAssessmentAutomationResource> GetCustomAssessmentAutomations(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.AsyncPageable<CustomEntityStoreAssignmentResource> GetCustomEntityStoreAssignmentsAsync(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Pageable<CustomEntityStoreAssignmentResource> GetCustomEntityStoreAssignments(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.AsyncPageable<JitNetworkAccessPolicyResource> GetJitNetworkAccessPoliciesAsync(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Pageable<JitNetworkAccessPolicyResource> GetJitNetworkAccessPolicies(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.AsyncPageable<Azure.ResourceManager.SecurityCenter.Models.SecureScoreControlDetails> GetSecureScoreControlsAsync(Azure.ResourceManager.SecurityCenter.Models.SecurityScoreODataExpand? expand = default, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Pageable<Azure.ResourceManager.SecurityCenter.Models.SecureScoreControlDetails> GetSecureScoreControls(Azure.ResourceManager.SecurityCenter.Models.SecurityScoreODataExpand? expand = default, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.AsyncPageable<Azure.ResourceManager.SecurityCenter.Models.SecuritySolutionsReferenceData> GetAllSecuritySolutionsReferenceDataAsync(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Pageable<Azure.ResourceManager.SecurityCenter.Models.SecuritySolutionsReferenceData> GetAllSecuritySolutionsReferenceData(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.AsyncPageable<SecurityAlertData> GetAlertsAsync(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Pageable<SecurityAlertData> GetAlerts(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.AsyncPageable<SecurityTaskData> GetTasksAsync(string ascLocation, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Pageable<SecurityTaskData> GetTasks(string ascLocation, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.AsyncPageable<SoftwareInventoryResource> GetSoftwareInventoriesAsync(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Pageable<SoftwareInventoryResource> GetSoftwareInventories(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual SecurityCenterPricingCollection GetSecurityCenterPricings() => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual SecurityCloudConnectorCollection GetSecurityCloudConnectors() => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual SubscriptionAssessmentMetadataCollection GetAllSubscriptionAssessmentMetadata() => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual SubscriptionGovernanceRuleCollection GetSubscriptionGovernanceRules() => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual SubscriptionSecurityApplicationCollection GetSubscriptionSecurityApplications() => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.AsyncPageable<AdaptiveApplicationControlGroupResource> GetAdaptiveApplicationControlGroupsAsync(Azure.ResourceManager.Resources.SubscriptionResource subscriptionResource, bool? includePathRecommendations = default, bool? summary = default, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Pageable<AdaptiveApplicationControlGroupResource> GetAdaptiveApplicationControlGroups(Azure.ResourceManager.Resources.SubscriptionResource subscriptionResource, bool? includePathRecommendations = default, bool? summary = default, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.AsyncPageable<CustomAssessmentAutomationResource> GetCustomAssessmentAutomationsAsync(Azure.ResourceManager.Resources.SubscriptionResource subscriptionResource, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Pageable<CustomAssessmentAutomationResource> GetCustomAssessmentAutomations(Azure.ResourceManager.Resources.SubscriptionResource subscriptionResource, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.AsyncPageable<CustomEntityStoreAssignmentResource> GetCustomEntityStoreAssignmentsAsync(Azure.ResourceManager.Resources.SubscriptionResource subscriptionResource, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Pageable<CustomEntityStoreAssignmentResource> GetCustomEntityStoreAssignments(Azure.ResourceManager.Resources.SubscriptionResource subscriptionResource, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.AsyncPageable<JitNetworkAccessPolicyResource> GetJitNetworkAccessPoliciesAsync(Azure.ResourceManager.Resources.SubscriptionResource subscriptionResource, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Pageable<JitNetworkAccessPolicyResource> GetJitNetworkAccessPolicies(Azure.ResourceManager.Resources.SubscriptionResource subscriptionResource, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.AsyncPageable<Azure.ResourceManager.SecurityCenter.Models.SecureScoreControlDetails> GetSecureScoreControlsAsync(Azure.ResourceManager.Resources.SubscriptionResource subscriptionResource, Azure.ResourceManager.SecurityCenter.Models.SecurityScoreODataExpand? expand = default, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Pageable<Azure.ResourceManager.SecurityCenter.Models.SecureScoreControlDetails> GetSecureScoreControls(Azure.ResourceManager.Resources.SubscriptionResource subscriptionResource, Azure.ResourceManager.SecurityCenter.Models.SecurityScoreODataExpand? expand = default, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.AsyncPageable<Azure.ResourceManager.SecurityCenter.Models.SecuritySolutionsReferenceData> GetAllSecuritySolutionsReferenceDataAsync(Azure.ResourceManager.Resources.SubscriptionResource subscriptionResource, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Pageable<Azure.ResourceManager.SecurityCenter.Models.SecuritySolutionsReferenceData> GetAllSecuritySolutionsReferenceData(Azure.ResourceManager.Resources.SubscriptionResource subscriptionResource, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.AsyncPageable<SecurityAlertData> GetAlertsAsync(Azure.ResourceManager.Resources.SubscriptionResource subscriptionResource, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Pageable<SecurityAlertData> GetAlerts(Azure.ResourceManager.Resources.SubscriptionResource subscriptionResource, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.AsyncPageable<SecurityTaskData> GetTasksAsync(Azure.ResourceManager.Resources.SubscriptionResource subscriptionResource, string ascLocation, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Pageable<SecurityTaskData> GetTasks(Azure.ResourceManager.Resources.SubscriptionResource subscriptionResource, string ascLocation, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.AsyncPageable<SoftwareInventoryResource> GetSoftwareInventoriesAsync(Azure.ResourceManager.Resources.SubscriptionResource subscriptionResource, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Pageable<SoftwareInventoryResource> GetSoftwareInventories(Azure.ResourceManager.Resources.SubscriptionResource subscriptionResource, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.AsyncPageable<Azure.ResourceManager.SecurityCenter.Models.SecurityCenterAllowedConnection> GetAllowedConnectionsAsync(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Pageable<Azure.ResourceManager.SecurityCenter.Models.SecurityCenterAllowedConnection> GetAllowedConnections(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.AsyncPageable<Azure.ResourceManager.SecurityCenter.Models.DiscoveredSecuritySolution> GetDiscoveredSecuritySolutionsAsync(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Pageable<Azure.ResourceManager.SecurityCenter.Models.DiscoveredSecuritySolution> GetDiscoveredSecuritySolutions(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.AsyncPageable<Azure.ResourceManager.SecurityCenter.Models.ExternalSecuritySolution> GetExternalSecuritySolutionsAsync(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Pageable<Azure.ResourceManager.SecurityCenter.Models.ExternalSecuritySolution> GetExternalSecuritySolutions(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.AsyncPageable<Azure.ResourceManager.SecurityCenter.Models.MdeOnboarding> GetMdeOnboardingsAsync(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Pageable<Azure.ResourceManager.SecurityCenter.Models.MdeOnboarding> GetMdeOnboardings(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.AsyncPageable<Azure.ResourceManager.SecurityCenter.Models.SecuritySolution> GetSecuritySolutionsAsync(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Pageable<Azure.ResourceManager.SecurityCenter.Models.SecuritySolution> GetSecuritySolutions(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.AsyncPageable<Azure.ResourceManager.SecurityCenter.Models.SecurityTopologyResource> GetTopologiesAsync(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Pageable<Azure.ResourceManager.SecurityCenter.Models.SecurityTopologyResource> GetTopologies(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Response<Azure.ResourceManager.SecurityCenter.Models.MdeOnboarding> GetMdeOnboarding(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Response<SecurityCenterLocationResource> GetSecurityCenterLocation(Azure.Core.AzureLocation ascLocation, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Response<SecurityCenterPricingResource> GetSecurityCenterPricing(string pricingName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Response<SecurityCloudConnectorResource> GetSecurityCloudConnector(string securityCloudConnectorName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Response<SecurityContactResource> GetSecurityContact(string securityContactName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Response<SecuritySettingResource> GetSecuritySetting(Azure.ResourceManager.SecurityCenter.Models.SecuritySettingName settingName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Response<SubscriptionAssessmentMetadataResource> GetSubscriptionAssessmentMetadata(string assessmentMetadataName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Response<SubscriptionGovernanceRuleResource> GetSubscriptionGovernanceRule(string ruleId, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Response<SubscriptionSecurityApplicationResource> GetSubscriptionSecurityApplication(string applicationId, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.SecurityCenter.Models.MdeOnboarding>> GetMdeOnboardingAsync(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual System.Threading.Tasks.Task<Azure.Response<SecurityCenterLocationResource>> GetSecurityCenterLocationAsync(Azure.Core.AzureLocation ascLocation, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual System.Threading.Tasks.Task<Azure.Response<SecurityCenterPricingResource>> GetSecurityCenterPricingAsync(string pricingName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual System.Threading.Tasks.Task<Azure.Response<SecurityCloudConnectorResource>> GetSecurityCloudConnectorAsync(string securityCloudConnectorName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual System.Threading.Tasks.Task<Azure.Response<SecurityContactResource>> GetSecurityContactAsync(string securityContactName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual System.Threading.Tasks.Task<Azure.Response<SecuritySettingResource>> GetSecuritySettingAsync(Azure.ResourceManager.SecurityCenter.Models.SecuritySettingName settingName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual System.Threading.Tasks.Task<Azure.Response<SubscriptionAssessmentMetadataResource>> GetSubscriptionAssessmentMetadataAsync(string assessmentMetadataName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual System.Threading.Tasks.Task<Azure.Response<SubscriptionGovernanceRuleResource>> GetSubscriptionGovernanceRuleAsync(string ruleId, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual System.Threading.Tasks.Task<Azure.Response<SubscriptionSecurityApplicationResource>> GetSubscriptionSecurityApplicationAsync(string applicationId, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
    }
}
