// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#nullable disable

#pragma warning disable CS1591

using System.Threading;
using Microsoft.TypeSpec.Generator.Customizations;

namespace Azure.ResourceManager.SecurityCenter.Mocking
{
    [CodeGenSuppress("GetJitNetworkAccessPoliciesAsync", typeof(CancellationToken))]
    [CodeGenSuppress("GetJitNetworkAccessPolicies", typeof(CancellationToken))]
    public partial class MockableSecurityCenterResourceGroupResource
    {
        public virtual AdaptiveNetworkHardeningCollection GetAdaptiveNetworkHardenings(string resourceNamespace, string resourceType, string resourceName) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual CustomAssessmentAutomationCollection GetCustomAssessmentAutomations() => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual CustomEntityStoreAssignmentCollection GetCustomEntityStoreAssignments() => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual JitNetworkAccessPolicyCollection GetJitNetworkAccessPolicies(Azure.Core.AzureLocation ascLocation) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual ResourceGroupSecurityAlertCollection GetResourceGroupSecurityAlerts(Azure.Core.AzureLocation ascLocation) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual ResourceGroupSecurityTaskCollection GetResourceGroupSecurityTasks(Azure.Core.AzureLocation ascLocation) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual ServerVulnerabilityAssessmentCollection GetServerVulnerabilityAssessments(string resourceNamespace, string resourceType, string resourceName) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual SoftwareInventoryCollection GetSoftwareInventories(string resourceNamespace, string resourceType, string resourceName) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.AsyncPageable<SecurityAlertData> GetAlertsByResourceGroupAsync(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Pageable<SecurityAlertData> GetAlertsByResourceGroup(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.AsyncPageable<JitNetworkAccessPolicyResource> GetJitNetworkAccessPoliciesAsync(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Pageable<JitNetworkAccessPolicyResource> GetJitNetworkAccessPolicies(CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Response<AdaptiveNetworkHardeningResource> GetAdaptiveNetworkHardening(string resourceNamespace, string resourceType, string resourceName, string adaptiveNetworkHardeningResourceName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Response<CustomAssessmentAutomationResource> GetCustomAssessmentAutomation(string customAssessmentAutomationName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Response<CustomEntityStoreAssignmentResource> GetCustomEntityStoreAssignment(string customEntityStoreAssignmentName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Response<JitNetworkAccessPolicyResource> GetJitNetworkAccessPolicy(Azure.Core.AzureLocation ascLocation, string jitNetworkAccessPolicyName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Response<Azure.ResourceManager.SecurityCenter.Models.DiscoveredSecuritySolution> GetDiscoveredSecuritySolution(Azure.Core.AzureLocation ascLocation, string discoveredSecuritySolutionName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Response<Azure.ResourceManager.SecurityCenter.Models.ExternalSecuritySolution> GetExternalSecuritySolution(Azure.Core.AzureLocation ascLocation, string externalSecuritySolutionName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Response<Azure.ResourceManager.SecurityCenter.Models.SecurityCenterAllowedConnection> GetAllowedConnection(Azure.Core.AzureLocation ascLocation, Azure.ResourceManager.SecurityCenter.Models.SecurityCenterConnectionType connectionType, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Response<Azure.ResourceManager.SecurityCenter.Models.SecuritySolution> GetSecuritySolution(Azure.Core.AzureLocation ascLocation, string securitySolutionName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Response<Azure.ResourceManager.SecurityCenter.Models.SecurityTopologyResource> GetTopology(Azure.Core.AzureLocation ascLocation, string topologyName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Response<ResourceGroupSecurityAlertResource> GetResourceGroupSecurityAlert(Azure.Core.AzureLocation ascLocation, string alertName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Response<ResourceGroupSecurityTaskResource> GetResourceGroupSecurityTask(Azure.Core.AzureLocation ascLocation, string taskName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Response<ServerVulnerabilityAssessmentResource> GetServerVulnerabilityAssessment(string resourceNamespace, string resourceType, string resourceName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual Azure.Response<SoftwareInventoryResource> GetSoftwareInventory(string resourceNamespace, string resourceType, string resourceName, string softwareName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual System.Threading.Tasks.Task<Azure.Response<AdaptiveNetworkHardeningResource>> GetAdaptiveNetworkHardeningAsync(string resourceNamespace, string resourceType, string resourceName, string adaptiveNetworkHardeningResourceName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual System.Threading.Tasks.Task<Azure.Response<CustomAssessmentAutomationResource>> GetCustomAssessmentAutomationAsync(string customAssessmentAutomationName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual System.Threading.Tasks.Task<Azure.Response<CustomEntityStoreAssignmentResource>> GetCustomEntityStoreAssignmentAsync(string customEntityStoreAssignmentName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual System.Threading.Tasks.Task<Azure.Response<JitNetworkAccessPolicyResource>> GetJitNetworkAccessPolicyAsync(Azure.Core.AzureLocation ascLocation, string jitNetworkAccessPolicyName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.SecurityCenter.Models.DiscoveredSecuritySolution>> GetDiscoveredSecuritySolutionAsync(Azure.Core.AzureLocation ascLocation, string discoveredSecuritySolutionName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.SecurityCenter.Models.ExternalSecuritySolution>> GetExternalSecuritySolutionAsync(Azure.Core.AzureLocation ascLocation, string externalSecuritySolutionName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.SecurityCenter.Models.SecurityCenterAllowedConnection>> GetAllowedConnectionAsync(Azure.Core.AzureLocation ascLocation, Azure.ResourceManager.SecurityCenter.Models.SecurityCenterConnectionType connectionType, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.SecurityCenter.Models.SecuritySolution>> GetSecuritySolutionAsync(Azure.Core.AzureLocation ascLocation, string securitySolutionName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual System.Threading.Tasks.Task<Azure.Response<Azure.ResourceManager.SecurityCenter.Models.SecurityTopologyResource>> GetTopologyAsync(Azure.Core.AzureLocation ascLocation, string topologyName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual System.Threading.Tasks.Task<Azure.Response<ResourceGroupSecurityAlertResource>> GetResourceGroupSecurityAlertAsync(Azure.Core.AzureLocation ascLocation, string alertName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual System.Threading.Tasks.Task<Azure.Response<ResourceGroupSecurityTaskResource>> GetResourceGroupSecurityTaskAsync(Azure.Core.AzureLocation ascLocation, string taskName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual System.Threading.Tasks.Task<Azure.Response<ServerVulnerabilityAssessmentResource>> GetServerVulnerabilityAssessmentAsync(string resourceNamespace, string resourceType, string resourceName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
        public virtual System.Threading.Tasks.Task<Azure.Response<SoftwareInventoryResource>> GetSoftwareInventoryAsync(string resourceNamespace, string resourceType, string resourceName, string softwareName, CancellationToken cancellationToken = default) => throw new System.NotSupportedException("This member is preserved for compatibility with a previous SecurityCenter API surface.");
    }
}
