# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/synapse/ci.yml
    - sdk/synapse/service.projects
    - sdk/synapse/Azure.Analytics.Synapse.Artifacts

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    SDKType: client
    ServiceDirectory: synapse
    ArtifactName: packages
    Artifacts:
    - name: Azure.Analytics.Synapse.Artifacts
      safeName: AzureAnalyticsSynapseArtifacts
      triggeringPaths:
      - Azure.Analytics.Synapse.Shared
