// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Usage", "AZC0001:Use one of the following pre-approved namespace groups (https://azure.github.io/azure-sdk/registered_namespaces.html): Azure.AI, Azure.Analytics, Azure.Communication, Azure.Containers, Azure.Core.Expressions, Azure.Data, Azure.DigitalTwins, Azure.Identity, Azure.IoT, Azure.Learn, Azure.Management, Azure.Media, Azure.Messaging, Azure.MixedReality, Azure.Monitor, Azure.ResourceManager, Azure.Search, Azure.Security, Azure.Storage, Azure.Template, Microsoft.Extensions.Azure", Justification = "<Pending>", Scope = "namespace", Target = "~N:Azure.Health.Insights.RadiologyInsights")]
[assembly: SuppressMessage("Usage", "AZC0012:Avoid single word type names", Justification = "<Pending>", Scope = "type", Target = "~T:Azure.Health.Insights.RadiologyInsights.Annotation")]
[assembly: SuppressMessage("Usage", "AZC0012:Avoid single word type names", Justification = "<Pending>", Scope = "type", Target = "~T:Azure.Health.Insights.RadiologyInsights.Extendible")]
[assembly: SuppressMessage("Usage", "AZC0012:Avoid single word type names", Justification = "<Pending>", Scope = "type", Target = "~T:Azure.Health.Insights.RadiologyInsights.Extension")]
[assembly: SuppressMessage("Naming", "AZC0030:Improper model name suffix", Justification = "<Pending>", Scope = "type", Target = "~T:Azure.Health.Insights.RadiologyInsights.FindingOptions")]
[assembly: SuppressMessage("Usage", "AZC0012:Avoid single word type names", Justification = "<Pending>", Scope = "type", Target = "~T:Azure.Health.Insights.RadiologyInsights.Reference")]
[assembly: SuppressMessage("Usage", "AZC0012:Avoid single word type names", Justification = "<Pending>", Scope = "type", Target = "~T:Azure.Health.Insights.RadiologyInsights.Ratio")]
[assembly: SuppressMessage("Usage", "AZC0012:Avoid single word type names", Justification = "<Pending>", Scope = "type", Target = "~T:Azure.Health.Insights.RadiologyInsights.Range")]
[assembly: SuppressMessage("Naming", "AZC0030:Improper model name suffix", Justification = "<Pending>", Scope = "type", Target = "~T:Azure.Health.Insights.RadiologyInsights.RadiologyInsightsInferenceOptions")]
[assembly: SuppressMessage("Naming", "AZC0032:Improper model name suffix", Justification = "<Pending>", Scope = "type", Target = "~T:Azure.Health.Insights.RadiologyInsights.RadiologyInsightsData")]
[assembly: SuppressMessage("Usage", "AZC0012:Avoid single word type names", Justification = "<Pending>", Scope = "type", Target = "~T:Azure.Health.Insights.RadiologyInsights.Coding")]
[assembly: SuppressMessage("Usage", "AZC0012:Avoid single word type names", Justification = "<Pending>", Scope = "type", Target = "~T:Azure.Health.Insights.RadiologyInsights.Coding")]
[assembly: SuppressMessage("Usage", "AZC0012:Avoid single word type names", Justification = "<Pending>", Scope = "type", Target = "~T:Azure.Health.Insights.RadiologyInsights.Element")]
[assembly: SuppressMessage("Usage", "AZC0012:Avoid single word type names", Justification = "<Pending>", Scope = "type", Target = "~T:Azure.Health.Insights.RadiologyInsights.Encounter")]
[assembly: SuppressMessage("Usage", "AZC0012:Avoid single word type names", Justification = "<Pending>", Scope = "type", Target = "~T:Azure.Health.Insights.RadiologyInsights.Encounter")]
[assembly: SuppressMessage("Usage", "AZC0012:Avoid single word type names", Justification = "<Pending>", Scope = "type", Target = "~T:Azure.Health.Insights.RadiologyInsights.Identifier")]
[assembly: SuppressMessage("Usage", "AZC0012:Avoid single word type names", Justification = "<Pending>", Scope = "type", Target = "~T:Azure.Health.Insights.RadiologyInsights.Identifier")]
[assembly: SuppressMessage("Usage", "AZC0012:Avoid single word type names", Justification = "<Pending>", Scope = "type", Target = "~T:Azure.Health.Insights.RadiologyInsights.Narrative")]
[assembly: SuppressMessage("Usage", "AZC0012:Avoid single word type names", Justification = "<Pending>", Scope = "type", Target = "~T:Azure.Health.Insights.RadiologyInsights.Observation")]
[assembly: SuppressMessage("Usage", "AZC0012:Avoid single word type names", Justification = "<Pending>", Scope = "type", Target = "~T:Azure.Health.Insights.RadiologyInsights.Period")]
[assembly: SuppressMessage("Usage", "AZC0012:Avoid single word type names", Justification = "<Pending>", Scope = "type", Target = "~T:Azure.Health.Insights.RadiologyInsights.Quantity")]
[assembly: SuppressMessage("Naming", "AZC0030:Improper model name suffix", Justification = "<Pending>", Scope = "type", Target = "~T:Azure.Health.Insights.RadiologyInsights.FollowupRecommendationOptions")]
[assembly: SuppressMessage("Naming", "AZC0032:Improper model name suffix", Justification = "<Pending>", Scope = "type", Target = "~T:Azure.Health.Insights.RadiologyInsights.SampledData")]
[assembly: SuppressMessage("Usage", "AZC0012:Avoid single word type names", Justification = "<Pending>", Scope = "type", Target = "~T:Azure.Health.Insights.RadiologyInsights.Meta")]
[assembly: SuppressMessage("Usage", "AZC0012:Avoid single word type names", Justification = "<Pending>", Scope = "type", Target = "~T:Azure.Health.Insights.RadiologyInsights.Resource")]
