<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Azure.Provisioning.AlertRuleRecommendations simplifies declarative resource provisioning in .NET.</Description>
    <Version>1.0.0-beta.1</Version>
    <TypespecAdditionalOptions>namespace=Azure.Provisioning.AlertRuleRecommendations;emitter-output-dir=$(MSBuildProjectDirectory)/..;api-version=2023-08-01-preview</TypespecAdditionalOptions>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Provisioning" />
  </ItemGroup>

</Project>
