//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azure.DigitalTwins.Core.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestAssets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestAssets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Azure.DigitalTwins.Core.Tests.TestAssets", typeof(TestAssets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;@id&quot;: &quot;BUILDING_MODEL_ID&quot;,
        ///    &quot;@type&quot;: &quot;Interface&quot;,
        ///    &quot;displayName&quot;: &quot;Building&quot;,
        ///    &quot;description&quot;: &quot;A free-standing structure.&quot;,
        ///    &quot;contents&quot;: [
        ///        {
        ///            &quot;@type&quot;: &quot;Relationship&quot;,
        ///            &quot;name&quot;: &quot;has&quot;,
        ///            &quot;target&quot;: &quot;FLOOR_MODEL_ID&quot;
        ///        },
        ///        {
        ///            &quot;@type&quot;: &quot;Relationship&quot;,
        ///            &quot;name&quot;: &quot;isEquippedWith&quot;,
        ///            &quot;target&quot;: &quot;HVAC_MODEL_ID&quot;
        ///        },
        ///        {
        ///            &quot;@type&quot;: &quot;Property&quot;,
        ///            &quot;name&quot;: &quot;AverageTempera [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BuildingModelPayload {
            get {
                return ResourceManager.GetString("BuildingModelPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;@id&quot;: &quot;FLOOR_MODEL_ID&quot;,
        ///    &quot;@type&quot;: &quot;Interface&quot;,
        ///    &quot;@context&quot;: &quot;dtmi:dtdl:context;2&quot;,
        ///    &quot;displayName&quot;: &quot;Floor&quot;,
        ///    &quot;description&quot;: &quot;A building story.&quot;,
        ///    &quot;contents&quot;: [
        ///        {
        ///            &quot;@type&quot;: &quot;Relationship&quot;,
        ///            &quot;name&quot;: &quot;contains&quot;,
        ///            &quot;target&quot;: &quot;ROOM_MODEL_ID&quot;,
        ///            &quot;properties&quot;: [
        ///                {
        ///                    &quot;@type&quot;: &quot;Property&quot;,
        ///                    &quot;name&quot;: &quot;isAccessRestricted&quot;,
        ///                    &quot;schema&quot;: &quot;boolean&quot;
        ///                }
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FloorModelPayload {
            get {
                return ResourceManager.GetString("FloorModelPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$metadata&quot;: {
        ///    &quot;$model&quot;: &quot;FLOOR_MODEL_ID&quot;
        ///  },
        ///  &quot;AverageTemperature&quot;: 75
        ///}.
        /// </summary>
        internal static string FloorTwinPayload {
            get {
                return ResourceManager.GetString("FloorTwinPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;@id&quot;: &quot;HVAC_MODEL_ID&quot;,
        ///    &quot;@type&quot;: &quot;Interface&quot;,
        ///    &quot;displayName&quot;: &quot;HVAC&quot;,
        ///    &quot;description&quot;: &quot;A heating, ventilation, and air conditioning unit.&quot;,
        ///    &quot;contents&quot;: [
        ///        {
        ///            &quot;@type&quot;: &quot;Property&quot;,
        ///            &quot;name&quot;: &quot;Efficiency&quot;,
        ///            &quot;schema&quot;: &quot;double&quot;
        ///        },
        ///        {
        ///            &quot;@type&quot;: &quot;Property&quot;,
        ///            &quot;name&quot;: &quot;TargetTemperature&quot;,
        ///            &quot;schema&quot;: &quot;double&quot;
        ///        },
        ///        {
        ///            &quot;@type&quot;: &quot;Property&quot;,
        ///            &quot;name&quot;: &quot;TargetHumid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HvacModelPayload {
            get {
                return ResourceManager.GetString("HvacModelPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$metadata&quot;: {
        ///    &quot;$model&quot;: &quot;HVAC_MODEL_ID&quot;
        ///  },
        ///  &quot;TargetTemperature&quot;: 80,
        ///  &quot;TargetHumidity&quot;: 25
        ///}.
        /// </summary>
        internal static string HvacTwinPayload {
            get {
                return ResourceManager.GetString("HvacTwinPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///     &quot;$targetId&quot;: &quot;TARGET_TWIN_ID&quot;,
        ///     &quot;$relationshipName&quot;: &quot;RELATIONSHIP_NAME&quot;
        ///}.
        /// </summary>
        internal static string RelationshipPayload {
            get {
                return ResourceManager.GetString("RelationshipPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///     &quot;$targetId&quot;: &quot;TARGET_TWIN_ID&quot;,
        ///     &quot;$relationshipName&quot;: &quot;RELATIONSHIP_NAME&quot;,
        ///     &quot;PROPERTY_NAME&quot;: &quot;PROPERTY_VALUE&quot;
        ///}.
        /// </summary>
        internal static string RelationshipWithPropertyPayload {
            get {
                return ResourceManager.GetString("RelationshipWithPropertyPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;@id&quot;: &quot;ROOM_MODEL_ID&quot;,
        ///    &quot;@type&quot;: &quot;Interface&quot;,
        ///    &quot;displayName&quot;: &quot;Room&quot;,
        ///    &quot;description&quot;: &quot;An enclosure inside a building.&quot;,
        ///    &quot;contents&quot;: [
        ///        {
        ///            &quot;@type&quot;: &quot;Relationship&quot;,
        ///            &quot;name&quot;: &quot;containedIn&quot;,
        ///            &quot;target&quot;: &quot;FLOOR_MODEL_ID&quot;
        ///        },
        ///        {
        ///            &quot;@type&quot;: &quot;Property&quot;,
        ///            &quot;name&quot;: &quot;Temperature&quot;,
        ///            &quot;schema&quot;: &quot;double&quot;
        ///        },
        ///        {
        ///            &quot;@type&quot;: &quot;Property&quot;,
        ///            &quot;name&quot;: &quot;Humidity&quot;,
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RoomModelPayload {
            get {
                return ResourceManager.GetString("RoomModelPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$metadata&quot;: {
        ///    &quot;$model&quot;: &quot;ROOM_MODEL_ID&quot;
        ///  },
        ///  &quot;Temperature&quot;: 80,
        ///  &quot;Humidity&quot;: 25,
        ///  &quot;IsOccupied&quot;: true,
        ///  &quot;EmployeeId&quot;: &quot;Employee1&quot;
        ///}.
        /// </summary>
        internal static string RoomTwinPayload {
            get {
                return ResourceManager.GetString("RoomTwinPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;@id&quot;: &quot;ROOM_WITH_WIFI_MODEL_ID&quot;,
        ///    &quot;@type&quot;: &quot;Interface&quot;,
        ///    &quot;displayName&quot;: &quot;RoomWithWifi&quot;,
        ///    &quot;contents&quot;: [
        ///        {
        ///            &quot;@type&quot;: &quot;Property&quot;,
        ///            &quot;name&quot;: &quot;Temperature&quot;,
        ///            &quot;schema&quot;: &quot;double&quot;
        ///        },
        ///        {
        ///            &quot;@type&quot;: &quot;Property&quot;,
        ///            &quot;name&quot;: &quot;Humidity&quot;,
        ///            &quot;schema&quot;: &quot;double&quot;
        ///        },
        ///        {
        ///            &quot;@type&quot;: &quot;Property&quot;,
        ///            &quot;name&quot;: &quot;IsOccupied&quot;,
        ///            &quot;schema&quot;: &quot;boolean&quot;
        ///        },
        ///        {
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RoomWithWifiModelPayload {
            get {
                return ResourceManager.GetString("RoomWithWifiModelPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$metadata&quot;: {
        ///    &quot;$model&quot;: &quot;ROOM_WITH_WIFI_MODEL_ID&quot;
        ///  },
        ///  &quot;Temperature&quot;: 80,
        ///  &quot;Humidity&quot;: 25,
        ///  &quot;IsOccupied&quot;: true,
        ///  &quot;EmployeeId&quot;: &quot;Employee1&quot;,
        ///  &quot;WIFI_COMPONENT_NAME&quot;: {
        ///        &quot;$metadata&quot;: {
        ///        },
        ///        &quot;RouterName&quot;: &quot;Cisco1&quot;,
        ///        &quot;Network&quot;: &quot;Room1&quot;
        ///    }
        ///}.
        /// </summary>
        internal static string RoomWithWifiTwinPayload {
            get {
                return ResourceManager.GetString("RoomWithWifiTwinPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;@id&quot;: &quot;WARD_MODEL_ID&quot;,
        ///    &quot;@type&quot;: &quot;Interface&quot;,
        ///    &quot;displayName&quot;: &quot;Ward&quot;,
        ///    &quot;description&quot;: &quot;A separate partition in a building, made of rooms and hallways.&quot;,
        ///    &quot;contents&quot;: [
        ///        {
        ///            &quot;@type&quot;: &quot;Property&quot;,
        ///            &quot;name&quot;: &quot;VisitorCount&quot;,
        ///            &quot;schema&quot;: &quot;double&quot;
        ///        },
        ///        {
        ///            &quot;@type&quot;: &quot;Property&quot;,
        ///            &quot;name&quot;: &quot;HandWashPercentage&quot;,
        ///            &quot;schema&quot;: &quot;double&quot;
        ///        },
        ///        {
        ///            &quot;@type&quot;: &quot;Relationship&quot;,
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WardModelPayload {
            get {
                return ResourceManager.GetString("WardModelPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;@id&quot;: &quot;WIFI_MODEL_ID&quot;,
        ///    &quot;@type&quot;: &quot;Interface&quot;,
        ///    &quot;@context&quot;: &quot;dtmi:dtdl:context;2&quot;,
        ///    &quot;displayName&quot;: &quot;Wifi&quot;,
        ///    &quot;contents&quot;: [
        ///        {
        ///            &quot;@type&quot;: &quot;Property&quot;,
        ///            &quot;name&quot;: &quot;RouterName&quot;,
        ///            &quot;schema&quot;: &quot;string&quot;
        ///        },
        ///        {
        ///            &quot;@type&quot;: &quot;Property&quot;,
        ///            &quot;name&quot;: &quot;Network&quot;,
        ///            &quot;schema&quot;: &quot;string&quot;
        ///        }
        ///    ]
        ///}.
        /// </summary>
        internal static string WifiModelPayload {
            get {
                return ResourceManager.GetString("WifiModelPayload", resourceCulture);
            }
        }
    }
}
