// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using System.Diagnostics.CodeAnalysis;

// AZC0007: TranscriptionClient constructors use System.ClientModel credential types.
// ProjectConversationsClient
[assembly: SuppressMessage("Usage", "AZC0007", Justification = "Azure.AI.Projects.OpenAI Uses System.ClientModel instead of Azure.Core.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectConversationsClient.#ctor(System.ClientModel.Primitives.ClientPipeline,OpenAI.OpenAIClientOptions)")]
// ProjectOpenAIClient
[assembly:  SuppressMessage("Usage", "AZC0007", Justification = "Azure.AI.Projects.OpenAI.ProjectOpenAIClient Uses System.ClientModel AuthenticationTokenProvider instead of Azure.Core", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectOpenAIClient.#ctor(System.Uri,System.ClientModel.AuthenticationTokenProvider,Azure.AI.Projects.OpenAI.ProjectOpenAIClientOptions)")]
[assembly:  SuppressMessage("Usage", "AZC0007", Justification = "Azure.AI.Projects.OpenAI.ProjectOpenAIClient Uses System.ClientModel AuthenticationTokenProvider instead of Azure.Core", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectOpenAIClient.#ctor(System.ClientModel.Primitives.AuthenticationPolicy,Azure.AI.Projects.OpenAI.ProjectOpenAIClientOptions)")]
// ProjectResponsesClient
[assembly:  SuppressMessage("Usage", "AZC0007", Justification = "Azure.AI.Projects.OpenAI.ProjectResponsesClient Uses System.ClientModel AuthenticationTokenProvider instead of Azure.Core", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectResponsesClient.#ctor(System.Uri,System.ClientModel.AuthenticationTokenProvider,Azure.AI.Projects.OpenAI.ProjectResponsesClientOptions)")]
[assembly:  SuppressMessage("Usage", "AZC0007", Justification = "Azure.AI.Projects.OpenAI.ProjectResponsesClient Uses System.ClientModel AuthenticationTokenProvider instead of Azure.Core", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectResponsesClient.#ctor(System.Uri,System.ClientModel.AuthenticationTokenProvider,Azure.AI.Projects.OpenAI.AgentReference,System.String,Azure.AI.Projects.OpenAI.ProjectResponsesClientOptions)")]

[assembly:  SuppressMessage("Usage", "AZC0007", Justification = "Azure.AI.Projects.OpenAI.ProjectResponsesClient Uses System.ClientModel AuthenticationTokenProvider instead of Azure.Core", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectResponsesClient.#ctor(System.ClientModel.AuthenticationTokenProvider,Azure.AI.Projects.OpenAI.ProjectResponsesClientOptions)")]
[assembly:  SuppressMessage("Usage", "AZC0007", Justification = "Azure.AI.Projects.OpenAI.ProjectResponsesClient Uses System.ClientModel AuthenticationTokenProvider instead of Azure.Core", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectResponsesClient.#ctor(System.ClientModel.AuthenticationTokenProvider,Azure.AI.Projects.OpenAI.ProjectResponsesClientOptions,Azure.AI.Projects.OpenAI.AgentReference,System.String)")]

// AZC0015: We return AsyncCollectionResult<T> and CollectionResult<T> instead of Pageable<T>.
// ProjectConversationsClient
[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult<ProjectConversation>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectConversationsClient.CreateProjectConversation(Azure.AI.Projects.OpenAI.ProjectConversationCreationOptions,System.Threading.CancellationToken)")]
[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult<ProjectConversation>>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectConversationsClient.CreateProjectConversationAsync(Azure.AI.Projects.OpenAI.ProjectConversationCreationOptions,System.Threading.CancellationToken)")]
[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns CollectionResult<ProjectConversation>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectConversationsClient.GetProjectConversations(Azure.AI.Projects.OpenAI.AgentReference,System.Nullable{System.Int32},System.String,System.String,System.String,System.Threading.CancellationToken)")]
[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns AsyncCollectionResult<ProjectConversation>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectConversationsClient.GetProjectConversationsAsync(Azure.AI.Projects.OpenAI.AgentReference,System.Nullable{System.Int32},System.String,System.String,System.String,System.Threading.CancellationToken)")]
[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult<ProjectConversation>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectConversationsClient.GetProjectConversation(System.String,System.Threading.CancellationToken)")]
[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult<ProjectConversation>>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectConversationsClient.GetProjectConversationAsync(System.String,System.Threading.CancellationToken)")]

[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns CollectionResult<AgentResponseItem>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectConversationsClient.GetProjectConversationItems(System.String,System.Nullable{Azure.AI.Projects.OpenAI.AgentResponseItemKind},System.Nullable{System.Int32},System.String,System.String,System.String,System.Collections.Generic.IEnumerable{OpenAI.Conversations.IncludedConversationItemProperty},System.Threading.CancellationToken)")]
[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns AsyncCollectionResult<AgentResponseItem>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectConversationsClient.GetProjectConversationItemsAsync(System.String,System.Nullable{Azure.AI.Projects.OpenAI.AgentResponseItemKind},System.Nullable{System.Int32},System.String,System.String,System.String,System.Collections.Generic.IEnumerable{OpenAI.Conversations.IncludedConversationItemProperty},System.Threading.CancellationToken)")]

[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult<AgentResponseItem>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectConversationsClient.GetProjectConversationItem(System.String,System.String,System.Collections.Generic.IEnumerable{OpenAI.Conversations.IncludedConversationItemProperty},System.Threading.CancellationToken)")]
[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult<AgentResponseItem>>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectConversationsClient.GetProjectConversationItemAsync(System.String,System.String,System.Collections.Generic.IEnumerable{OpenAI.Conversations.IncludedConversationItemProperty},System.Threading.CancellationToken)")]

[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult<ReadOnlyCollection<ResponseItem>>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectConversationsClient.CreateProjectConversationItems(System.String,System.Collections.Generic.IEnumerable{OpenAI.Responses.ResponseItem},System.Collections.Generic.IEnumerable{OpenAI.Conversations.IncludedConversationItemProperty},System.Threading.CancellationToken)")]
[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult<ReadOnlyCollection<ResponseItem>>>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectConversationsClient.CreateProjectConversationItemsAsync(System.String,System.Collections.Generic.IEnumerable{OpenAI.Responses.ResponseItem},System.Collections.Generic.IEnumerable{OpenAI.Conversations.IncludedConversationItemProperty},System.Threading.CancellationToken)")]

[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult<ProjectConversation>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectConversationsClient.UpdateProjectConversation(System.String,Azure.AI.Projects.OpenAI.ProjectConversationUpdateOptions,System.Threading.CancellationToken)")]
[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult<ProjectConversation>>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectConversationsClient.UpdateProjectConversationAsync(System.String,Azure.AI.Projects.OpenAI.ProjectConversationUpdateOptions,System.Threading.CancellationToken)")]

// ProjectResponsesClient
[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult<ResponseResult>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectResponsesClient.CreateResponse(OpenAI.Responses.CreateResponseOptions,System.Threading.CancellationToken)")]
[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult<ResponseResult>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectResponsesClient.CreateResponse(System.Collections.Generic.IEnumerable{OpenAI.Responses.ResponseItem},System.String,System.Threading.CancellationToken)")]
[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult<ResponseResult>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectResponsesClient.CreateResponse(System.String,System.String,System.Threading.CancellationToken)")]
[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult<ResponseResult>>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectResponsesClient.CreateResponseAsync(OpenAI.Responses.CreateResponseOptions,System.Threading.CancellationToken)")]
[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult<ResponseResult>>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectResponsesClient.CreateResponseAsync(System.Collections.Generic.IEnumerable{OpenAI.Responses.ResponseItem},System.String,System.Threading.CancellationToken)")]
[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns Task<ClientResult<ResponseResult>>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectResponsesClient.CreateResponseAsync(System.String,System.String,System.Threading.CancellationToken)")]

[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult<StreamingResponseUpdate>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectResponsesClient.CreateResponseStreaming(OpenAI.Responses.CreateResponseOptions,System.Threading.CancellationToken)")]
[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult<StreamingResponseUpdate>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectResponsesClient.CreateResponseStreaming(System.Collections.Generic.IEnumerable{OpenAI.Responses.ResponseItem},System.String,System.Threading.CancellationToken)")]
[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns ClientResult<StreamingResponseUpdate>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectResponsesClient.CreateResponseStreaming(System.String,System.String,System.Threading.CancellationToken)")]
[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns AsyncCollectionResult<StreamingResponseUpdate>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectResponsesClient.CreateResponseStreamingAsync(OpenAI.Responses.CreateResponseOptions,System.Threading.CancellationToken)")]
[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns AsyncCollectionResult<StreamingResponseUpdate>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectResponsesClient.CreateResponseStreamingAsync(System.Collections.Generic.IEnumerable{OpenAI.Responses.ResponseItem},System.String,System.Threading.CancellationToken)")]
[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns AsyncCollectionResult<StreamingResponseUpdate>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectResponsesClient.CreateResponseStreamingAsync(System.String,System.String,System.Threading.CancellationToken)")]

[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns CollectionResult<ResponseResult>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectResponsesClient.GetProjectResponses(Azure.AI.Projects.OpenAI.AgentReference,System.String,System.Nullable{System.Int32},System.String,System.String,System.String,System.Threading.CancellationToken)")]
[assembly:  SuppressMessage("Usage", "AZC0015", Justification = "Returns AsyncCollectionResult<ResponseResult>.", Scope = "member", Target = "~M:Azure.AI.Projects.OpenAI.ProjectResponsesClient.GetProjectResponsesAsync(Azure.AI.Projects.OpenAI.AgentReference,System.String,System.Nullable{System.Int32},System.String,System.String,System.String,System.Threading.CancellationToken)")]
