Param(
  [Parameter(Mandatory=$true)]  [string]$subscriptionId,
  [Parameter(Mandatory=$false)] [string]$region            = "eastasia",
  [Parameter(Mandatory=$false)] [string]$resourceGroupName = "pslibtestosprofile",
  [Parameter(Mandatory=$false)] [string]$keyVaultName      = "pslibtestkeyvault"
)
$PfxCertifcate = "MIIKQQIBAzCCCgEGCSqGSIb3DQEHAaCCCfIEggnuMIIJ6jCCBhMGCSqGSIb3DQEHAaCCBgQEggYAMIIF/DCCBfgGCyqGSIb3DQEMCgECoIIE/jCCBPowHAYKKoZIhvcNAQwBAzAOBAiLr4TjROl2hAICB9AEggTY3kRxvqPu2H85Jx6yAVq8oDCpfWKWJ0aXp5L+vI1saIaQk+BzEJ1r8gVuEsB23DWRZvwCwToH0rckkWrPARvvHNsLnwZHgjf6vBNyudxD4XHWSifjKpWwmlwv2fxvBORpKHbf+WZJNGGncriAhLjvCcepuKOO3NL1I7igc+xaSCbXd09T1oAHrTy17MyGvnG7kWbgugkoq/otmroJ4sJY4n4V9IzxiNb6PW4KxqgQdMk0S9I1wlM7wZZH3WB0nB89ztV/dAOoi1lQ1HUI28G3YC0YJQz5cM1d2G74ZFEX3QXRw3Yr+ja7mKp+L3T1B7FVlmkk86L5ak2192w/v35C6h4gw36Qz7waRRNVxIj7S2h06idSUDYPsOMYorXV6/VFP4+iOV/lCO0E83M04KCRjPimDyyWffJayWUs2btrdK42fiuBsZPxXykBIExHa35K0cIhG0BKQlAUypywXVDgwrdymwp+oO/UYA6seV8J1ywe+nCKbwyygDE/1pFxqLspnI1khmMZ0w8yJzRiGzmDEgsa98/vFndh4UwcXbproTIylormxSt0XFLOLWwySNGZo1jnVU7uLRM6DNwU5j36KlgY8dHv/11CwRgl3ds/+azrxTnURxPuA6R7TO4PVgfAi/2NyLC9LbeyBz+Qagdkeq9GyL2zfjCnrZPmanyM42S23R7jQ/8Ao8NmpBkgqqg8lNgIbB5cH6LslqhdIN41iQjuKAWLOiD+pFuiXZpymL0qQm6TSMTLrld1KaTQg1mh3544YmYx4m7VezQ3Td45vCxhOo4BKC3W4jGMMBa8STVhEVlNwwuV6xAz/YOA/is+4qqciXOOScnNlWS06AgiBkTs4kqelSuh8K+z6AtemfUVE08p+YwDp7bFuvOu/WwE+GoDryWkPgmLsYYsToduKOlOvtFIsJw3Vv/uINDlKcDUe1ttyPUgISAEgvE59JFgLNjAzmnXpCslX9u1V66jnb7WTzA6+2MWkWn1+qiYLQMDDEtJTu9E7JtkIppRpTid7yL77MgvOqw6ZAGNyXnpe+J9pvAN+XFvk/guFxB0KYhIVOetpsnFqKUoZQcPPspW4r8z/EDhCc+KU/EaDm1a81/XdqjRreJUeZeaZCI+rINghaY1iG/HueL7a4LncDHKP8NiCBJMNU0oFp/j6gY0fwTLe+EFRyOVdXB8Ho9SxcVAogp90sh8MstCEs9bUJfSLx3bloA1/ZqUhEevfnlXEJmMpTDa6Q25Me0CQ1uuswSa3sd/QKJCL6B6Cz/xsCfTo1a6t3wDL7NhfaGCgF0zRLsqDgnmN/m8pVipKj3siZzoVe21kiz5YT9WarRkPYkGkOpqidnnrt2ube4daWVbJnH2doQegkHll+Elt/NM10Wvw8I2VGk1xMHqp7IS5JSTx9tG82GIANJXp6PiRId3Af5gNvQ2saAP8lYtG4n6WV5sbTuJnLYsAmN+Zri2Zhce92QSUUMoo9iGETw3m8kYJuAw/lovTocdMkAMkHHIQQHMreQj4INf4hhzJqRPO3NpzN0XXRewZeTZOJVLIPu9rU6HoI+HXXvr2Virb75SFQ26OAQD9bYmF6N6Dn1prGPS0A8TxStJDM4v5y0PEZjUSyBDyJyy+8/kiki+YnIwtByDf6XNCcpbEjGB5jANBgkrBgEEAYI3EQIxADATBgkqhkiG9w0BCRUxBgQEAQAAADBbBgkqhkiG9w0BCRQxTh5MAHsARQA4ADYANgA2ADAAMgA3AC0AOAA3ADIAMgAtADQAQgA5AEEALQBBADAAMQAyAC0AMQBEADUANQBFAEYANgBCADkAOQAwADUAfTBjBgkrBgEEAYI3EQExVh5UAE0AaQBjAHIAbwBzAG8AZgB0ACAAQgBhAHMAZQAgAEMAcgB5AHAAdABvAGcAcgBhAHAAaABpAGMAIABQAHIAbwB2AGkAZABlAHIAIAB2ADEALgAwMIIDzwYJKoZIhvcNAQcGoIIDwDCCA7wCAQAwggO1BgkqhkiG9w0BBwEwHAYKKoZIhvcNAQwBBjAOBAjvKiI9VQPquAICB9CAggOI4XwUxGBKGWzQ7mkexVseWL03RcLJhn56vTY4CFMpGzxaQz8j3TPwTcYh7FbDzqLEZiiknK6e5vM/maqbAacsenOzyAyx5/aCM6OWVDqtPZlSVC0tRtths+JuUMUMweoAZBeIYqjMyd/wQ+WbvcMdfrh/A3xcFUSJOpoSmelX9bPH6GRI2lgBR0OuMfvkLJQJeKm0fYtGsSZm9Z3Xagyo0EtBYLCWpSQM2jrv18Hty/MmMjO+ZiNeVOQFEfgiK4pfK0AvXnQ1ls1vCjneSNTIKRKFCW7ULffbDDMZrJu/YD1kFLbQ26n9dam+rbpb3m7SkrNSadNnnRVGY7DWO+q0NzWFazHYxzGIcxTCdPijsABQgG3Iv2rB02C8Tt8w51/pa6ow1IbzvpeoRjSo8sBeY+DK7+Avtftn5F2BeiRG6hjUNt7y8RW/qOm7csakO5YccXKYpwQLyegM0jA4DobXkKzw1qgCNXgUu07bbwsBReeQSe8Sm7mVE/RFwhggoJvrtA/NYV7/P3b0rqOThwayDV49crBdE1eIIz651cxZPW/WX9w5QcQpSk4+BC4U+dLdev/cCsZUas9ZUlCDCdg+xQzSZnHwYUozBH+y+YmvpJBsf5nBDpFn452U3VQBgwQQhkr9CwZJqTFTaPogBRFaYybQL9kJJ2JMLa74lfGjWiPn01ePrQP0fmhaTKsKTzgZXFGjXug8gsZ5WKlNAkOiRPUtZBI6Ps7r1eHtCd45kyynFiUwhAxx0TnGD3RKjjf6sI7rr3O7bzPlOsWfVWBAqS/yAk2hHK9YHsTLz5fjPwb/4NKrrNSjCz1OOqOdK5gemYcGY8liyp4YzDaXsqEnpaJ/ddZ40/dbwXtZpWvPV0h4WHwoH3coKsEyaPBfeH4Y21mtm+QvrSnrIhX4zUrcFiIfadJF57jg3Ceya30bT+V2Kzbx9z5jy3e4DR3/9di/KAd+vHI5QkHDm2ZbuMjmT08oGDSwohlgzGiIHl/cf5Vvp5zI+1LIIphBw7Qqt9VVxsaggH18T3vbbKU9ZyLdmSvqw1N51v7tqzLEO0RlR9ImlyvfCbceXt732ttXzdbFLY8k25uSBvRm1IfNZU8qPieJuoqhE7IRdSWyH7bpVGyyRtGqIxH7P0obgF69qn5TCHv70ZX7RNP47JKIJmxPDdqguyL2XOWE3JjpejrIa7OAEILb3cdkXjA3MB8wBwYFKw4DAhoEFHfFQWPANmPAPKnKR8G/SLWuGF0NBBSpg+gHp3kEPGg+5XppbUCgBNrSPQ=="
$PfxCertifcatePassword = "CRP-Core"

Switch-AzureMode AzureResourceManager
Select-AzureSubscription -SubscriptionId $subscriptionId
New-AzureResourceGroup -Name $resourceGroupName -Location $region
$keyVault = New-AzureKeyVault -ResourceGroupName $resourceGroupName -Location $region -VaultName $keyVaultName -EnabledForDeployment

$CertificateJson = @"
{
  "data":     "$PfxCertifcate",
  "dataType": "pfx",
  "password": "$PfxCertifcatePassword"
}
"@

$CertificateBytes = [System.Text.Encoding]::UTF8.GetBytes($CertificateJson)
$JsonEncodedCertificate = [System.Convert]::ToBase64String($CertificateBytes)
$secret = ConvertTo-SecureString -String $JsonEncodedCertificate -AsPlainText -Force
$secretName = "WinRM"
$secret = Set-AzureKeyVaultSecret -VaultName $keyVaultName -Name $secretName -SecretValue $secret

Write-Host "Please Use the values below during recording:"
Write-Host
Write-Host -ForegroundColor Green "KeyVaultId: " $keyVault.ResourceId
Write-Host
Write-Host -ForegroundColor Green "CertificateUrl: " $secret.Id
Write-Host
Write-Host
Write-Host "After recording completes, Please  delete the whole resource group which contains the key vault, using the following command"
Write-Host -ForegroundColor Yellow  "  Remove-AzureResourceGroup -Name $resourceGroupName "
